package de.goldendeveloper.discord.entertainment;

import de.goldendeveloper.mysql.entities.Database;
import de.goldendeveloper.mysql.entities.Row;
import de.goldendeveloper.mysql.entities.Table;
import org.jetbrains.annotations.NotNull;

public class FillTableIfisEmpty {

    public static void fillSerienTable(Database db, @NotNull Table table) {
        table.insert(new Row(table, db).with("name", "The Bodyguard"));
        table.insert(new Row(table, db).with("name", "Mac Gyver (2016)"));
        table.insert(new Row(table, db).with("name", "The Witcher"));
        table.insert(new Row(table, db).with("name", "Blindspot"));
        table.insert(new Row(table, db).with("name", "Scorpion"));
        table.insert(new Row(table, db).with("name", "The Mandalorian"));
        table.insert(new Row(table, db).with("name", "Mia and Me"));
        table.insert(new Row(table, db).with("name", "Der kleine Prinz"));
        table.insert(new Row(table, db).with("name", "PRODIGAL SON"));
        table.insert(new Row(table, db).with("name", "MARVELS IRON FIST"));
        table.insert(new Row(table, db).with("name", "LUCIFER"));
        table.insert(new Row(table, db).with("name", "LOST IN SPACE"));
        table.insert(new Row(table, db).with("name", "LETHAL WEAPON"));
        table.insert(new Row(table, db).with("name", "HAWAII FIVE-0"));
        table.insert(new Row(table, db).with("name", "Young Sheldon"));
        table.insert(new Row(table, db).with("name", "Forever"));
        table.insert(new Row(table, db).with("name", "Castel"));
    }

    public static void fillEmojiGame(Table table, String Difficulty, String columnBegriff, String emojiOne, String emojiTwo) {
       insert(table, columnBegriff, "Fernbedienung", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Rasierschaum", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Laderampe", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Lichterkette", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Rauhfasertapete", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Tannenbaumständer", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Siebträgermaschine", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Lampenfassung", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Schneeketten", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Konfettiregen", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Geschenkpapier", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Wollschal", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Schleifenbank", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Rundumleuchte", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Kugelbahn", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Schaukelpferd", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Verhaltensmuster", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Handcreme", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Räuchermännchen", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Querschläger", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Adventskalender", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Brillenputztuch", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Hauptgewinn", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Wäscheklammer", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Spiegelreflexkamera", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Pralinenschachtel", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Drehbuch", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Kinderstuhl", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Sonnenblumenöl", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Christbaumkugel", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Zungenkuss", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Ladegerät", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Schreihals", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Glühwein", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Osterhase", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Teppichklopfer", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Schokokringel", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Vollpfosten", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Sprudelwasser", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Kichstarter", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Eierlikör", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Neujahresgruß", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Glatteis", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Weihnachtsgans", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Lebkuchenherz", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Trostpreis", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Versuchskaninchen", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Regalboden", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Mistelzweig", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Hebamme", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Manschettenknopf", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Schneegestöber", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Renntier", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Winterstiefel", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Flussufer", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Pfauenfeder", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Ohrensessel", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Verlobungsring", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Nassrasur", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Garagentür", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Weihnachtspost", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Glasreiniger", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Intimpiercing", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Gießkanne", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Hackebeil", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Tiefkühlfach", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Treppenhaus", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Fahrradschlauch", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Kreißsaal", Difficulty, "easy", emojiOne, "", emojiTwo, "");
       insert(table, columnBegriff, "Mitesser", Difficulty, "easy", emojiOne, "", emojiTwo, "");
    }

    public static void insert(@NotNull Table table, String columnBegriff, String columnWert, String Difficulty, String DifficultyWert, String emojiOne, String emojiOneWert, String emojiTwo, String emojiTwoWert) {
        table.insert(new Row(table, table.getDatabase()).with(columnBegriff, columnWert).with(Difficulty, DifficultyWert).with(emojiOne, emojiOneWert).with(emojiTwo, emojiTwoWert));
    }

    public static void fillJokeTable(Database db, @NotNull Table table) {
        String column = "name";
        table.insert(new Row(table, db).with(column, "Aus welchem Land kommen Schornsteinfeger? Aus Rußland!"));
        table.insert(new Row(table, db).with(column, "Axl Rose hat seiner nordfriesischen Freundin ein Liebeslied geschrieben: Sweet Child of Moin."));
        table.insert(new Row(table, db).with(column, "Beim Zahnarzt: Das kann jetzt ein bisschen weh tun. - Kein Problem. - Ich hab seit 3 Jahren ein Verhältnis mit Ihrer Frau."));
        table.insert(new Row(table, db).with(column, "Brennholzverleih."));
        table.insert(new Row(table, db).with(column, "Dem Reh fallen die Haare aus. Der Doktor weist es in eine Rehhaarklinik ein."));
        table.insert(new Row(table, db).with(column, "Der Erfinder des Post-It-Zettels ist gestorben. Die tröstliche Nachricht: Es gibt ein Kleben nach dem Tod."));
        table.insert(new Row(table, db).with(column, "Der Pfannkuchenbäcker ist an seinem eigenen Teig erstickt. Einfach crepiert."));
        table.insert(new Row(table, db).with(column, "Egal wie gut Du fährst, Züge fahren Güter."));
        table.insert(new Row(table, db).with(column, "Ein Besoffener beschimpft und beleidigt ein Helium. Und was macht es? Es reagiert nicht."));
        table.insert(new Row(table, db).with(column, "Ein Gockel bekommt eine Blasterpistole. Aus versehen bringt er damit alle Hühner um. Da ist der Hahn Solo."));
        table.insert(new Row(table, db).with(column, "Einbruch bei Adidas. Was schickt die Polizei? Drei Streifen."));
        table.insert(new Row(table, db).with(column, "Fliegt ein Kuckuck übers Meer. Grüßt ihn ein Hai:Hi"));
        table.insert(new Row(table, db).with(column, "Fragt der Polizist: Haben sie Restalkohol? - Nee, alles ausgetrunken."));
        table.insert(new Row(table, db).with(column, "Geben sich verliebte Anästhesisten eigentlich Narkosenamen?"));
        table.insert(new Row(table, db).with(column, "Gehen zwei Zahnstocher durch den Wald. Kommt ein Igel vorbei. Sagt der eine Zahnstocher: Ich wusste gar nicht, dass hier ein Bus fährt."));
        table.insert(new Row(table, db).with(column, "Geht ein Cowboy zum Friseur. Als er wieder rauskommt ist sein Pony weg."));
        table.insert(new Row(table, db).with(column, "Geht eine schwangere Frau zum Bäcker und sagt:Ich bekomme ein Brot."));
        table.insert(new Row(table, db).with(column, "Huch, meine Uhr ist runter gefallen. Ich kann sie nicht aufheben. - Ich hab kein Uhrheberrecht."));
        table.insert(new Row(table, db).with(column, "Hüpft ein Rudel Gurken durch den Wald. Was ist falsch? Gurken sind keine Rudeltiere."));
        table.insert(new Row(table, db).with(column, "Ich bin so unentschlossen. Als japanischer Krieger wäre ich ein Nunja."));
        table.insert(new Row(table, db).with(column, "Ich brauche eine Krankschreibung? Was fehlt ihnen denn? Eine Krankschreibung."));
        table.insert(new Row(table, db).with(column, "Ich habe bei den Weight Watchers angerufen: Aber keine hat abgenommen."));
        table.insert(new Row(table, db).with(column, "Ich habe bei einem Brötchen angerufen, aber:War belegt."));
        table.insert(new Row(table, db).with(column, "Ich habe bei nem DJ angerufen:Der hat einfach aufgelegt."));
        table.insert(new Row(table, db).with(column, "Ich habe bei Spiderman angerufen, aber der hatte kein Netz."));
        table.insert(new Row(table, db).with(column, "Ich habe beim Arzt angerufen:Ich wurde aber nicht verbunden."));
        table.insert(new Row(table, db).with(column, "Ich habe beim Bäcker angerufen, da ging aber nur die Mehlbox ran."));
        table.insert(new Row(table, db).with(column, "Ich habe beim Metzger angerufen, aber kein Schwein ging ran."));
        table.insert(new Row(table, db).with(column, "Ich habe das Herz eines Löwen ...und lebenslanges Verbot im Leipziger Zoo."));
        table.insert(new Row(table, db).with(column, "Ich habe einem Hipster ans Schienbein getreten.Jetzt hopster."));
        table.insert(new Row(table, db).with(column, "Ich habe einen total lieben Hund, der ist so ruhig - der hat sogar den No -Bell preis gewonnen."));
        table.insert(new Row(table, db).with(column, "Ich habe in der Botschaft angerufen, aber keiner ging ran.War wohl Kanada."));
        table.insert(new Row(table, db).with(column, "Ich habe meiner Frau zu Weihnachten einen Nerz geschenkt und jetzt weigert sie sich, das Tier zufüttern."));
        table.insert(new Row(table, db).with(column, "Ich wollte einen Witz über die Deutsche Bahn machen, aber ich wusste nicht ob der ankommt."));
        table.insert(new Row(table, db).with(column, "Im Restaurant:Isst Du gerne wild?-Nein, ganz normal und langsam. "));
        table.insert(new Row(table, db).with(column, "In Mittelamerika gibt es kaum gute Tapezierer - aber dafür Guatemala !"));
        table.insert(new Row(table, db).with(column, "In St.Pauli wurde gestern ein Sarg gefunden.Aber der ging und ging nicht auf.War wohl ein Zuhälter drin ? "));
        table.insert(new Row(table, db).with(column, "In welchem Land ist man so langsam wie eine Schnecke ?In Kriechenland."));
        table.insert(new Row(table, db).with(column, "In welcher Maßeinheit messen Hunde ihre Temperatur ? In Belgrad. "));
        table.insert(new Row(table, db).with(column, "Klaus war echt nervig, deshalb bekam er nie frische Brötchen.Klaus störte Bäcker. "));
        table.insert(new Row(table, db).with(column, "Kommt ein Dachdecker in eine Bar. —Sagt der Wirt: Der geht aufs Haus. "));
        table.insert(new Row(table, db).with(column, "Kommt ein Frosch in den Milchladen.Fragt die Verkäuferin: Was willst du denn? - Sagt der Frosch:Quak. "));
        table.insert(new Row(table, db).with(column, "Kommt ein Igel in die Konditorei:Einmal Rumkugeln bitte-- Wenn sie wollen, wir haben gerade frisch gewischt."));
        table.insert(new Row(table, db).with(column, "Kommt ein Pferd in den Blumenladen:Haben sie Mageriten? (ma  geritten)"));
        table.insert(new Row(table, db).with(column, "Mein Arzt hat eine südamerikanische Augenkrankheit bei mir diagnostiziert - ich Chile."));
        table.insert(new Row(table, db).with(column, "Mein Hund ein echter Charmeur.Immer wenn ich ihn fragt:Na wie sehe ich aus, sagt er: Wau !"));
        table.insert(new Row(table, db).with(column, "Mir ist kalt - ich geh mal in die Ecke.Da sind 90 Grad. "));
        table.insert(new Row(table, db).with(column, "Neulich im Tatort: Wo waren Sie zur Tatzeit ? -Im Internet !"));
        table.insert(new Row(table, db).with(column, "Papa, in Ägypten ist nächste Woche auch keine Schule ! --  Ok ?  --  Ja, die haben da Sphinxferien !"));
        table.insert(new Row(table, db).with(column, "Sagt der Pessimist: Schlimmer geht nicht! - Sagt der Optimist:Doch!"));
        table.insert(new Row(table, db).with(column, "Sagt der Walfisch zum Tuhnfisch: Was wollen wir tun, Fisch? Sagt der Thunfisch:Du hast die Wahl, Fisch! "));
        table.insert(new Row(table, db).with(column, "Sagt die eine Kerze zur anderen:Du, ist Wasser eigentlich gefährlich ? -Sagt die andere:Davon kannst Du ausgehen."));
        table.insert(new Row(table, db).with(column, "Sagt die eine Sicherung zur anderen:Lass uns zusammen durchbrennen !"));
        table.insert(new Row(table, db).with(column, "Sagt die eine Wand zur anderen Wand: Wir treffen uns an der Ecke."));
        table.insert(new Row(table, db).with(column, "Sagt die Erbse zur anderen: Vorsicht, da ist eine Trepepepepepepepepe..."));
        table.insert(new Row(table, db).with(column, "Schicke Unterwäsche !-Wohin ? "));
        table.insert(new Row(table, db).with(column, "Sprechstundenhilfe: Warum tragen Sie eine Augenklappe ?  Ich bin Piratpatient. "));
        table.insert(new Row(table, db).with(column, "Steht ein Baum allein im Wald..."));
        table.insert(new Row(table, db).with(column, "Steht ein Pils im Wald.Kommt ein Hase und trinkt es aus.Und warum steht ein Pils im Wald ? Weil die Tannen zapfen."));
        table.insert(new Row(table, db).with(column, "Stelle dir zwei bayerisch getrachtet Personen vor, die die Daumen nach oben recken.In der anderen Hand Bier und Brezn.Was ist das ? Confirmation Bayers"));
        table.insert(new Row(table, db).with(column, "Stiftung Warentest hat Besteck getestet.Das Messer hat am besten abgeschnitten."));
        table.insert(new Row(table, db).with(column, "Tage an denen man plant, Bananen zu essen, nennt man Bananenplantage."));
        table.insert(new Row(table, db).with(column, "Tonic ohne Alkohol ist übrigens ginlos."));
        table.insert(new Row(table, db).with(column, "Treffen sich zwei Magneten:Was zieh ich heute bloß an?"));
        table.insert(new Row(table, db).with(column, "Unterhalten sich zwei Fliesenleger:Wo sind denn die ganzen Fliesen hin? Oh, die muss ich wohl verlegt haben."));
        table.insert(new Row(table, db).with(column, "Wann gehen U - Boote unter ? Am Tag der offenen Tür."));
        table.insert(new Row(table, db).with(column, "Warum darf das Neutron nicht in die Disco?Heute nur geladene Gäste !"));
        table.insert(new Row(table, db).with(column, "Warum findet ein Henker nie den Rückweg ? Weil der nur die Hinrichtung kennt. "));
        table.insert(new Row(table, db).with(column, "Warum fliegen Störche im Winter in den Süden?-Weil Laufen zu lange dauern würde. "));
        table.insert(new Row(table, db).with(column, "Warum gehen Ameisen am Sonntag nicht in die Kirche ? Weil Ameisen Insekten sind. "));
        table.insert(new Row(table, db).with(column, "Warum gibt es in Booten keinen Honig ? Weil es auf Schiffen ka -bienen gibt. "));
        table.insert(new Row(table, db).with(column, "Warum haben diese Fische so ausgesprochen gute Zähne ?Das sind Kariesprofilachse. "));
        table.insert(new Row(table, db).with(column, "Warum haben Fische Schuppen?Damit sie ihre Fahrräder unterstellen können."));
        table.insert(new Row(table, db).with(column, "Warum ist der Florist über seine Lieferung traurig?Sie ist eingegangen. "));
        table.insert(new Row(table, db).with(column, "Warum klaut Robin Hood Deo ? Um es unter den Armen zu verteilen !"));
        table.insert(new Row(table, db).with(column, "Warum können Seeräuber schlecht mit Kreisen Rechnen ? Weil sie Pi -Raten !"));
        table.insert(new Row(table, db).with(column, "Warum können Skelette so schlecht lügen ?Die sind so einfach zu durchschauen."));
        table.insert(new Row(table, db).with(column, "Warum leben Haie im Salzwasser ? Weil sie von Pfefferwasser niesen müssen. "));
        table.insert(new Row(table, db).with(column, "Warum muss die Spinne grillen ? Sie ist ein Weberknecht. "));
        table.insert(new Row(table, db).with(column, "Warum sind bei IKEA Pfeile am Boden ? Weil es ein Einrichtungshaus ist."));
        table.insert(new Row(table, db).with(column, "Warum sind Fußballer eine Gefahr im Straßenverkehr ? Weil sie bei rot gehen müssen. "));
        table.insert(new Row(table, db).with(column, "Warum steht die Freiheitsstatue in New York ? Weil sie sich nicht setzen kann. "));
        table.insert(new Row(table, db).with(column, "Warum summen Bienen ? Weil sie den Text nicht kennen. "));
        table.insert(new Row(table, db).with(column, "Warum wachsen auf dem Mond keine Blumen ? Zu wenig Erde."));
        table.insert(new Row(table, db).with(column, "Was bekommt ein Kannibale, der zu spät zum Essen kommt ? Die kalte Schulter."));
        table.insert(new Row(table, db).with(column, "Was benutzt ein Bär als Eingabegerät?Eine Tatzatur."));
        table.insert(new Row(table, db).with(column, "Was bestellt ein Maulwurf im Restaurant? —Ein Drei -Gänge - Menü. "));
        table.insert(new Row(table, db).with(column, "Was denken sich die Gletscher zum Klimawandel ? Wir werden Seen."));
        table.insert(new Row(table, db).with(column, "Was erzählen sich holländische Süßspeisen am liebsten ? Vla - chwitze. "));
        table.insert(new Row(table, db).with(column, "Was erzählt Weizen sich gegenseitig beim Campen ? Grieselgeschichten. "));
        table.insert(new Row(table, db).with(column, "Was essen Autos am liebsten ? —Parkplätzchen. "));
        table.insert(new Row(table, db).with(column, "Was essen Piraten am liebsten ? —Kapern. "));
        table.insert(new Row(table, db).with(column, "Was findet man beim Kannibalen in der Dusche ? —Head and Shoulders. "));
        table.insert(new Row(table, db).with(column, "Was freut sich und stinkt ? -Das Gefurztagskind. "));
        table.insert(new Row(table, db).with(column, "Was für ein Gefühl hatte Mozart beim Komponieren ?Einen Haydn -Spaß. "));
        table.insert(new Row(table, db).with(column, "Was gibt es bei Olympia—Teilnehmern zum Nachtisch ? —Fackelpudding !"));
        table.insert(new Row(table, db).with(column, "Was gräbt und ist aus der Puste ? Eine Schnaufel. "));
        table.insert(new Row(table, db).with(column, "Was hat acht Arme und fliegt durchs Weltall?Eine Krakete."));
        table.insert(new Row(table, db).with(column, "Was hat acht Beine und schummelt?Eine Mogelspinne."));
        table.insert(new Row(table, db).with(column, "Was hat ein Mann, der im Dreieck läuft ? Kreislaufprobleme. "));
        table.insert(new Row(table, db).with(column, "Was hat einen Beutel und schießt ?Ein Penguruh."));
        table.insert(new Row(table, db).with(column, "Was hat Haare und wird gebraten ?Bartkartoffeln. "));
        table.insert(new Row(table, db).with(column, "Was hoppelt über die Wiese und raucht aus den Ohren ?Ein Kaminchen."));
        table.insert(new Row(table, db).with(column, "Was isst eine Sadomaso Frau vor Weihnachten ? Domina - Steine. "));
        table.insert(new Row(table, db).with(column, "Was isst Familie Biber zu abend ?Tischstäbchen. "));
        table.insert(new Row(table, db).with(column, "Was ist braun und hilft dir, wenn du traurig bist ? Ein Trost - brot. "));
        table.insert(new Row(table, db).with(column, "Was ist braun und hängt mit nem Warndreieck im Baum ?Ein Pannenzapfen."));
        table.insert(new Row(table, db).with(column, "Was ist braun und schwimmt unter Wasser ? Ein U - Brot. "));
        table.insert(new Row(table, db).with(column, "Was ist braun, kann fliegen und macht Kindern die Zähne kaputt ? -Die Toffi - Fee !"));
        table.insert(new Row(table, db).with(column, "Was ist braun, lebt im Nil und schmeckt lecker ? Ein Schokodil. "));
        table.insert(new Row(table, db).with(column, "Was ist braun, lecker und gesund?Schogolade. "));
        table.insert(new Row(table, db).with(column, "Was ist bunt und will dringend aus dem Zimmer raus ?Ein Fluchtsalat."));
        table.insert(new Row(table, db).with(column, "Was ist bunt, leuchtet und kann nicht schwimmen?ein Bagger mit Lichterkette."));
        table.insert(new Row(table, db).with(column, "Was ist bunt, süß und ein bisschen einfach gestrickt ? Ein Dummibärchen."));
        table.insert(new Row(table, db).with(column, "Was ist das agressivste Milchprodukt?Schlagsahne."));
        table.insert(new Row(table, db).with(column, "Was ist das Gegenteil von Japan ? Neinpan."));
        table.insert(new Row(table, db).with(column, "Was ist das Wichtigste an den Elefanten?Das zweite E, sonst wären es nur 11 Anten. (bayerisch vorgelesen)"));
        table.insert(new Row(table, db).with(column, "Was ist der unförmigste Seevogel von Nordfriesland ? Die Amöve."));
        table.insert(new Row(table, db).with(column, "Was ist die größte Anerkennung unter Aquarellisten ? Verläuft bei Dir!"));
        table.insert(new Row(table, db).with(column, "Was ist durchsichtig, stinkt und ignorant? Ein Schnurz."));
        table.insert(new Row(table, db).with(column, "Was ist ein Cowboy ohne Pferd? Ein Sattelschlepper."));
        table.insert(new Row(table, db).with(column, "Was ist ein Keks unter einem Baum? Ein schattiges Plätzchen."));
        table.insert(new Row(table, db).with(column, "Was ist ein nackter Ritter? Ent - rüstet!"));
        table.insert(new Row(table, db).with(column, "Was ist eine Glühbirne, die schockiert zu Boden fällt?Fassungslos!"));
        table.insert(new Row(table, db).with(column, "Was ist eine Kastanie hinter Gittern? Eine Knastanie."));
        table.insert(new Row(table, db).with(column, "Was ist gelb und flattert im Wind? Eine Fahnane."));
        table.insert(new Row(table, db).with(column, "Was ist gelb und hüpft durch den Wald?Ein Postfrosch."));
        table.insert(new Row(table, db).with(column, "Was ist gelb und kann nicht schwimmen ? Ein Bagger. Und warum? Weil er nur einen Arm hat."));
        table.insert(new Row(table, db).with(column, "Was ist gelb und läuft den Baum hoch?Ein Posthörnchen."));
        table.insert(new Row(table, db).with(column, "Was ist gelb und schießt ? Eine Banone."));
        table.insert(new Row(table, db).with(column, "Was ist gelb und schwimmt über n See? Eine Schwanane."));
        table.insert(new Row(table, db).with(column, "Was ist gelb und steht am Fenster ? -Eine Spannanas."));
        table.insert(new Row(table, db).with(column, "Was ist gesund, kräftig und spielt den beleidigten?Das andere Schmollkornbrot."));
        table.insert(new Row(table, db).with(column, "Was ist groß, braun und schreibt undeutlich ? Ein Kritz - li - bär."));
        table.insert(new Row(table, db).with(column, "Was ist groß, grau und interessiert niemanden ? Ein Irrelephant."));
        table.insert(new Row(table, db).with(column, "Was ist groß, grau und ruft gleich an?Ein Telefant."));
        table.insert(new Row(table, db).with(column, "Was ist grün und fliegt durchs Weltall? Ein Salatelit."));
        table.insert(new Row(table, db).with(column, "Was ist grün und fährt Pandabären zur Arbeit ? Ein Bam - bus."));
        table.insert(new Row(table, db).with(column, "Was ist grün und gewinnt jedes Rennen?Ein Schnellerie."));
        table.insert(new Row(table, db).with(column, "Was ist grün und hüpft durch den Wald?Ein Rudel Gurken."));
        table.insert(new Row(table, db).with(column, "Was ist grün und liegt im Sarg?Eine Sterbse."));
        table.insert(new Row(table, db).with(column, "Was ist grün und macht die Toilette sauber?Ein Klokodil."));
        table.insert(new Row(table, db).with(column, "Was ist grün und schnarcht am Wegesrand ? Eine Pennnessel."));
        table.insert(new Row(table, db).with(column, "Was ist grün und sitzt auf dem Klo ? Der Kacktus."));
        table.insert(new Row(table, db).with(column, "Was ist grün und tut weh, wenn man es ins Auge kriegt ? Ein Billardtisch."));
        table.insert(new Row(table, db).with(column, "Was ist grün und will dringend ins Zimmer ? Ein Klopfsalat."));
        table.insert(new Row(table, db).with(column, "Was ist grün, blind und kann singen ? Kiwi Wonder."));
        table.insert(new Row(table, db).with(column, "Was ist grün, hängt an der Türklinke und guckt durchs Schlüsselloch ? Ein Spionat."));
        table.insert(new Row(table, db).with(column, "Was ist grün, sauer und versteckt sich vor der Polizei ? Ein Essig - Schurke."));
        table.insert(new Row(table, db).with(column, "Was ist grün, schlau und stellt viele Fragen ? -Günther Lauch."));
        table.insert(new Row(table, db).with(column, "Was ist grün, sitzt auf einem Baum und wenn es runterfällt bist Du verletzt ? Ein Billiardtisch."));
        table.insert(new Row(table, db).with(column, "Was ist grün, springt durchs Gras und ist super happy ? Eine Freuschrecke. "));
        table.insert(new Row(table, db).with(column, "Was ist heiß und flauschig ? Eine Fellkartoffel. "));
        table.insert(new Row(table, db).with(column, "Was ist klein und schwarz und dreht sich auf der Wiese ? Ein Maulwurf beim Hammerwerfen. "));
        table.insert(new Row(table, db).with(column, "Was ist klein, glitschig und immer schlecht gelaunt?Eine Maulquappe."));
        table.insert(new Row(table, db).with(column, "Was ist langsam, wird steinalt und macht einen Riesenlärm ? Eine Schildtröte. "));
        table.insert(new Row(table, db).with(column, "Was ist lila und bedient im Restaurant ? Eine Obergine. "));
        table.insert(new Row(table, db).with(column, "Was ist lässig und hat einen Euter ? Eine Kuhl. "));
        table.insert(new Row(table, db).with(column, "Was ist orange und kann nicht still sitzen ?Eine Zappelsine."));
        table.insert(new Row(table, db).with(column, "Was ist orange und läuft durch die Berge ?Eine Wandarine."));
        table.insert(new Row(table, db).with(column, "Was ist rot und schlecht für die Zähne ?Ein Ziegelstein."));
        table.insert(new Row(table, db).with(column, "Was ist rot und steht im Wald ? Ein Kirsch. "));
        table.insert(new Row(table, db).with(column, "Was ist rot und wiehert ? Eine Pferdbeere. "));
        table.insert(new Row(table, db).with(column, "Was ist rot, rund und sitzt auf dem Klo ? Eine Klomate. "));
        table.insert(new Row(table, db).with(column, "Was ist schwarz, rot und lebt in der Arktis ? Ein Pinguin mit Sonnenbrand. "));
        table.insert(new Row(table, db).with(column, "Was ist schwarz - weiß und 50 cm in der Luft?Ein Schwebra."));
        table.insert(new Row(table, db).with(column, "Was ist schwarz - weiß und explodiert?Ein Sprenguin."));
        table.insert(new Row(table, db).with(column, "Was ist schwarz - weiß und hüpft auf und ab ? Ein Springuin. "));
        table.insert(new Row(table, db).with(column, "Was ist schwarz - weiß und sitzt auf der Schaukel ? Ein Schwinguin. "));
        table.insert(new Row(table, db).with(column, "Was ist süß und schwingt sich von Torte zu Torte ?Tarzipan. "));
        table.insert(new Row(table, db).with(column, "Was ist süß, klebrig und geht durch die Wüste ? Ein Karamel. "));
        table.insert(new Row(table, db).with(column, "Was ist unter der Erde und stinkt ? Eine Furzel. "));
        table.insert(new Row(table, db).with(column, "Was ist schwarz - weiß und 50 cm in der Luft?Ein Schwebra."));
        table.insert(new Row(table, db).with(column, "Was ist weiß und fliegt durch den Wald?Biene Mayo."));
        table.insert(new Row(table, db).with(column, "Was ist weiß und guckt durchs Schlüsselloch ? —Ein Spannbettlaken."));
        table.insert(new Row(table, db).with(column, "Was ist weiß und rennt den Berg wieder hoch ? Eine Lawine mit Heimweh. "));
        table.insert(new Row(table, db).with(column, "Was ist weiß und schnarcht auf der Wiese ?Ein Schlaf."));
        table.insert(new Row(table, db).with(column, "Was ist weiß und springt von Baum zu Baum ? Ein Tierarzt bei der Zeckenimpfung."));
        table.insert(new Row(table, db).with(column, "Was ist weiß und stört beim Essen ? Eine Lawine. "));
        table.insert(new Row(table, db).with(column, "Was ist weiß und tanz im Wald ums Feuer ? Rumpelpilzchen. "));
        table.insert(new Row(table, db).with(column, "Was ist wohlhabend und springt von Ast zu Ast ? Ein Scheichhörnchen. "));
        table.insert(new Row(table, db).with(column, "Was kauft ein Mann mit zwei linken Füßen im Schuhgeschäft?Flip Flips."));
        table.insert(new Row(table, db).with(column, "Was kommt aufs Brot und schmeckt nach Kleister?Kleberwurst. "));
        table.insert(new Row(table, db).with(column, "Was lebt in der Savanne und ist immer sauber ? Eine Hygiäne. "));
        table.insert(new Row(table, db).with(column, "Was liegt am Strand und kann man nicht gut verstehen und ist auch noch erkältet ? Eine Niesnuschel. "));
        table.insert(new Row(table, db).with(column, "Was liegt am Strand und kann man nicht gut verstehen ?Eine Nuschel."));
        table.insert(new Row(table, db).with(column, "Was machen PiratInnen, wenn Sie nicht mehr weiterwissen?Einen Arrrrrrrbeitskreis."));
        table.insert(new Row(table, db).with(column, "Was machen Tiere in der Disko?Sie diskotieren."));
        table.insert(new Row(table, db).with(column, "Was machen zwei Bäume, wenn sie einen trinken wollen?Sie gehen in ihre Stammkneipe. "));
        table.insert(new Row(table, db).with(column, "Was machen zwei wütende Schafe ? Sie bekommen sich in die Wolle. "));
        table.insert(new Row(table, db).with(column, "Was macht der Mathematiker beim Skifahren?Er rechnet mit Brüchen."));
        table.insert(new Row(table, db).with(column, "Was macht der Ostfriese wenn er zu Hause mehr elektrische Anschlussleistung braucht?Er geht mit dem Eimer raus und holt sich ein paar Kilo Watt. "));
        table.insert(new Row(table, db).with(column, "Was macht ein arbeitsloser Schauspieler ? Spielt keine Rolle."));
        table.insert(new Row(table, db).with(column, "Was macht ein Clown im Büro ?Faxen. "));
        table.insert(new Row(table, db).with(column, "Was macht ein schwuler Wurm im Salat ? -Er schmeißt die Schnecken raus."));
        table.insert(new Row(table, db).with(column, "Was macht eine Bombe im Bordell? —Puff. "));
        table.insert(new Row(table, db).with(column, "Was macht eine Bombe im Treppenhaus ?Hochgehen. "));
        table.insert(new Row(table, db).with(column, "Was macht eine Ente auf dem Router ? Nat. "));
        table.insert(new Row(table, db).with(column, "Was macht man mit einem Hund ohne Beine ?Um die Häuser ziehen."));
        table.insert(new Row(table, db).with(column, "Was passiert wenn man Cola und Bier gleichzeitig trinkt ? —Man colabiert."));
        table.insert(new Row(table, db).with(column, "Was piekst und fliest das Bad?Ein Kachelschwein."));
        table.insert(new Row(table, db).with(column, "Was sagt der frustrierte Origami - Lehrer zu seinem Schüler ? Kannste knicken !"));
        table.insert(new Row(table, db).with(column, "Was sagt der Fuchs im Hühnerstall ?Raus aus den Federn !"));
        table.insert(new Row(table, db).with(column, "Was sagt der große Stift zum kleinen Stift ?Wachs - mal - Stift. "));
        table.insert(new Row(table, db).with(column, "Was sagt der Holzwurmpapa abends zu seinen Kindern ?Husch, husch ab ins Brettchen. "));
        table.insert(new Row(table, db).with(column, "Was sagt der Teig bei der Hochzeit ? Ich bin ganz gerührt !"));
        table.insert(new Row(table, db).with(column, "Was sagt ein Ackerbesteller bei gutem Wetter ? Das Land - wird. "));
        table.insert(new Row(table, db).with(column, "Was sagt ein Gen, wenn es ein anderes trifft?-Halogen. "));
        table.insert(new Row(table, db).with(column, "Was sagt ein Pirat im Pferdestall ?A, Heu. "));
        table.insert(new Row(table, db).with(column, "Was schwimmt auf dem Teich und fängt mit Z an ?Zwei Enten."));
        table.insert(new Row(table, db).with(column, "Was schwimmt im Meer und addiert ?Ein Oktoplus."));
        table.insert(new Row(table, db).with(column, "Was sind die teuersten Tomaten ? Die Geldautomaten. "));
        table.insert(new Row(table, db).with(column, "Was sitzt am Frühstückstisch und winkt?Ein Grüsli."));
        table.insert(new Row(table, db).with(column, "Was sitzt auf dem Baum und schreit Aha! - Ein Uhu mit Sprachfehler. "));
        table.insert(new Row(table, db).with(column, "Was sitzt auf dem Turm und macht alle 15 Minuten Schuhu?Der Turmuhur."));
        table.insert(new Row(table, db).with(column, "Was sitzt auf einem Baum und winkt ? —Ein Huhu !"));
        table.insert(new Row(table, db).with(column, "Was sitzt ganz hinten im Brotkasten und ist beleidigt ? Ein Schmollkornbrot. "));
        table.insert(new Row(table, db).with(column, "Was sitzt im Baum und weint?Eine Heule !"));
        table.insert(new Row(table, db).with(column, "Was steht auf dem Herd und ist total geheim ? Ein Topf Secret !"));
        table.insert(new Row(table, db).with(column, "Was steht Weihnachten im Wohnzimmer und ist kaputt ?Ein Pannenbaum."));
        table.insert(new Row(table, db).with(column, "Was studiert man für einen Führerschein ?Fahr - ma - kologie. "));
        table.insert(new Row(table, db).with(column, "Was wird oft übersehen ?Ein Gartenzaun."));
        table.insert(new Row(table, db).with(column, "Welche Fische haben die beste Mundhygiene ?Die Zahnprophylachse."));
        table.insert(new Row(table, db).with(column, "Welche Handwerker essen am meisten ? Maurer, die verputzen ganze Häuser. "));
        table.insert(new Row(table, db).with(column, "Welche Schuhe tragen Raubfische sehr gern ?Hai - Heels. "));
        table.insert(new Row(table, db).with(column, "Welche Weinsorte wächst am Fuße des Vesuvs ? Glühwein. "));
        table.insert(new Row(table, db).with(column, "Welcher Fisch nervt im Unterricht ? Na der Stör !"));
        table.insert(new Row(table, db).with(column, "Welches Gemüse serviert sich selbst ? Die Obergine. "));
        table.insert(new Row(table, db).with(column, "Welches Getränk trinken Firmenchefs?Leitungswasser. "));
        table.insert(new Row(table, db).with(column, "Welches ist die lustigste Automarke ? Scherzedes. "));
        table.insert(new Row(table, db).with(column, "Welches Maultier sitzt in der Bar und trink Cappuccino ? Das Cafémel. "));
        table.insert(new Row(table, db).with(column, "Welches Obst geht immer in die Kirche ? Die Frommbeere. "));
        table.insert(new Row(table, db).with(column, "Welches Tier badet gern in Tomaten, Basilikum und Olivenöl?Der Mozzarellensittich."));
        table.insert(new Row(table, db).with(column, "Welches Tier hält immer Maß ? Der Ellensittich. "));
        table.insert(new Row(table, db).with(column, "Welches Tier klebt gerne zwischen den Zähnen ? Der Karamellensittich. "));
        table.insert(new Row(table, db).with(column, "Welches Tier kümmert sich um Meeresbewohner, denen es nicht gut geht?Die Krakenschwester."));
        table.insert(new Row(table, db).with(column, "Welches Tier trägt Strapse und Korsett und ist auch sonst eher verrucht?Der Bordellensittich."));
        table.insert(new Row(table, db).with(column, "Wenn ein südamerikanisches Kameltier betrunken ist ...ist das dann ein Alkpaka ? "));
        table.insert(new Row(table, db).with(column, "Wenn eine Kapselkaffeemaschine das Zeitliche segnet, schlägt die Stunde des Senseomanns."));
        table.insert(new Row(table, db).with(column, "Wenn Nicolas Wöhrl sich ein Brötchen schmiert ...ist es dann wissenschaftlich belegt ? "));
        table.insert(new Row(table, db).with(column, "Wer ist bunt, flattert durch die Luft und hilft wo er nur kann ? Ein Retterling. "));
        table.insert(new Row(table, db).with(column, "Wer ist grün, kann zaubern und riecht streng?Stinkerbell. "));
        table.insert(new Row(table, db).with(column, "Wer kümmert sich um die Gräten der Meeresbewohner ?Der Oktopäde."));
        table.insert(new Row(table, db).with(column, "Wer mit Nüssen zahlt, darf sich nicht wundern, wenn Affen für ihn arbeiten."));
        table.insert(new Row(table, db).with(column, "Wer wohnt im Dschungel und schummelt?Mogli. "));
        table.insert(new Row(table, db).with(column, "Wie begrüßen sich Schönheitschirurgen ?Na was machst Du denn für ein Gesicht ?"));
        table.insert(new Row(table, db).with(column, "Wie berechnet eine Kuh die Fläche ihrer Weide ?--Mit der Muhtiplikation."));
        table.insert(new Row(table, db).with(column, "Wie heißt das intelligenteste Gemüse ? -Schlaubergine. "));
        table.insert(new Row(table, db).with(column, "Wie heißt der Tiger mit Vornamen ?-Schaumfes !"));
        table.insert(new Row(table, db).with(column, "Wie heißt ein Spanier ohne Auto ?Carlos. "));
        table.insert(new Row(table, db).with(column, "Wie kastriert man einen Kühlschrank ? Tür auf, Eier raus, Tür zu. "));
        table.insert(new Row(table, db).with(column, "Wie nennt man das Küchengerät dass dir heimlich die Süßigkeiten wegisst ? Die Spülnaschine. "));
        table.insert(new Row(table, db).with(column, "Wie nennt man das Oberteil von Meerjungfrauen ? Algebra. "));
        table.insert(new Row(table, db).with(column, "Wie nennt man den Flur eines Iglus ? Eisdiele !"));
        table.insert(new Row(table, db).with(column, "Wie nennt man den germanischen Gott der Ungeduld ?Hammersbald. "));
        table.insert(new Row(table, db).with(column, "Wie nennt man die Steigerung von Buchstabensuppe ? Wörtersee. "));
        table.insert(new Row(table, db).with(column, "Wie nennt man ein kleines schwäbisches Schwein, das um Hilfe ruft ? Ein Notrufsäule. "));
        table.insert(new Row(table, db).with(column, "Wie nennt man ein Monster mit Schnupfen ? Rotzilla. "));
        table.insert(new Row(table, db).with(column, "Wie nennt man ein Rudel aggressiver Wölfe ? Wolfgang. "));
        table.insert(new Row(table, db).with(column, "Wie nennt man ein verschwundenes Rindvieh ?-Oxford. "));
        table.insert(new Row(table, db).with(column, "Wie nennt man ein weißes Mammut ?Hell - mut !"));
        table.insert(new Row(table, db).with(column, "Wie nennt man ein tiefgefrorenes Mammut ?Hart - mut !"));
        table.insert(new Row(table, db).with(column, "Wie nennt man eine Biene, die diagonal fliegt?Eine Quersumme."));
        table.insert(new Row(table, db).with(column, "Wie nennt man eine Frucht, die ein großes Anwesen hat?--Eine Hektarine. "));
        table.insert(new Row(table, db).with(column, "Wie nennt man einen ausgehungerten Frosch ?Magerquark. "));
        table.insert(new Row(table, db).with(column, "Wie nennt man einen Bär der KungFu beherrscht ?Grizzly. "));
        table.insert(new Row(table, db).with(column, "Wie nennt man einen Ausserirdischen, der in der Informationstechnik arbeitet?Italien. "));
        table.insert(new Row(table, db).with(column, "Wie nennt man einen Bären der Granufink braucht ? Ein Pullerbär. "));
        table.insert(new Row(table, db).with(column, "Wie nennt man einen Delfin mit einer Unterhose auf dem Kopf ? Slipper. "));
        table.insert(new Row(table, db).with(column, "Wie nennt man einen dicken Schriftsteller ?-Kugelschreiber !"));
        table.insert(new Row(table, db).with(column, "Wie nennt man einen dünnen Weihnachtsmann ?Nikolauch. "));
        table.insert(new Row(table, db).with(column, "Wie nennt man einen extrem dünnen Frosch ? Magerquak. "));
        table.insert(new Row(table, db).with(column, "Wie nennt man einen Gerd, der den Rasen mäht ? Gerd - ner. "));
        table.insert(new Row(table, db).with(column, "Wie nennt man einen Hering, der am Flughafen arbeitet ? Einen Zollmops. "));
        table.insert(new Row(table, db).with(column, "Wie nennt man einen Hering, der beleidigt ist?Einen Schmollmops."));
        table.insert(new Row(table, db).with(column, "Wie nennt man einen Hering, der die besten Memes postet?Einen Lolmops."));
        table.insert(new Row(table, db).with(column, "Wie nennt man einen Hering, der doofe Kommentare schreibt ? Einen Trollmops. "));
        table.insert(new Row(table, db).with(column, "Wie nennt man einen Hering, der gerne Atombombentests macht ? Einen Atollmops. "));
        table.insert(new Row(table, db).with(column, "Wie nennt man einen Hering, der gerne Befehle befolgt ? Einen Jawollmops. "));
        table.insert(new Row(table, db).with(column, "Wie nennt man einen Hering, der gerne Fußball mag ? Einen(Mehmet) Schollmops. "));
        table.insert(new Row(table, db).with(column, "Wie nennt man einen Hering, der gerne strickt?Einen Wollmops."));
        table.insert(new Row(table, db).with(column, "Wie nennt man einen Hering, der immer alles aufschreibt ? Einen Protokollmops. "));
        table.insert(new Row(table, db).with(column, "Wie nennt man einen Hering, der immer alles machen muss?Einen Sollmops."));
        table.insert(new Row(table, db).with(column, "Wie nennt man einen Hering, der immer nur traurige Musik spielt ? Einen Mollmops. "));
        table.insert(new Row(table, db).with(column, "Wie nennt man einen Hering, der immer sauer ist ? Einen Grollmops. "));
        table.insert(new Row(table, db).with(column, "Wie nennt man einen Hering, der immer total begeistert ist?Einen Tollmops."));
        table.insert(new Row(table, db).with(column, "Wie nennt man einen Hering, der Regie führt?Einen(Uwe) Bollmops. "));
        table.insert(new Row(table, db).with(column, "Wie nennt man einen Hering, der sehr unkultiviert ist ? Einen Prollmops. "));
        table.insert(new Row(table, db).with(column, "Wie nennt man einen Hering, der sich für Umfragen interessiert?Einen Pollmops."));
        table.insert(new Row(table, db).with(column, "Wie nennt man einen Hering, der total besoffen ist ? Einen Vollmops. "));
        table.insert(new Row(table, db).with(column, "Wie nennt man einen Hering, der total gerne Puppen mag?Einen Dollmops."));
        table.insert(new Row(table, db).with(column, "Wie nennt man einen Hund der gerne Äpfel isst ? Apfelpudel. "));
        table.insert(new Row(table, db).with(column, "Wie nennt man einen hungrigen risikobereiten Wellensittich ? Trill - Seeker "));
        table.insert(new Row(table, db).with(column, "Wie nennt man einen kleinen Matrosen, der sich nicht wäscht ? Na : Ein Meerschweinchen !"));
        table.insert(new Row(table, db).with(column, "Wie nennt man einen kleinen Türsteher ?Sicherheitshalber. "));
        table.insert(new Row(table, db).with(column, "Wie nennt man einen Landwirt mit Studium ? Einen Ackerdemiker. "));
        table.insert(new Row(table, db).with(column, "Wie nennt man einen überfahrenen Vogel?Piepmatsch !"));
        table.insert(new Row(table, db).with(column, "Wie nennt man Fernsehverbot auf Russisch ?Njetflix. "));
        table.insert(new Row(table, db).with(column, "Wie nennt man Han Solo, wenn er in der Disko rumtanzt ? Han Twerker. "));
        table.insert(new Row(table, db).with(column, "Wie nennt man heute einen Hofnarr ?Untertainer. "));
        table.insert(new Row(table, db).with(column, "Wie nennt man jemand der nur so tut als würde er etwas werfen ? Einen Scheinwerfer. "));
        table.insert(new Row(table, db).with(column, "Wie nennt man jemanden der DIN A4 Blätter scannt ? Skan - din - a - vier. "));
        table.insert(new Row(table, db).with(column, "Wie nennt man Kaninchen im Fitnessstudio ?Pumpernickel. "));
        table.insert(new Row(table, db).with(column, "Wie viel wiegen ein Pferd und ein Hund zusammen ? Ein PfHund !"));
        table.insert(new Row(table, db).with(column, "Wie viele Psychotherapeuten braucht man um eine Glühbirne zu wechseln ?Einen, aber die Birne muss auch wollen. "));
        table.insert(new Row(table, db).with(column, "Wie viele Softwareentwickler braucht man um eine Glühbirne zu wechseln ?Keinen, das ist eindeutig ein Hardwareproblem."));
        table.insert(new Row(table, db).with(column, "Wie war die Stimmung in der DDR ? Sie hielt sich in Grenzen."));
        table.insert(new Row(table, db).with(column, "Wieso können Seeräuber keinen Kreis fahren?-Weil sie Pi raten. "));
        table.insert(new Row(table, db).with(column, "Will jemand einen Witz über Natriumhydrat hören - NaH !"));
        table.insert(new Row(table, db).with(column, "Wo baden Eisbären am liebsten ? Im Nordpool. "));
        table.insert(new Row(table, db).with(column, "Wo geht Darth Vader shoppen ? In der Darth Mall !"));
        table.insert(new Row(table, db).with(column, "Wo gibt es die meisten Gespenster in Europa ?In Buuuuuuuuhdapest !"));
        table.insert(new Row(table, db).with(column, "Wo ist die Deutschlandzentrale von Burger King ? In Whoppertal. "));
        table.insert(new Row(table, db).with(column, "Wo machen Kühe Urlaub?Auf Kuuuhba !"));
        table.insert(new Row(table, db).with(column, "Wo wohnen Katzen ? Im Mietz - Haus !"));
        table.insert(new Row(table, db).with(column, "Wo baden Eisbären am liebsten ? Im Nordpool. "));
        table.insert(new Row(table, db).with(column, "Wohin geht ein Baum, wenn er Rückenschmerzen hat ? Zum Kiefer - Orthopäden. "));
        table.insert(new Row(table, db).with(column, "Wohin geht ein Zyklop, wenn er nicht gut sieht?Zum Augearzt."));
        table.insert(new Row(table, db).with(column, "Wollte Socken bei H&M kaufen.Oma strickt dagegen. "));
        table.insert(new Row(table, db).with(column, "Womit backen Schlümpfe ? Mit Garga - Mehl. "));
        table.insert(new Row(table, db).with(column, "Womit ist der Boden eines Iglus ausgelegt ? Mit Eisdielen. "));
        table.insert(new Row(table, db).with(column, "Womit kann man eine Webseite hosten, aber nur wenn Vollmond ist?Mit einem Werserver. "));
        table.insert(new Row(table, db).with(column, "Womit verprügeln sich Schafe ?Mit dem Mäh - Drescher. "));
        table.insert(new Row(table, db).with(column, "Womit verzieren Rinder ihren Kuchen ? Mit Kuhvertüre. "));
        table.insert(new Row(table, db).with(column, "Wovon träumt eine Katze nachts ? Von einem Muskelkater."));
        table.insert(new Row(table, db).with(column, "Wussten Sie, dass Esoteriker häufig zur Arbeit pendeln...?"));
        table.insert(new Row(table, db).with(column, "Zu welchem Arzt geht Pinocchio ? Zum Holz - Nasen - Ohren - Arzt. "));
        table.insert(new Row(table, db).with(column, "„Du hast aber schon mal einen Schornstein gemauert, oder?“ „Nein, das ist ein Versuchskaminchen."));
    }

    public static void fillMovieTable(Database db, @NotNull Table table) {
        String column = "name";
        table.insert(new Row(table, db).with(column, "DRACHENZÄHMEN LEICHT GEMACHT 1"));
        table.insert(new Row(table, db).with(column, "DRACHENZÄHMEN LEICHT GEMACHT 2"));
        table.insert(new Row(table, db).with(column, "DRACHENZÄHMEN LEICHT GEMACHT 3"));
        table.insert(new Row(table, db).with(column, "AQUAMAN"));
        table.insert(new Row(table, db).with(column, "Harry Potter und der Stein der Weisen"));
        table.insert(new Row(table, db).with(column, "Harry Potter und der Orden des Phönix"));
        table.insert(new Row(table, db).with(column, "Harry Potter und der Gefangene von Askaban"));
        table.insert(new Row(table, db).with(column, "Harry Potter und die Heiligtümer des Todes Teil 1"));
        table.insert(new Row(table, db).with(column, "Harry Potter und die Heiligtümer des Todes Teil 2"));
        table.insert(new Row(table, db).with(column, "Harry Potter und die Kammer des Schreckens "));
        table.insert(new Row(table, db).with(column, "Harry Potter und der Halbblutprinz"));
        table.insert(new Row(table, db).with(column, "DEADPOOL"));
        table.insert(new Row(table, db).with(column, "DEADPOOL 2"));
        table.insert(new Row(table, db).with(column, "BLACK PANTHER"));
        table.insert(new Row(table, db).with(column, "EXTREME RAGE"));
        table.insert(new Row(table, db).with(column, "XXX 3: DIE RÜCKKEHR DES XANDER CAGE"));
        table.insert(new Row(table, db).with(column, "XXX - TRIPLE X"));
        table.insert(new Row(table, db).with(column, "XXX² - THE NEXT LEVEL"));
        table.insert(new Row(table, db).with(column, "SKYSCRAPER"));
        table.insert(new Row(table, db).with(column, "96 HOURS"));
        table.insert(new Row(table, db).with(column, "96 HOURS - TAKEN 2"));
        table.insert(new Row(table, db).with(column, "96 HOURS - TAKEN 3"));
        table.insert(new Row(table, db).with(column, "AFTER EARTH"));
        table.insert(new Row(table, db).with(column, "ALADDIN"));
        table.insert(new Row(table, db).with(column, "ARTHUR UND DIE MINIMOYS 1"));
        table.insert(new Row(table, db).with(column, "ARTHUR UND DIE MINIMOYS 2"));
        table.insert(new Row(table, db).with(column, "ARTHUR UND DIE MINIMOYS 3"));
        table.insert(new Row(table, db).with(column, "ALITA: BATTLE ANGEL"));
        table.insert(new Row(table, db).with(column, "ALVIN UND DIE CHIPMUNKS"));
        table.insert(new Row(table, db).with(column, "ANGEL HAS FALLEN"));
        table.insert(new Row(table, db).with(column, "BRIGHT"));
        table.insert(new Row(table, db).with(column, "BUMBLEBEE"));
        table.insert(new Row(table, db).with(column, "BOB, DER STREUNER"));
        table.insert(new Row(table, db).with(column, "BLOODSHOT"));
        table.insert(new Row(table, db).with(column, "BLINKY BILL - DAS MEER DER WEISSEN DRACHEN"));
        table.insert(new Row(table, db).with(column, "ANT-MAN"));
        table.insert(new Row(table, db).with(column, "ANT-MAN AND THE WASP"));
        table.insert(new Row(table, db).with(column, "RAYA UND DER LETZTE DRACHE"));
        table.insert(new Row(table, db).with(column, "ARLO & SPOT"));
        table.insert(new Row(table, db).with(column, "BAD BOYS"));
        table.insert(new Row(table, db).with(column, "BAD BOYS FOR LIFE"));
        table.insert(new Row(table, db).with(column, "BAYMAX - RIESIGES ROBOWABOHU"));
        table.insert(new Row(table, db).with(column, "BAYWATCH"));
        table.insert(new Row(table, db).with(column, "BEE MOVIE - DAS HONIGKOMPLOTT"));
        table.insert(new Row(table, db).with(column, "BARBIE IN SCHWANENSEE "));
        table.insert(new Row(table, db).with(column, "BARBIE IN: DIE SUPER-PRINZESSIN"));
        table.insert(new Row(table, db).with(column, "BARBIE IN DER NUSSKNACKER"));
        table.insert(new Row(table, db).with(column, "BARBIE ALS RAPUNZEL"));
        table.insert(new Row(table, db).with(column, "ASTERIX BEI DEN OLYMPISCHEN SPIELEN"));
        table.insert(new Row(table, db).with(column, "AVATAR AUFBRUCH NACH PANDORA"));
        table.insert(new Row(table, db).with(column, "AVENGERS ENDGAME"));
        table.insert(new Row(table, db).with(column, "AVENGERS 3: INFINITY WAR"));
        table.insert(new Row(table, db).with(column, "ARTEMIS FOWL"));
        table.insert(new Row(table, db).with(column, "ATLANTIS - DIE RÜCKKEHR"));
        table.insert(new Row(table, db).with(column, "AB DURCH DIE HECKE"));
        table.insert(new Row(table, db).with(column, "Frozen"));
        table.insert(new Row(table, db).with(column, "DIE EISKÖNIGIN 2"));
        table.insert(new Row(table, db).with(column, "Vaiana"));
        table.insert(new Row(table, db).with(column, "Rapunzel"));
        table.insert(new Row(table, db).with(column, "Karate kid"));
        table.insert(new Row(table, db).with(column, "PHANTASTISCHE TIERWESEN UND WO SIE ZU FINDEN SIND"));
        table.insert(new Row(table, db).with(column, "PHANTASTISCHE TIERWESEN - GRINDELWALDS VERBRECHEN"));
        table.insert(new Row(table, db).with(column, "ZOOMANIA"));
        table.insert(new Row(table, db).with(column, "Merlin"));
        table.insert(new Row(table, db).with(column, "Shrek"));
        table.insert(new Row(table, db).with(column, "Tarzan"));
        table.insert(new Row(table, db).with(column, "Die fantastische Welt von Oz"));
        table.insert(new Row(table, db).with(column, "Monster High"));
        table.insert(new Row(table, db).with(column, "CAPTAIN AMERICA: THE FIRST AVENGER"));
        table.insert(new Row(table, db).with(column, "CAPTAIN AMERICA 2: THE RETURN OF THE FIRST AVENGER"));
        table.insert(new Row(table, db).with(column, "CAPTAIN MARVEL"));
        table.insert(new Row(table, db).with(column, "CARS"));
        table.insert(new Row(table, db).with(column, "CARS 2"));
        table.insert(new Row(table, db).with(column, "CARS 3: EVOLUTION"));
        table.insert(new Row(table, db).with(column, "CHAPPIE"));
        table.insert(new Row(table, db).with(column, "CHARLIE UND DIE SCHOKOLADENFABRIK "));
        table.insert(new Row(table, db).with(column, "CROCODILE DUNDEE"));
        table.insert(new Row(table, db).with(column, "CROCODILE DUNDEE II"));
        table.insert(new Row(table, db).with(column, "CROCODILE DUNDEE IN LOS ANGELES"));
        table.insert(new Row(table, db).with(column, "DADDY OHNE PLAN"));
        table.insert(new Row(table, db).with(column, "DAS HAUS DER GEHEIMNISVOLLEN UHREN"));
        table.insert(new Row(table, db).with(column, "DAS VERMÄCHTNIS DER TEMPELRITTER"));
        table.insert(new Row(table, db).with(column, "DAS VERMÄCHTNIS DES GEHEIMEN BUCHES"));
        table.insert(new Row(table, db).with(column, "DAS VERSCHOLLENE MEDAILLON"));
        table.insert(new Row(table, db).with(column, "DER HERR DER RINGE - DIE GEFÄHRTEN"));
        table.insert(new Row(table, db).with(column, "DER HERR DER RINGE - DIE RÜCKKEHR DES KÖNIGS"));
        table.insert(new Row(table, db).with(column, "DER HERR DER RINGE - DIE ZWEI TÜRME"));
        table.insert(new Row(table, db).with(column, "DER HOBBIT - DIE SCHLACHT DER FÜNF HEERE"));
        table.insert(new Row(table, db).with(column, "DER HOBBIT EINE UNERWARTETE REISE"));
        table.insert(new Row(table, db).with(column, "DER HOBBIT: SMAUGS EINÖDE"));
        table.insert(new Row(table, db).with(column, "DER KAUFHAUS COP"));
        table.insert(new Row(table, db).with(column, "DER KAUFHAUS COP 2"));
        table.insert(new Row(table, db).with(column, "DER KNASTCOACH"));
        table.insert(new Row(table, db).with(column, "DER KÖNIG DER LÖWEN"));
        table.insert(new Row(table, db).with(column, "DER PLANET DER AFFEN: PREVOLUTION"));
        table.insert(new Row(table, db).with(column, "DER POLAREXPRESS"));
        table.insert(new Row(table, db).with(column, "DER PRINZ AUS ZAMUNDA"));
        table.insert(new Row(table, db).with(column, "DER SPION VON NEBENAN"));
        table.insert(new Row(table, db).with(column, "DESCENDANTS - DIE NACHKOMMEN"));
        table.insert(new Row(table, db).with(column, "DESCENDANTS 2"));
        table.insert(new Row(table, db).with(column, "DESCENDANTS 3 - DIE NACHKOMMEN"));
        table.insert(new Row(table, db).with(column, "DESCENDANTS 3 - DIE NACHKOMMEN"));
        table.insert(new Row(table, db).with(column, "DIE BESTIMMUNG - ALLEGIANT PART 1"));
        table.insert(new Row(table, db).with(column, "DIE BESTIMMUNG - DIVERGENT"));
        table.insert(new Row(table, db).with(column, "DIE BIENE MAJA - DER FILM"));
        table.insert(new Row(table, db).with(column, "DIE CHRONIKEN VON NARNIA - PRINZ KASPIAN VON NARNIA"));
        table.insert(new Row(table, db).with(column, "DIE CHRONIKEN VON NARNIA: DER KÖNIG VON NARNIA"));
        table.insert(new Row(table, db).with(column, "DIE CHRONIKEN VON NARNIA: DIE REISE AUF DER MORGENRÖTE"));
        table.insert(new Row(table, db).with(column, "DIE CROODS"));
        table.insert(new Row(table, db).with(column, "DIE FANTASTISCHE REISE DES DR. DOLITTLE"));
        table.insert(new Row(table, db).with(column, "DIE HÜTER DES LICHTS"));
        table.insert(new Row(table, db).with(column, "DIE PEANUTS - DER FILM"));
        table.insert(new Row(table, db).with(column, "DIE PINGUINE AUS MADAGASCAR"));
        table.insert(new Row(table, db).with(column, "DIE SCHLÜMPFE"));
        table.insert(new Row(table, db).with(column, "DIE SCHLÜMPFE 2"));
        table.insert(new Row(table, db).with(column, "DIE SCHLÜMPFE 3 - DAS VERLORENE DORF"));
        table.insert(new Row(table, db).with(column, "DIE SCHÖNE UND DAS BIEST"));
        table.insert(new Row(table, db).with(column, "DIE TRIBUTE VON PANEM - CATCHING FIRE"));
        table.insert(new Row(table, db).with(column, "DIE TRIBUTE VON PANEM - THE HUNGER GAMES"));
        table.insert(new Row(table, db).with(column, "DIE TRIBUTE VON PANEM - MOCKINGJAY: TEIL 1"));
        table.insert(new Row(table, db).with(column, "DIE TRIBUTE VON PANEM - MOCKINGJAY: TEIL 2"));
        table.insert(new Row(table, db).with(column, "DIE UNFASSBAREN - NOW YOU SEE ME"));
        table.insert(new Row(table, db).with(column, "DIE UNFASSBAREN 2"));
        table.insert(new Row(table, db).with(column, "DIE UNGLAUBLICHEN 2"));
        table.insert(new Row(table, db).with(column, "DOCTOR STRANGE"));
        table.insert(new Row(table, db).with(column, "DORA UND DIE GOLDENE STADT"));
        table.insert(new Row(table, db).with(column, "DRAGONBALL EVOLUTION"));
        table.insert(new Row(table, db).with(column, "DUMBO"));
        table.insert(new Row(table, db).with(column, "THE DEATH OF SUPERMAN"));
        table.insert(new Row(table, db).with(column, "MISSION: IMPOSSIBLE - FALLOUT"));
        table.insert(new Row(table, db).with(column, "MISSION: IMPOSSIBLE - ROGUE NATION"));
        table.insert(new Row(table, db).with(column, "MISSION: IMPOSSIBLE - 2"));
        table.insert(new Row(table, db).with(column, "MISSION: IMPOSSIBLE - 3"));
        table.insert(new Row(table, db).with(column, "MISSION: IMPOSSIBLE - PHANTOM PROTOKOLL "));
        table.insert(new Row(table, db).with(column, "PACIFIC RIM 2: UPRISING"));
        table.insert(new Row(table, db).with(column, "PRINCE OF PERSIA - DER SAND DER ZEIT"));
        table.insert(new Row(table, db).with(column, "PREDATORS"));
        table.insert(new Row(table, db).with(column, "PRAKTI.COM"));
        table.insert(new Row(table, db).with(column, "POWER RANGERS"));
        table.insert(new Row(table, db).with(column, "POKEMON MEISTERDETEKTIV PIKACHU"));
        table.insert(new Row(table, db).with(column, "PIXELS"));
        table.insert(new Row(table, db).with(column, "PETS"));
        table.insert(new Row(table, db).with(column, "PETS 2"));
        table.insert(new Row(table, db).with(column, "PETER HASE"));
        table.insert(new Row(table, db).with(column, "PERCY JACKSON - DIEBE IM OLYMP"));
        table.insert(new Row(table, db).with(column, "PERCY JACKSON - IM BANN DES ZYKLOPEN"));
        table.insert(new Row(table, db).with(column, "PASSENGERS"));
        table.insert(new Row(table, db).with(column, "PARKER"));
        table.insert(new Row(table, db).with(column, "PAN"));
        table.insert(new Row(table, db).with(column, "PACIFIC RIM"));
        table.insert(new Row(table, db).with(column, "ONWARD: KEINE HALBEN SACHEN"));
        table.insert(new Row(table, db).with(column, "OBEN"));
        table.insert(new Row(table, db).with(column, "NACHTS IM MUSEUM"));
        table.insert(new Row(table, db).with(column, "NACHTS IM MUSEUM 2"));
        table.insert(new Row(table, db).with(column, "NACHTS IM MUSEUM - DAS GEHEIMNISVOLLE GRABMAL"));
        table.insert(new Row(table, db).with(column, "MORTAL ENGINES KRIEG DER STÄDTE"));
        table.insert(new Row(table, db).with(column, "MONSTERS VS. ALIENS"));
        table.insert(new Row(table, db).with(column, "MONSTER TRUCKS"));
        table.insert(new Row(table, db).with(column, "MOGLI: LEGENDE DES DSCHUNGELS"));
        table.insert(new Row(table, db).with(column, "MINIONS"));
        table.insert(new Row(table, db).with(column, "MERIDA - LEGENDE DER HIGHLANDS"));
        table.insert(new Row(table, db).with(column, "MENSCH, DAVE!"));
        table.insert(new Row(table, db).with(column, "MEN IN BLACK: INTERNATIONAL"));
        table.insert(new Row(table, db).with(column, "MEN IN BLACK"));
        table.insert(new Row(table, db).with(column, "MEN IN BLACK II"));
        table.insert(new Row(table, db).with(column, "MEN IN BLACK 3"));
        table.insert(new Row(table, db).with(column, "MAZE RUNNER 3: DIE AUSERWÄHLTEN IN DER TODESZONE"));
        table.insert(new Row(table, db).with(column, "MAZE RUNNER 2 - DIE AUSERWÄHLTEN IN DER BRANDWÜSTE"));
        table.insert(new Row(table, db).with(column, "MAZE RUNNER - DIE AUSERWÄHLTEN IM LABYRINTH"));
        table.insert(new Row(table, db).with(column, "MAX STEEL"));
        table.insert(new Row(table, db).with(column, "MATRIX"));
        table.insert(new Row(table, db).with(column, "MATRIX RELOADED"));
        table.insert(new Row(table, db).with(column, "MATRIX REVOLUTIONS"));
        table.insert(new Row(table, db).with(column, "MARVELS THE AVENGERS"));
        table.insert(new Row(table, db).with(column, "MARVELS THE AVENGERS 2: AGE OF ULTRON"));
        table.insert(new Row(table, db).with(column, "MAN OF STEEL"));
        table.insert(new Row(table, db).with(column, "MALEFICENT - DIE DUNKLE FEE"));
        table.insert(new Row(table, db).with(column, "MALEFICENT 2: MÄCHTE DER FINSTERNIS"));
        table.insert(new Row(table, db).with(column, "MADAGASCAR"));
        table.insert(new Row(table, db).with(column, "MADAGASCAR 2 "));
        table.insert(new Row(table, db).with(column, "MADAGASCAR 3 - FLUCHT DURCH EUROPA"));
        table.insert(new Row(table, db).with(column, "MAD MAX: FURY ROAD"));
        table.insert(new Row(table, db).with(column, "LUCY"));
        table.insert(new Row(table, db).with(column, "LUCAS, DER AMEISENSCHRECK"));
        table.insert(new Row(table, db).with(column, "LONDON HAS FALLEN"));
        table.insert(new Row(table, db).with(column, "LILO & STITCH"));
        table.insert(new Row(table, db).with(column, "LILO & STITCH 2 - STITCH VÖLLIG ABGEDREHT"));
        table.insert(new Row(table, db).with(column, "LETS BE COPS - DIE PARTY-BULLE"));
        table.insert(new Row(table, db).with(column, "LEGION"));
        table.insert(new Row(table, db).with(column, "LEGEND OF TARZAN"));
        table.insert(new Row(table, db).with(column, "LEAGUE OF GODS"));
        table.insert(new Row(table, db).with(column, "LARA CROFT: TOMB RAIDER"));
        table.insert(new Row(table, db).with(column, "KUNG FU YOGA - DER GOLDENE ARM DER GÖTTER"));
        table.insert(new Row(table, db).with(column, "KUNG FU PANDA - DIE GEHEIMNISSE DER MEISTER"));
        table.insert(new Row(table, db).with(column, "KUNG FU PANDA 2"));
        table.insert(new Row(table, db).with(column, "KUNG FU PANDA 3"));
        table.insert(new Row(table, db).with(column, "KUBO - DER TAPFERE SAMURAI"));
        table.insert(new Row(table, db).with(column, "KINGSMAN 1: THE SECRET SERVICE"));
        table.insert(new Row(table, db).with(column, "KINGSMAN 2: THE GOLDEN CIRCLE"));
        table.insert(new Row(table, db).with(column, "KINGSMAN 3:"));
        table.insert(new Row(table, db).with(column, "KINDSKÖPFE"));
        table.insert(new Row(table, db).with(column, "KINDSKÖPFE 2"));
        table.insert(new Row(table, db).with(column, "KINDERGARTEN COP 2"));
        table.insert(new Row(table, db).with(column, "KICK-ASS"));
        table.insert(new Row(table, db).with(column, "KICK-ASS 2"));
        table.insert(new Row(table, db).with(column, "KHUMBA - DAS ZEBRA OHNE STREIFEN AM POPO"));
        table.insert(new Row(table, db).with(column, "KEVIN - ALLEIN ZU HAUS"));
        table.insert(new Row(table, db).with(column, "KEVIN - ALLEIN IN NEW YORK"));
        table.insert(new Row(table, db).with(column, "KEINOHRHASE & ZWEIOHRKÜKEN"));
        table.insert(new Row(table, db).with(column, "JUSTICE LEAGUE"));
        table.insert(new Row(table, db).with(column, "JURASSIC WORLD"));
        table.insert(new Row(table, db).with(column, "JUPITER ASCENDING"));
        table.insert(new Row(table, db).with(column, "JUMANJI: WELCOME TO THE JUNGLE"));
        table.insert(new Row(table, db).with(column, "JUMANJI: THE NEXT LEVEL"));
        table.insert(new Row(table, db).with(column, "JOKER"));
        table.insert(new Row(table, db).with(column, "JOHNNY ENGLISH - MAN LEBT NUR DREIMAL"));
        table.insert(new Row(table, db).with(column, "JOHNNY ENGLISH "));
        table.insert(new Row(table, db).with(column, "JIU JITSU"));
        table.insert(new Row(table, db).with(column, "JIM KNOPF UND LUKAS DER LOKOMOTIVFÜHRER"));
        table.insert(new Row(table, db).with(column, "JAMES BOND 007 - SPECTRE"));
        table.insert(new Row(table, db).with(column, "JAMES BOND 007 - STIRB AN EINEM ANDEREN TAG"));
        table.insert(new Row(table, db).with(column, "JAMES BOND 007 - SKYFALL"));
        table.insert(new Row(table, db).with(column, "JAMES BOND 007 - CASINO ROYALE"));
        table.insert(new Row(table, db).with(column, "JAGDFIEBER 1"));
        table.insert(new Row(table, db).with(column, "JAGDFIEBER 2"));
        table.insert(new Row(table, db).with(column, "JAGDFIEBER 3"));
        table.insert(new Row(table, db).with(column, "JAGDFIEBER 4 - UNGEBETENE BESUCHER"));
        table.insert(new Row(table, db).with(column, "JAGD AUF DEN SCHATZ DER RIESEN"));
        table.insert(new Row(table, db).with(column, "JACK REACHER - DIE JAGD HAT BEGONNEN!"));
        table.insert(new Row(table, db).with(column, "JACK REACHER - 2: KEIN WEG ZURÜCK"));
        table.insert(new Row(table, db).with(column, "IRON MAN 1"));
        table.insert(new Row(table, db).with(column, "IRON MAN 2"));
        table.insert(new Row(table, db).with(column, "IRON MAN 3"));
        table.insert(new Row(table, db).with(column, "INSIDE OUT - ALLES STEHT KOPF"));
        table.insert(new Row(table, db).with(column, "INDIANA JONES UND DER TEMPEL DES TODES"));
        table.insert(new Row(table, db).with(column, "INDIANA JONES UND DER LETZTE KREUZZUG"));
        table.insert(new Row(table, db).with(column, "INDIANA JONES UND DAS KÖNIGREICH DES KRISTALLSCHÄDEL"));
        table.insert(new Row(table, db).with(column, "INDIANA JONES - JÄGER DES VERLORENEN SCHATZES"));
        table.insert(new Row(table, db).with(column, "INDEPENDENTS DAY 1"));
        table.insert(new Row(table, db).with(column, "INDEPENDENCE DAY 2: WIEDERKEHR "));
        table.insert(new Row(table, db).with(column, "IMMORTAL WARS - NUR DER STÄRKSTE ÜBERLEBT"));
        table.insert(new Row(table, db).with(column, "ICH BIN NUMMER 4"));
        table.insert(new Row(table, db).with(column, "ICH - EINFACH UNVERBESSERLICH 1"));
        table.insert(new Row(table, db).with(column, "ICH - EINFACH UNVERBESSERLICH 2"));
        table.insert(new Row(table, db).with(column, "ICH - EINFACH UNVERBESSERLICH 3"));
        table.insert(new Row(table, db).with(column, "ICE AGE 1"));
        table.insert(new Row(table, db).with(column, "ICE AGE 2"));
        table.insert(new Row(table, db).with(column, "ICE AGE 3"));
        table.insert(new Row(table, db).with(column, "ICE AGE 4 - VOLL VERSCHOBEN"));
        table.insert(new Row(table, db).with(column, "ICE AGE 5 - KOLLISION VORAUS!"));
        table.insert(new Row(table, db).with(column, "I, ROBOT"));
        table.insert(new Row(table, db).with(column, "HÜTER DER ERINNERUNG - THE GIVER "));
        table.insert(new Row(table, db).with(column, "HULK"));
        table.insert(new Row(table, db).with(column, "HUI BUH, DAS SCHLOSSGESPENST"));
        table.insert(new Row(table, db).with(column, "HOTEL TRANSSILVANIEN 1"));
        table.insert(new Row(table, db).with(column, "HOTEL TRANSSILVANIEN 2"));
        table.insert(new Row(table, db).with(column, "HOTEL TRANSSILVANIEN 3 - EIN MONSTER URLAUB (2018)"));
        table.insert(new Row(table, db).with(column, "HOTEL TRANSSILVANIEN 4"));
        table.insert(new Row(table, db).with(column, "HITMAN - AGENT 47"));
        table.insert(new Row(table, db).with(column, "HIGH SCHOOL MUSICAL 1:"));
        table.insert(new Row(table, db).with(column, "HIGH SCHOOL MUSICAL 2: SINGT ALLE ODER KEINER! (2007)"));
        table.insert(new Row(table, db).with(column, "HIGH SCHOOL MUSICAL 3: SENIOR YEAR (2008)"));
        table.insert(new Row(table, db).with(column, "HERCULES"));
        table.insert(new Row(table, db).with(column, "HAPPY FEET"));
        table.insert(new Row(table, db).with(column, "HANCOCK"));
        table.insert(new Row(table, db).with(column, "GUARDIANS OF THE GALAXY"));
        table.insert(new Row(table, db).with(column, "GUARDIANS OF THE GALAXY VOL. 2"));
        table.insert(new Row(table, db).with(column, "GREEN LANTERN"));
        table.insert(new Row(table, db).with(column, "GODZILLA 2 KING OF THE MONSTERS "));
        table.insert(new Row(table, db).with(column, "GODS OF EGYPT "));
        table.insert(new Row(table, db).with(column, "GOD OF WAR"));
        table.insert(new Row(table, db).with(column, "GNOMEO UND JULIA"));
        table.insert(new Row(table, db).with(column, "GHOST RIDER: SPIRIT OF VENGEANCE"));
        table.insert(new Row(table, db).with(column, "GEMINI MAN"));
        table.insert(new Row(table, db).with(column, "GARFIELD - FETT IM LEBEN"));
        table.insert(new Row(table, db).with(column, "GARFIELD - TIERISCHE HELDEN"));
        table.insert(new Row(table, db).with(column, "FÜNF FREUNDE UND DAS TAL DER DINOSAURIER (2018)"));
        table.insert(new Row(table, db).with(column, "FÜNF FREUNDE 3"));
        table.insert(new Row(table, db).with(column, "FÜNF FREUNDE 4"));
        table.insert(new Row(table, db).with(column, "FREUNDE MIT GEWISSEN VORZÜGEN "));
        table.insert(new Row(table, db).with(column, "FLUCH DER KARIBIK"));
        table.insert(new Row(table, db).with(column, "FLUCH DER KARIBIK 2"));
        table.insert(new Row(table, db).with(column, "FLUCH DER KARIBIK 3 - AM ENDE DER WELT (2007)"));
        table.insert(new Row(table, db).with(column, "FLUCH DER KARIBIK 4 - FREMDE GEZEITEN (2011)"));
        table.insert(new Row(table, db).with(column, "FLUCH DER KARIBIK SALAZARS RACHE"));
        table.insert(new Row(table, db).with(column, "FINDET DORIE"));
        table.insert(new Row(table, db).with(column, "FERDINAND - GEHT STIERISCH AB"));
        table.insert(new Row(table, db).with(column, "FASTER"));
        table.insert(new Row(table, db).with(column, "FAST & FURIOUS: NEUES MODELL. ORIGINALTEILE (2009)"));
        table.insert(new Row(table, db).with(column, "FAST & FURIOUS FIVE"));
        table.insert(new Row(table, db).with(column, "FAST & FURIOUS 6"));
        table.insert(new Row(table, db).with(column, "FAST AND FURIOUS 7"));
        table.insert(new Row(table, db).with(column, "FAST & FURIOUS 8"));
        table.insert(new Row(table, db).with(column, "FAST & FURIOUS PRESENTS: HOBBS & SHAW (2019)"));
        table.insert(new Row(table, db).with(column, "FANTASTIC FOUR"));
        table.insert(new Row(table, db).with(column, "FANTASTIC FOUR - RISE OF THE SILVER SURFER (2007)"));
        table.insert(new Row(table, db).with(column, "FACK JU GÖHTE"));
        table.insert(new Row(table, db).with(column, "FACK JU GÖHTE 2"));
        table.insert(new Row(table, db).with(column, "FACK JU GÖHTE 3"));
        table.insert(new Row(table, db).with(column, "Final Destination 5"));
        table.insert(new Row(table, db).with(column, "EXODUS - GÖTTER UND KÖNIGE"));
        table.insert(new Row(table, db).with(column, "ESPEN UND DIE LEGENDE VOM BERGKÖNIG (2017)"));
        table.insert(new Row(table, db).with(column, "EMOJI - DER FILM"));
        table.insert(new Row(table, db).with(column, "ELLIOT, DER DRACHE"));
        table.insert(new Row(table, db).with(column, "LEG DICH NICHT MIT ZOHAN AN"));
        table.insert(new Row(table, db).with(column, "17 Again"));
        table.insert(new Row(table, db).with(column, "The last witch Hunter"));
    }

    public static void fillGameTable(Database db, @NotNull Table table) {
        String column = "name";
        table.insert(new Row(table, db).with(column, "Valorant"));
        table.insert(new Row(table, db).with(column, "Minecraft"));
        table.insert(new Row(table, db).with(column, "Call of Duty: Black Ops Cold War"));
        table.insert(new Row(table, db).with(column, "Call of Duty: Black Ops 2"));
        table.insert(new Row(table, db).with(column, "Call of Duty: Warzone"));
        table.insert(new Row(table, db).with(column, "Call of Duty: Modern Warfare"));
        table.insert(new Row(table, db).with(column, "League of Legends"));
        table.insert(new Row(table, db).with(column, "Apex Legens"));
        table.insert(new Row(table, db).with(column, "Grand Theft Auto 5"));
        table.insert(new Row(table, db).with(column, "Shellshock Live"));
        table.insert(new Row(table, db).with(column, "Remant from the Ashes"));
        table.insert(new Row(table, db).with(column, "Rougue Company"));
        table.insert(new Row(table, db).with(column, "Pico Park"));
        table.insert(new Row(table, db).with(column, "Raft"));
        table.insert(new Row(table, db).with(column, "Rocket_League"));
        table.insert(new Row(table, db).with(column, "Split Gate"));
        table.insert(new Row(table, db).with(column, "Fornite"));
        table.insert(new Row(table, db).with(column, "Orcs Must Die! 3"));
        table.insert(new Row(table, db).with(column, "Immortal Fenxy Rising"));
        table.insert(new Row(table, db).with(column, "Stranded_Deep"));
        table.insert(new Row(table, db).with(column, "Among Us"));
        table.insert(new Row(table, db).with(column, "Watch Dogs 2"));
        table.insert(new Row(table, db).with(column, "Satisfactory"));
        table.insert(new Row(table, db).with(column, "Kingdom new Lands"));
        table.insert(new Row(table, db).with(column, "Counter Strike"));
        table.insert(new Row(table, db).with(column, "FarCry 5"));
        table.insert(new Row(table, db).with(column, "FarCry 6"));
        table.insert(new Row(table, db).with(column, "Mud Runner"));
        table.insert(new Row(table, db).with(column, "Battelfront 2"));
        table.insert(new Row(table, db).with(column, "StarCraft 1"));
        table.insert(new Row(table, db).with(column, "StarCraft 2"));
        table.insert(new Row(table, db).with(column, "Age of Empire 2"));
        table.insert(new Row(table, db).with(column, "Subnautica"));
        table.insert(new Row(table, db).with(column, "Subnautica Below Zero"));
        table.insert(new Row(table, db).with(column, "Sea of Thives"));
        table.insert(new Row(table, db).with(column, "Supraland"));
        table.insert(new Row(table, db).with(column, "Terraria"));
        table.insert(new Row(table, db).with(column, "Stone.world"));
        table.insert(new Row(table, db).with(column, "Overcooked"));
    }

    public static void fillFactTable(Database db, @NotNull Table table) {
        String column = "name";
        table.insert(new Row(table, db).with(column, "Den Kopf gegen die Wand zu schlagen verbrennt 150 Kalorien."));
        table.insert(new Row(table, db).with(column, "Ein kleinen Kind kann durch die Venen eines Blauwals schwimmen."));
        table.insert(new Row(table, db).with(column, "Hitlers Mutter hat in Betracht gezogen abzutreiben aber der Doktor hat sie überzeugt das Baby zu behalten."));
        table.insert(new Row(table, db).with(column, "Seeotter halten im Schlaf Händchen, damit sie nicht voneinander abdriften."));
        table.insert(new Row(table, db).with(column, "In Großbritannien ist es illegal, am Weihnachtstag Hackfleisch Pasteten zu essen."));
        table.insert(new Row(table, db).with(column, "Pteronophobie ist die Angst, von Vätern gekitzelt zu werden."));
        table.insert(new Row(table, db).with(column, "Wenn Flusspferde verärgert sind, wird ihr Schweiß rot."));
        table.insert(new Row(table, db).with(column, "Eine Herde von Krähen wird als Mörder bezeichnet."));
        table.insert(new Row(table, db).with(column, "Die “Facebook Sucht” ist eine psychische Störung, die von Psychologen identifiziert wurde."));
        table.insert(new Row(table, db).with(column, "Die durchschnittliche Frau verbraucht in 5 Jahre ca. 1,7 Meter Lippenstift."));
        table.insert(new Row(table, db).with(column, "Der 29. Mai ist der offizielle “Steck-ein-Kissen-in-dein-Gefrierfach-Tag”."));
        table.insert(new Row(table, db).with(column, "Cherophobie ist die Angst vor Spaß."));
        table.insert(new Row(table, db).with(column, "Menschlicher Speichel hat einen dreimal so hohen Siedepunkt wie normales Wasser"));
        table.insert(new Row(table, db).with(column, "Wenn man einen Känguru-Schwanz anhebt kann es nicht hüpfen."));
        table.insert(new Row(table, db).with(column, "Bananen sind krumm weil sie in Richtung der Sonne wachsen."));
        table.insert(new Row(table, db).with(column, "Billy-Ziegen urinieren auf ihren eigenen Köpfe um attraktiver für Weibchen zu riechen."));
        table.insert(new Row(table, db).with(column, "Der Erfinder der Frisbee wurde nach seinem Tod eingeäschert und zu einer Frisbee verarbeitet."));
        table.insert(new Row(table, db).with(column, "In deinem Leben produzierst du so viel Speichel um zwei swimming pools zu füllen."));
        table.insert(new Row(table, db).with(column, "Wenn Pinocchio sagt “Meine Nase wächst gerade” geschieht das Lügner Paradox. "));
        table.insert(new Row(table, db).with(column, "Polarbären können bis zu 86 Pinguine essen."));
        table.insert(new Row(table, db).with(column, "König Henry VIII schlief mit eine riesigen Axt neben seinem Bett."));
        table.insert(new Row(table, db).with(column, "Filmtrailer wurden ursprünglich nach dem Film gezeigt, deswegen werden sie auch “trailer” genannt."));
        table.insert(new Row(table, db).with(column, "Ein Adler kann einen jungen Hirsch töten und mit ihm wegfliegen."));
        table.insert(new Row(table, db).with(column, "Herzinfarkte passieren am häufigsten an einem Montag."));
        table.insert(new Row(table, db).with(column, "Wenn du kontinuierlich pupsen würdest, hättest du nach 6 Jahren und 9 Monaten genügend Gas für eine Atombombe produziert."));
        table.insert(new Row(table, db).with(column, "2015 sind mehr Menschen an den Verletzungen durch ein Selfie gestorben als von Haiangriffen."));
        table.insert(new Row(table, db).with(column, "Die top 6 Nahrungsmittel, durch die du pupsen kannst sind Bohnen, Mais, Paprika, Blumenkohl, Kohl und Milch."));
        table.insert(new Row(table, db).with(column, "Es gibt eine Spezies von Spinnen, die Feldwinkelspinne."));
        table.insert(new Row(table, db).with(column, "Das Brüllen eines Löwen kann bis zu 8 km gehört werden."));
        table.insert(new Row(table, db).with(column, "Ein Toaster benötigt fast halb so viel Energie wie ein normaler Ofen."));
        table.insert(new Row(table, db).with(column, "Babyspinnen nennt man Spiderlinge."));
        table.insert(new Row(table, db).with(column, "Du kannst nicht zur gleichen Zeit schnarchen und träumen."));
        table.insert(new Row(table, db).with(column, "Den folgenden Satz kann man vorwärts sowie rückwärts lesen: Die Liebe ist Sieger, stets rege ist sie bei Leid."));
        table.insert(new Row(table, db).with(column, "Ein Babyoktopus hat die Größe eines Flohs wenn es geboren ist."));
        table.insert(new Row(table, db).with(column, "Ein Scharf, eine Ente und ein Hahn waren die ersten Passagiere in einem Heißluftballon."));
        table.insert(new Row(table, db).with(column, "In Uganda ist die Hälfte der Bevölkerung unter 15 Jahre alt."));
        table.insert(new Row(table, db).with(column, "Arabische Frauen können eine Scheidung beantragen wenn ihr Ehemänner keinen Kaffee für sie einschenken."));
        table.insert(new Row(table, db).with(column, "Das Recycling eines Glases spart genauso viel Energie wie 3 Stunden Tv zu schauen."));
        table.insert(new Row(table, db).with(column, "Einen kleinen bisschen Hundekot auf einen Insektenbiss zu verschmieren lindert Juckreiz und Schwellung."));
        table.insert(new Row(table, db).with(column, "Welse sind die einzigen Tiere, die eine ungerade Anzahl Schnurrhaare haben."));
        table.insert(new Row(table, db).with(column, "Facebook, Skype und Twitter sind alle in China verboten."));
        table.insert(new Row(table, db).with(column, "95% der Menschen texten Dinge, die sie nie persönlich sagen würden."));
        table.insert(new Row(table, db).with(column, "Die Titanic war das erste Schiff, dass das SOS-Signal verwendet hat."));
        table.insert(new Row(table, db).with(column, "Über 8.000 Menschen in Amerika werden jährlich durch Musikinstrumente verletzt."));
        table.insert(new Row(table, db).with(column, "Die französische Sprache hat sieben verschiedene Wörter für “Kapitulation”."));
        table.insert(new Row(table, db).with(column, "Fast 3% des Eises der antarktischen Gletschers sind aus Pinguin-Urin."));
        table.insert(new Row(table, db).with(column, "Bob Dylans echter Name ist Robert Zimmerman."));
        table.insert(new Row(table, db).with(column, "Ein Krokodil kann nicht seine Zunge rausstrecken."));
        table.insert(new Row(table, db).with(column, "Bin Ladens Tod wurde am 1. Mai 2011 festgestellt, Hitlers Tod wurde am 1. Mai 1945 festgestellt."));
        table.insert(new Row(table, db).with(column, "J.K. Rowling hat den ungewöhnlichen Namen “Hermi(o)ne” gewählt damit junge Mädchen nicht dafür gehänselt werden ein Nerd zu sein."));
        table.insert(new Row(table, db).with(column, "Hewlett Packards (HP) Name wurde durch einen Münzwurf entschieden."));
        table.insert(new Row(table, db).with(column, "Die Anzahl der Stufen des Eifelturms beträgt 1665."));
        table.insert(new Row(table, db).with(column, "Der Pokemon Hitmonlee und Hitmonchan wurden nach Bruce Lee und Jackie Chan benannt."));
        table.insert(new Row(table, db).with(column, "Ein Arcophiler ist eine Person, die Teddybären sammelt oder sie sehr gerne mag."));
        table.insert(new Row(table, db).with(column, "Piraten trugen Ohrringe weil sie dachten, dass es das Sehvermögen verbessert."));
        table.insert(new Row(table, db).with(column, "Los Angeles ganzer Name lautet  “El Pueblo de Nuestra Senora la Reina de los Angeles de Porciuncula”."));
        table.insert(new Row(table, db).with(column, "Der Twitter-Vogel hat einen Namen – Larry."));
        table.insert(new Row(table, db).with(column, "Oktopusse haben vier Paar Arme."));
        table.insert(new Row(table, db).with(column, "In England wurde in den 1880er “Hose” als böses Wort bezeichnet."));
        table.insert(new Row(table, db).with(column, "Am 18. Februar 1979 schneite es in der Wüste von Sahara für 30 Minuten."));
        table.insert(new Row(table, db).with(column, "Jeder Mensch verbrachte ca. eine halbe Stunde als Einzelzelle."));
        table.insert(new Row(table, db).with(column, "Wenn du alles in letzter Minute machst … dauert es nur eine Minute."));
        table.insert(new Row(table, db).with(column, "Im Gegensatz zu vielen anderen Großkatzen sind Schneeleoparden nicht aggressiv gegenüber Menschen. Es gibt keinen bestätigten Schneeleoparden-Angriff."));
        table.insert(new Row(table, db).with(column, "Der erste Wecker konnte nur um 4:00 Uhr klingeln."));
        table.insert(new Row(table, db).with(column, "Vögel urinieren nicht."));
        table.insert(new Row(table, db).with(column, "Sterben im Parlamentshaus ist verboten – das wurde von den britischen Bürgern als das lächerlichste Gesetzt gewählt."));
        table.insert(new Row(table, db).with(column, "Die giftigste Qualle der Welt heißt Irukandji und ist kleiner als Fingernagel."));
        table.insert(new Row(table, db).with(column, "Der 20. Mai ist bekannt als “Snowman Burning Day”."));
        table.insert(new Row(table, db).with(column, "Schnecken haben 4 Nasen."));
        table.insert(new Row(table, db).with(column, "Panphobie ist die Angst vor allem …"));
        table.insert(new Row(table, db).with(column, "Ein Apfel, eine Kartoffel und eine Zwiebel schmecken genau gleich wenn die Nase geschlossen ist."));
        table.insert(new Row(table, db).with(column, "Die Vorderpfoten einer Katze sind anders als die Hinterpfoten. Sie haben 5 Zehen vorne aber nur 4 hinten."));
        table.insert(new Row(table, db).with(column, "Der durchschnittliche Mensch läuft in seinem Leben ca. zweimal um die Erde."));
        table.insert(new Row(table, db).with(column, "Die Bibel ist das meist geklaute Buch der Welt."));
        table.insert(new Row(table, db).with(column, "Marco Hort hat den Weltrekord in Strohhalme in den Mund stecken. Er schaffte 264 Stück."));
        table.insert(new Row(table, db).with(column, "Mel Blanc, die Stimme von Bugs Bunny, war gegen Karotten allergisch."));
        table.insert(new Row(table, db).with(column, "Kalifornien hat 6 Führerscheine ausgestellt mit den Namen Jesus Christus."));
        table.insert(new Row(table, db).with(column, "Nach Genisis 1:20-22 kam das Huhn vor dem Ei."));
        table.insert(new Row(table, db).with(column, "In der Karibik gibt es Austern, die Bäume hochklettern können."));
        table.insert(new Row(table, db).with(column, "Würmer essen ihre eigen Kot."));
        table.insert(new Row(table, db).with(column, "Eichhörnchen vergessen die Hälft der Orte, an denen Sie Nüsse versteckt haben."));
        table.insert(new Row(table, db).with(column, "Über 1.000 Vögel sterben indem sie gegen Fensterscheiben fliegen."));
        table.insert(new Row(table, db).with(column, "Der Erfinder des Waffeleisens mag keine Waffeln."));
        table.insert(new Row(table, db).with(column, "George W. Bush war mal ein Cheerleader."));
        table.insert(new Row(table, db).with(column, "Insgesamt gibt es 205 Knochen im Skeletts eines Pferdes."));
        table.insert(new Row(table, db).with(column, "Erdbeeren können auch gelb, grün oder weiß sein. Das beeinflusst auch das Geschmack, manche schmecken sogar nach Ananas."));
        table.insert(new Row(table, db).with(column, "Jedes Jahr sterben 2.500 Linkshänder durch die Verwendung von Rechtshänder-Produkten."));
        table.insert(new Row(table, db).with(column, "Madonna leidet unter Garophobia, die Angst vor Donner."));
        table.insert(new Row(table, db).with(column, "Kleenex-Tücher wurden ursprünglich als Filter für Gasmasken verwendet."));
        table.insert(new Row(table, db).with(column, "Während deines Lebens verbringst du ca. 38 Tage mit Zähne putzen."));
        table.insert(new Row(table, db).with(column, "Ronald McDonald wird in Japan “Donald McDonald” genannt, da die Aussprache leichter ist. In Singapur heißt er “Onkel McDonald”."));
    }
}
