package de.goldendeveloper.entertainment.util;

import de.goldendeveloper.entertainment.Main;
import de.goldendeveloper.mysql.entities.Row;
import de.goldendeveloper.mysql.entities.Table;

public class Fact {

    public Fact(Table table) {
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Den Kopf gegen die Wand zu schlagen verbrennt 150 Kalorien."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Ein kleinen Kind kann durch die Venen eines Blauwals schwimmen."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Hitlers Mutter hat in Betracht gezogen abzutreiben aber der Doktor hat sie überzeugt das Baby zu behalten."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Seeotter halten im Schlaf Händchen, damit sie nicht voneinander abdriften."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "In Großbritannien ist es illegal, am Weihnachtstag Hackfleisch Pasteten zu essen."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Pteronophobie ist die Angst, von Vätern gekitzelt zu werden."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wenn Flusspferde verärgert sind, wird ihr Schweiß rot."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Eine Herde von Krähen wird als Mörder bezeichnet."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Die “Facebook Sucht” ist eine psychische Störung, die von Psychologen identifiziert wurde."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Die durchschnittliche Frau verbraucht in 5 Jahre ca. 1,7 Meter Lippenstift."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Der 29. Mai ist der offizielle “Steck-ein-Kissen-in-dein-Gefrierfach-Tag”."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Cherophobie ist die Angst vor Spaß."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Menschlicher Speichel hat einen dreimal so hohen Siedepunkt wie normales Wasser"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wenn man einen Känguru-Schwanz anhebt kann es nicht hüpfen."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Bananen sind krumm weil sie in Richtung der Sonne wachsen."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Billy-Ziegen urinieren auf ihren eigenen Köpfe um attraktiver für Weibchen zu riechen."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Der Erfinder der Frisbee wurde nach seinem Tod eingeäschert und zu einer Frisbee verarbeitet."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "In deinem Leben produzierst du so viel Speichel um zwei swimming pools zu füllen."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wenn Pinocchio sagt “Meine Nase wächst gerade” geschieht das Lügner Paradox. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Polarbären können bis zu 86 Pinguine essen."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "König Henry VIII schlief mit eine riesigen Axt neben seinem Bett."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Filmtrailer wurden ursprünglich nach dem Film gezeigt, deswegen werden sie auch “trailer” genannt."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Ein Adler kann einen jungen Hirsch töten und mit ihm wegfliegen."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Herzinfarkte passieren am häufigsten an einem Montag."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wenn du kontinuierlich pupsen würdest, hättest du nach 6 Jahren und 9 Monaten genügend Gas für eine Atombombe produziert."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "2015 sind mehr Menschen an den Verletzungen durch ein Selfie gestorben als von Haiangriffen."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Die top 6 Nahrungsmittel, durch die du pupsen kannst sind Bohnen, Mais, Paprika, Blumenkohl, Kohl und Milch."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Es gibt eine Spezies von Spinnen, die Feldwinkelspinne."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Das Brüllen eines Löwen kann bis zu 8 km gehört werden."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Ein Toaster benötigt fast halb so viel Energie wie ein normaler Ofen."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Babyspinnen nennt man Spiderlinge."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Du kannst nicht zur gleichen Zeit schnarchen und träumen."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Den folgenden Satz kann man vorwärts sowie rückwärts lesen: Die Liebe ist Sieger, stets rege ist sie bei Leid."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Ein Babyoktopus hat die Größe eines Flohs wenn es geboren ist."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Ein Scharf, eine Ente und ein Hahn waren die ersten Passagiere in einem Heißluftballon."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "In Uganda ist die Hälfte der Bevölkerung unter 15 Jahre alt."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Arabische Frauen können eine Scheidung beantragen wenn ihr Ehemänner keinen Kaffee für sie einschenken."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Das Recycling eines Glases spart genauso viel Energie wie 3 Stunden Tv zu schauen."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Einen kleinen bisschen Hundekot auf einen Insektenbiss zu verschmieren lindert Juckreiz und Schwellung."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Welse sind die einzigen Tiere, die eine ungerade Anzahl Schnurrhaare haben."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Facebook, Skype und Twitter sind alle in China verboten."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "95% der Menschen texten Dinge, die sie nie persönlich sagen würden."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Die Titanic war das erste Schiff, dass das SOS-Signal verwendet hat."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Über 8.000 Menschen in Amerika werden jährlich durch Musikinstrumente verletzt."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Die französische Sprache hat sieben verschiedene Wörter für “Kapitulation”."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Fast 3% des Eises der antarktischen Gletschers sind aus Pinguin-Urin."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Bob Dylans echter Name ist Robert Zimmerman."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Ein Krokodil kann nicht seine Zunge rausstrecken."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Bin Ladens Tod wurde am 1. Mai 2011 festgestellt, Hitlers Tod wurde am 1. Mai 1945 festgestellt."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "J.K. Rowling hat den ungewöhnlichen Namen “Hermi(o)ne” gewählt damit junge Mädchen nicht dafür gehänselt werden ein Nerd zu sein."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Hewlett Packards (HP) Name wurde durch einen Münzwurf entschieden."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Die Anzahl der Stufen des Eifelturms beträgt 1665."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Der Pokemon Hitmonlee und Hitmonchan wurden nach Bruce Lee und Jackie Chan benannt."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Ein Arcophiler ist eine Person, die Teddybären sammelt oder sie sehr gerne mag."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Piraten trugen Ohrringe weil sie dachten, dass es das Sehvermögen verbessert."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Los Angeles ganzer Name lautet  “El Pueblo de Nuestra Senora la Reina de los Angeles de Porciuncula”."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Der Twitter-Vogel hat einen Namen – Larry."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Oktopusse haben vier Paar Arme."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "In England wurde in den 1880er “Hose” als böses Wort bezeichnet."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Am 18. Februar 1979 schneite es in der Wüste von Sahara für 30 Minuten."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Jeder Mensch verbrachte ca. eine halbe Stunde als Einzelzelle."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wenn du alles in letzter Minute machst … dauert es nur eine Minute."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Im Gegensatz zu vielen anderen Großkatzen sind Schneeleoparden nicht aggressiv gegenüber Menschen. Es gibt keinen bestätigten Schneeleoparden-Angriff."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Der erste Wecker konnte nur um 4:00 Uhr klingeln."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Vögel urinieren nicht."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Sterben im Parlamentshaus ist verboten – das wurde von den britischen Bürgern als das lächerlichste Gesetzt gewählt."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Die giftigste Qualle der Welt heißt Irukandji und ist kleiner als Fingernagel."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Der 20. Mai ist bekannt als “Snowman Burning Day”."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Schnecken haben 4 Nasen."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Panphobie ist die Angst vor allem …"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Ein Apfel, eine Kartoffel und eine Zwiebel schmecken genau gleich wenn die Nase geschlossen ist."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Die Vorderpfoten einer Katze sind anders als die Hinterpfoten. Sie haben 5 Zehen vorne aber nur 4 hinten."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Der durchschnittliche Mensch läuft in seinem Leben ca. zweimal um die Erde."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Die Bibel ist das meist geklaute Buch der Welt."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Marco Hort hat den Weltrekord in Strohhalme in den Mund stecken. Er schaffte 264 Stück."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Mel Blanc, die Stimme von Bugs Bunny, war gegen Karotten allergisch."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Kalifornien hat 6 Führerscheine ausgestellt mit den Namen Jesus Christus."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Nach Genisis 1:20-22 kam das Huhn vor dem Ei."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "In der Karibik gibt es Austern, die Bäume hochklettern können."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Würmer essen ihre eigen Kot."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Eichhörnchen vergessen die Hälft der Orte, an denen Sie Nüsse versteckt haben."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Über 1.000 Vögel sterben indem sie gegen Fensterscheiben fliegen."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Der Erfinder des Waffeleisens mag keine Waffeln."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "George W. Bush war mal ein Cheerleader."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Insgesamt gibt es 205 Knochen im Skeletts eines Pferdes."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Ertable.getDatabase()eeren können auch gelb, grün oder weiß sein. Das beeinflusst auch das Geschmack, manche schmecken sogar nach Ananas."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Jedes Jahr sterben 2.500 Linkshänder durch die Verwendung von Rechtshänder-Produkten."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Madonna leidet unter Garophobia, die Angst vor Donner."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Kleenex-Tücher wurden ursprünglich als Filter für Gasmasken verwendet."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Während deines Lebens verbringst du ca. 38 Tage mit Zähne putzen."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Ronald McDonald wird in Japan “Donald McDonald” genannt, da die Aussprache leichter ist. In Singapur heißt er “Onkel McDonald”."));

    }
}
