package de.goldendeveloper.entertainment.util;

import de.goldendeveloper.entertainment.Main;
import de.goldendeveloper.mysql.entities.Row;
import de.goldendeveloper.mysql.entities.Table;
import org.jetbrains.annotations.NotNull;

public class Joke {

    public Joke(@NotNull Table table) {
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Aus welchem Land kommen Schornsteinfeger? Aus Rußland!"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Axl Rose hat seiner nordfriesischen Freundin ein Liebeslied geschrieben: Sweet Child of Moin."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Beim Zahnarzt: Das kann jetzt ein bisschen weh tun. - Kein Problem. - Ich hab seit 3 Jahren ein Verhältnis mit Ihrer Frau."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Brennholzverleih."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Dem Reh fallen die Haare aus. Der Doktor weist es in eine Rehhaarklinik ein."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Der Erfinder des Post-It-Zettels ist gestorben. Die tröstliche Nachricht: Es gibt ein Kleben nach dem Tod."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Der Pfannkuchenbäcker ist an seinem eigenen Teig erstickt. Einfach crepiert."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Egal wie gut Du fährst, Züge fahren Güter."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Ein Besoffener beschimpft und beleidigt ein Helium. Und was macht es? Es reagiert nicht."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Ein Gockel bekommt eine Blasterpistole. Aus versehen bringt er damit alle Hühner um. Da ist der Hahn Solo."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Einbruch bei Adidas. Was schickt die Polizei? Drei Streifen."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Fliegt ein Kuckuck übers Meer. Grüßt ihn ein Hai:Hi"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Fragt der Polizist: Haben sie Restalkohol? - Nee, alles ausgetrunken."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Geben sich verliebte Anästhesisten eigentlich Narkosenamen?"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Gehen zwei Zahnstocher durch den Wald. Kommt ein Igel vorbei. Sagt der eine Zahnstocher: Ich wusste gar nicht, dass hier ein Bus fährt."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Geht ein Cowboy zum Friseur. Als er wieder rauskommt ist sein Pony weg."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Geht eine schwangere Frau zum Bäcker und sagt:Ich bekomme ein Brot."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Huch, meine Uhr ist runter gefallen. Ich kann sie nicht aufheben. - Ich hab kein Uhrheberrecht."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Hüpft ein Rudel Gurken durch den Wald. Was ist falsch? Gurken sind keine Rudeltiere."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Ich bin so unentschlossen. Als japanischer Krieger wäre ich ein Nunja."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Ich brauche eine Krankschreibung? Was fehlt ihnen denn? Eine Krankschreibung."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Ich habe bei den Weight Watchers angerufen: Aber keine hat abgenommen."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Ich habe bei einem Brötchen angerufen, aber:War belegt."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Ich habe bei nem DJ angerufen:Der hat einfach aufgelegt."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Ich habe bei Spiderman angerufen, aber der hatte kein Netz."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Ich habe beim Arzt angerufen:Ich wurde aber nicht verbunden."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Ich habe beim Bäcker angerufen, da ging aber nur die Mehlbox ran."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Ich habe beim Metzger angerufen, aber kein Schwein ging ran."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Ich habe das Herz eines Löwen ...und lebenslanges Verbot im Leipziger Zoo."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Ich habe einem Hipster ans Schienbein getreten.Jetzt hopster."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Ich habe einen total lieben Hund, der ist so ruhig - der hat sogar den No -Bell preis gewonnen."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Ich habe in der Botschaft angerufen, aber keiner ging ran.War wohl Kanada."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Ich habe meiner Frau zu Weihnachten einen Nerz geschenkt und jetzt weigert sie sich, das Tier zufüttern."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Ich wollte einen Witz über die Deutsche Bahn machen, aber ich wusste nicht ob der ankommt."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Im Restaurant:Isst Du gerne wild?-Nein, ganz normal und langsam. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "In Mittelamerika gibt es kaum gute Tapezierer - aber dafür Guatemala !"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "In St.Pauli wurde gestern ein Sarg gefunden.Aber der ging und ging nicht auf.War wohl ein Zuhälter drin ? "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "In welchem Land ist man so langsam wie eine Schnecke ?In Kriechenland."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "In welcher Maßeinheit messen Hunde ihre Temperatur ? In Belgrad. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Klaus war echt nervig, deshalb bekam er nie frische Brötchen.Klaus störte Bäcker. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Kommt ein Dachdecker in eine Bar. —Sagt der Wirt: Der geht aufs Haus. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Kommt ein Frosch in den Milchladen.Fragt die Verkäuferin: Was willst du denn? - Sagt der Frosch:Quak. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Kommt ein Igel in die Konditorei:Einmal Rumkugeln bitte-- Wenn sie wollen, wir haben gerade frisch gewischt."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Kommt ein Pferd in den Blumenladen:Haben sie Mageriten? (ma  geritten)"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Mein Arzt hat eine südamerikanische Augenkrankheit bei mir diagnostiziert - ich Chile."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Mein Hund ein echter Charmeur.Immer wenn ich ihn fragt:Na wie sehe ich aus, sagt er: Wau !"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Mir ist kalt - ich geh mal in die Ecke.Da sind 90 Grad. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Neulich im Tatort: Wo waren Sie zur Tatzeit ? -Im Internet !"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Papa, in Ägypten ist nächste Woche auch keine Schule ! --  Ok ?  --  Ja, die haben da Sphinxferien !"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Sagt der Pessimist: Schlimmer geht nicht! - Sagt der Optimist:Doch!"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Sagt der Walfisch zum Tuhnfisch: Was wollen wir tun, Fisch? Sagt der Thunfisch:Du hast die Wahl, Fisch! "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Sagt die eine Kerze zur anderen:Du, ist Wasser eigentlich gefährlich ? -Sagt die andere:Davon kannst Du ausgehen."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Sagt die eine Sicherung zur anderen:Lass uns zusammen durchbrennen !"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Sagt die eine Wand zur anderen Wand: Wir treffen uns an der Ecke."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Sagt die Erbse zur anderen: Vorsicht, da ist eine Trepepepepepepepepe..."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Schicke Unterwäsche !-Wohin ? "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Sprechstundenhilfe: Warum tragen Sie eine Augenklappe ?  Ich bin Piratpatient. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Steht ein Baum allein im Wald..."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Steht ein Pils im Wald.Kommt ein Hase und trinkt es aus.Und warum steht ein Pils im Wald ? Weil die Tannen zapfen."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Stelle dir zwei bayerisch getrachtet Personen vor, die die Daumen nach oben recken.In der anderen Hand Bier und Brezn.Was ist das ? Confirmation Bayers"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Stiftung Warentest hat Besteck getestet.Das Messer hat am besten abgeschnitten."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Tage an denen man plant, Bananen zu essen, nennt man Bananenplantage."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Tonic ohne Alkohol ist übrigens ginlos."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Treffen sich zwei Magneten:Was zieh ich heute bloß an?"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Unterhalten sich zwei Fliesenleger:Wo sind denn die ganzen Fliesen hin? Oh, die muss ich wohl verlegt haben."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wann gehen U - Boote unter ? Am Tag der offenen Tür."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Warum darf das Neutron nicht in die Disco?Heute nur geladene Gäste !"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Warum findet ein Henker nie den Rückweg ? Weil der nur die Hinrichtung kennt. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Warum fliegen Störche im Winter in den Süden?-Weil Laufen zu lange dauern würde. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Warum gehen Ameisen am Sonntag nicht in die Kirche ? Weil Ameisen Insekten sind. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Warum gibt es in Booten keinen Honig ? Weil es auf Schiffen ka -bienen gibt. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Warum haben diese Fische so ausgesprochen gute Zähne ?Das sind Kariesprofilachse. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Warum haben Fische Schuppen?Damit sie ihre Fahrräder unterstellen können."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Warum ist der Florist über seine Lieferung traurig?Sie ist eingegangen. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Warum klaut Robin Hood Deo ? Um es unter den Armen zu verteilen !"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Warum können Seeräuber schlecht mit Kreisen Rechnen ? Weil sie Pi -Raten !"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Warum können Skelette so schlecht lügen ?Die sind so einfach zu durchschauen."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Warum leben Haie im Salzwasser ? Weil sie von Pfefferwasser niesen müssen. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Warum muss die Spinne grillen ? Sie ist ein Weberknecht. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Warum sind bei IKEA Pfeile am Boden ? Weil es ein Einrichtungshaus ist."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Warum sind Fußballer eine Gefahr im Straßenverkehr ? Weil sie bei rot gehen müssen. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Warum steht die Freiheitsstatue in New York ? Weil sie sich nicht setzen kann. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Warum summen Bienen ? Weil sie den Text nicht kennen. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Warum wachsen auf dem Mond keine Blumen ? Zu wenig Erde."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was bekommt ein Kannibale, der zu spät zum Essen kommt ? Die kalte Schulter."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was benutzt ein Bär als Eingabegerät?Eine Tatzatur."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was bestellt ein Maulwurf im Restaurant? —Ein Drei -Gänge - Menü. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was denken sich die Gletscher zum Klimawandel ? Wir werden Seen."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was erzählen sich holländische Süßspeisen am liebsten ? Vla - chwitze. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was erzählt Weizen sich gegenseitig beim Campen ? Grieselgeschichten. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was essen Autos am liebsten ? —Parkplätzchen. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was essen Piraten am liebsten ? —Kapern. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was findet man beim Kannibalen in der Dusche ? —Head and Shoulders. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was freut sich und stinkt ? -Das Gefurztagskind. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was für ein Gefühl hatte Mozart beim Komponieren ?Einen Haydn -Spaß. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was gibt es bei Olympia—Teilnehmern zum Nachtisch ? —Fackelpudding !"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was gräbt und ist aus der Puste ? Eine Schnaufel. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was hat acht Arme und fliegt durchs Weltall?Eine Krakete."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was hat acht Beine und schummelt?Eine Mogelspinne."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was hat ein Mann, der im Dreieck läuft ? Kreislaufprobleme. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was hat einen Beutel und schießt ?Ein Penguruh."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was hat Haare und wird gebraten ?Bartkartoffeln. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was hoppelt über die Wiese und raucht aus den Ohren ?Ein Kaminchen."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was isst eine Sadomaso Frau vor Weihnachten ? Domina - Steine. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was isst Familie Biber zu abend ?Tischstäbchen. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist braun und hilft dir, wenn du traurig bist ? Ein Trost - brot. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist braun und hängt mit nem Warndreieck im Baum ?Ein Pannenzapfen."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist braun und schwimmt unter Wasser ? Ein U - Brot. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist braun, kann fliegen und macht Kindern die Zähne kaputt ? -Die Toffi - Fee !"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist braun, lebt im Nil und schmeckt lecker ? Ein Schokodil. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist braun, lecker und gesund?Schogolade. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist bunt und will dringend aus dem Zimmer raus ?Ein Fluchtsalat."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist bunt, leuchtet und kann nicht schwimmen?ein Bagger mit Lichterkette."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist bunt, süß und ein bisschen einfach gestrickt ? Ein Dummibärchen."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist das agressivste Milchprodukt?Schlagsahne."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist das Gegenteil von Japan ? Neinpan."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist das Wichtigste an den Elefanten?Das zweite E, sonst wären es nur 11 Anten. (bayerisch vorgelesen)"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist der unförmigste Seevogel von Nordfriesland ? Die Amöve."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist die größte Anerkennung unter Aquarellisten ? Verläuft bei Dir!"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist durchsichtig, stinkt und ignorant? Ein Schnurz."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist ein Cowboy ohne Pferd? Ein Sattelschlepper."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist ein Keks unter einem Baum? Ein schattiges Plätzchen."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist ein nackter Ritter? Ent - rüstet!"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist eine Glühbirne, die schockiert zu Boden fällt?Fassungslos!"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist eine Kastanie hinter Gittern? Eine Knastanie."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist gelb und flattert im Wind? Eine Fahnane."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist gelb und hüpft durch den Wald?Ein Postfrosch."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist gelb und kann nicht schwimmen ? Ein Bagger. Und warum? Weil er nur einen Arm hat."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist gelb und läuft den Baum hoch?Ein Posthörnchen."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist gelb und schießt ? Eine Banone."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist gelb und schwimmt über n See? Eine Schwanane."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist gelb und steht am Fenster ? -Eine Spannanas."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist gesund, kräftig und spielt den beleidigten?Das andere Schmollkornbrot."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist groß, braun und schreibt undeutlich ? Ein Kritz - li - bär."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist groß, grau und interessiert niemanden ? Ein Irrelephant."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist groß, grau und ruft gleich an?Ein Telefant."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist grün und fliegt durchs Weltall? Ein Salatelit."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist grün und fährt Pandabären zur Arbeit ? Ein Bam - bus."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist grün und gewinnt jedes Rennen?Ein Schnellerie."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist grün und hüpft durch den Wald?Ein Rudel Gurken."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist grün und liegt im Sarg?Eine Sterbse."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist grün und macht die Toilette sauber?Ein Klokodil."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist grün und schnarcht am Wegesrand ? Eine Pennnessel."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist grün und sitzt auf dem Klo ? Der Kacktus."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist grün und tut weh, wenn man es ins Auge kriegt ? Ein Billardtisch."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist grün und will dringend ins Zimmer ? Ein Klopfsalat."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist grün, blind und kann singen ? Kiwi Wonder."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist grün, hängt an der Türklinke und guckt durchs Schlüsselloch ? Ein Spionat."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist grün, sauer und versteckt sich vor der Polizei ? Ein Essig - Schurke."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist grün, schlau und stellt viele Fragen ? -Günther Lauch."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist grün, sitzt auf einem Baum und wenn es runterfällt bist Du verletzt ? Ein Billiardtisch."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist grün, springt durchs Gras und ist super happy ? Eine Freuschrecke. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist heiß und flauschig ? Eine Fellkartoffel. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist klein und schwarz und dreht sich auf der Wiese ? Ein Maulwurf beim Hammerwerfen. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist klein, glitschig und immer schlecht gelaunt?Eine Maulquappe."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist langsam, wird steinalt und macht einen Riesenlärm ? Eine Schildtröte. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist lila und bedient im Restaurant ? Eine Obergine. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist lässig und hat einen Euter ? Eine Kuhl. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist orange und kann nicht still sitzen ?Eine Zappelsine."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist orange und läuft durch die Berge ?Eine Wandarine."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist rot und schlecht für die Zähne ?Ein Ziegelstein."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist rot und steht im Wald ? Ein Kirsch. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist rot und wiehert ? Eine Pfertable.getDatabase()eere. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist rot, rund und sitzt auf dem Klo ? Eine Klomate. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist schwarz, rot und lebt in der Arktis ? Ein Pinguin mit Sonnenbrand. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist schwarz - weiß und 50 cm in der Luft?Ein Schwebra."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist schwarz - weiß und explodiert?Ein Sprenguin."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist schwarz - weiß und hüpft auf und ab ? Ein Springuin. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist schwarz - weiß und sitzt auf der Schaukel ? Ein Schwinguin. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist süß und schwingt sich von Torte zu Torte ?Tarzipan. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist süß, klebrig und geht durch die Wüste ? Ein Karamel. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist unter der Erde und stinkt ? Eine Furzel. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist schwarz - weiß und 50 cm in der Luft?Ein Schwebra."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist weiß und fliegt durch den Wald?Biene Mayo."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist weiß und guckt durchs Schlüsselloch ? —Ein Spannbettlaken."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist weiß und rennt den Berg wieder hoch ? Eine Lawine mit Heimweh. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist weiß und schnarcht auf der Wiese ?Ein Schlaf."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist weiß und springt von Baum zu Baum ? Ein Tierarzt bei der Zeckenimpfung."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist weiß und stört beim Essen ? Eine Lawine. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist weiß und tanz im Wald ums Feuer ? Rumpelpilzchen. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was ist wohlhabend und springt von Ast zu Ast ? Ein Scheichhörnchen. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was kauft ein Mann mit zwei linken Füßen im Schuhgeschäft?Flip Flips."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was kommt aufs Brot und schmeckt nach Kleister?Kleberwurst. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was lebt in der Savanne und ist immer sauber ? Eine Hygiäne. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was liegt am Strand und kann man nicht gut verstehen und ist auch noch erkältet ? Eine Niesnuschel. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was liegt am Strand und kann man nicht gut verstehen ?Eine Nuschel."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was machen PiratInnen, wenn Sie nicht mehr weiterwissen?Einen Arrrrrrrbeitskreis."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was machen Tiere in der Disko?Sie diskotieren."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was machen zwei Bäume, wenn sie einen trinken wollen?Sie gehen in ihre Stammkneipe. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was machen zwei wütende Schafe ? Sie bekommen sich in die Wolle. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was macht der Mathematiker beim Skifahren?Er rechnet mit Brüchen."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was macht der Ostfriese wenn er zu Hause mehr elektrische Anschlussleistung braucht?Er geht mit dem Eimer raus und holt sich ein paar Kilo Watt. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was macht ein arbeitsloser Schauspieler ? Spielt keine Rolle."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was macht ein Clown im Büro ?Faxen. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was macht ein schwuler Wurm im Salat ? -Er schmeißt die Schnecken raus."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was macht eine Bombe im Bordell? —Puff. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was macht eine Bombe im Treppenhaus ?Hochgehen. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was macht eine Ente auf dem Router ? Nat. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was macht man mit einem Hund ohne Beine ?Um die Häuser ziehen."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was passiert wenn man Cola und Bier gleichzeitig trinkt ? —Man colabiert."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was piekst und fliest das Bad?Ein Kachelschwein."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was sagt der frustrierte Origami - Lehrer zu seinem Schüler ? Kannste knicken !"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was sagt der Fuchs im Hühnerstall ?Raus aus den Federn !"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was sagt der große Stift zum kleinen Stift ?Wachs - mal - Stift. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was sagt der Holzwurmpapa abends zu seinen Kindern ?Husch, husch ab ins Brettchen. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was sagt der Teig bei der Hochzeit ? Ich bin ganz gerührt !"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was sagt ein Ackerbesteller bei gutem Wetter ? Das Land - wird. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was sagt ein Gen, wenn es ein anderes trifft?-Halogen. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was sagt ein Pirat im Pferdestall ?A, Heu. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was schwimmt auf dem Teich und fängt mit Z an ?Zwei Enten."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was schwimmt im Meer und addiert ?Ein Oktoplus."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was sind die teuersten Tomaten ? Die Geldautomaten. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was sitzt am Frühstückstisch und winkt?Ein Grüsli."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was sitzt auf dem Baum und schreit Aha! - Ein Uhu mit Sprachfehler. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was sitzt auf dem Turm und macht alle 15 Minuten Schuhu?Der Turmuhur."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was sitzt auf einem Baum und winkt ? —Ein Huhu !"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was sitzt ganz hinten im Brotkasten und ist beleidigt ? Ein Schmollkornbrot. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was sitzt im Baum und weint?Eine Heule !"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was steht auf dem Herd und ist total geheim ? Ein Topf Secret !"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was steht Weihnachten im Wohnzimmer und ist kaputt ?Ein Pannenbaum."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was studiert man für einen Führerschein ?Fahr - ma - kologie. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Was wird oft übersehen ?Ein Gartenzaun."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Welche Fische haben die beste Mundhygiene ?Die Zahnprophylachse."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Welche Handwerker essen am meisten ? Maurer, die verputzen ganze Häuser. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Welche Schuhe tragen Raubfische sehr gern ?Hai - Heels. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Welche Weinsorte wächst am Fuße des Vesuvs ? Glühwein. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Welcher Fisch nervt im Unterricht ? Na der Stör !"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Welches Gemüse serviert sich selbst ? Die Obergine. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Welches Getränk trinken Firmenchefs?Leitungswasser. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Welches ist die lustigste Automarke ? Scherzedes. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Welches Maultier sitzt in der Bar und trink Cappuccino ? Das Cafémel. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Welches Obst geht immer in die Kirche ? Die Frommbeere. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Welches Tier badet gern in Tomaten, Basilikum und Olivenöl?Der Mozzarellensittich."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Welches Tier hält immer Maß ? Der Ellensittich. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Welches Tier klebt gerne zwischen den Zähnen ? Der Karamellensittich. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Welches Tier kümmert sich um Meeresbewohner, denen es nicht gut geht?Die Krakenschwester."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Welches Tier trägt Strapse und Korsett und ist auch sonst eher verrucht?Der Bordellensittich."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wenn ein südamerikanisches Kameltier betrunken ist ...ist das dann ein Alkpaka ? "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wenn eine Kapselkaffeemaschine das Zeitliche segnet, schlägt die Stunde des Senseomanns."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wenn Nicolas Wöhrl sich ein Brötchen schmiert ...ist es dann wissenschaftlich belegt ? "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wer ist bunt, flattert durch die Luft und hilft wo er nur kann ? Ein Retterling. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wer ist grün, kann zaubern und riecht streng?Stinkerbell. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wer kümmert sich um die Gräten der Meeresbewohner ?Der Oktopäde."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wer mit Nüssen zahlt, darf sich nicht wundern, wenn Affen für ihn arbeiten."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wer wohnt im Dschungel und schummelt?Mogli. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wie begrüßen sich Schönheitschirurgen ?Na was machst Du denn für ein Gesicht ?"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wie berechnet eine Kuh die Fläche ihrer Weide ?--Mit der Muhtiplikation."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wie heißt das intelligenteste Gemüse ? -Schlaubergine. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wie heißt der Tiger mit Vornamen ?-Schaumfes !"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wie heißt ein Spanier ohne Auto ?Carlos. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wie kastriert man einen Kühlschrank ? Tür auf, Eier raus, Tür zu. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wie nennt man das Küchengerät dass dir heimlich die Süßigkeiten wegisst ? Die Spülnaschine. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wie nennt man das Oberteil von Meerjungfrauen ? Algebra. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wie nennt man den Flur eines Iglus ? Eisdiele !"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wie nennt man den germanischen Gott der Ungeduld ?Hammersbald. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wie nennt man die Steigerung von Buchstabensuppe ? Wörtersee. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wie nennt man ein kleines schwäbisches Schwein, das um Hilfe ruft ? Ein Notrufsäule. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wie nennt man ein Monster mit Schnupfen ? Rotzilla. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wie nennt man ein Rudel aggressiver Wölfe ? Wolfgang. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wie nennt man ein verschwundenes Rindvieh ?-Oxford. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wie nennt man ein weißes Mammut ?Hell - mut !"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wie nennt man ein tiefgefrorenes Mammut ?Hart - mut !"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wie nennt man eine Biene, die diagonal fliegt?Eine Quersumme."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wie nennt man eine Frucht, die ein großes Anwesen hat?--Eine Hektarine. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wie nennt man einen ausgehungerten Frosch ?Magerquark. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wie nennt man einen Bär der KungFu beherrscht ?Grizzly. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wie nennt man einen Ausserirdischen, der in der Informationstechnik arbeitet?Italien. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wie nennt man einen Bären der Granufink braucht ? Ein Pullerbär. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wie nennt man einen Delfin mit einer Unterhose auf dem Kopf ? Slipper. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wie nennt man einen dicken Schriftsteller ?-Kugelschreiber !"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wie nennt man einen dünnen Weihnachtsmann ?Nikolauch. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wie nennt man einen extrem dünnen Frosch ? Magerquak. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wie nennt man einen Gerd, der den Rasen mäht ? Gerd - ner. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wie nennt man einen Hering, der am Flughafen arbeitet ? Einen Zollmops. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wie nennt man einen Hering, der beleidigt ist?Einen Schmollmops."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wie nennt man einen Hering, der die besten Memes postet?Einen Lolmops."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wie nennt man einen Hering, der doofe Kommentare schreibt ? Einen Trollmops. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wie nennt man einen Hering, der gerne Atombombentests macht ? Einen Atollmops. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wie nennt man einen Hering, der gerne Befehle befolgt ? Einen Jawollmops. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wie nennt man einen Hering, der gerne Fußball mag ? Einen(Mehmet) Schollmops. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wie nennt man einen Hering, der gerne strickt?Einen Wollmops."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wie nennt man einen Hering, der immer alles aufschreibt ? Einen Protokollmops. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wie nennt man einen Hering, der immer alles machen muss?Einen Sollmops."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wie nennt man einen Hering, der immer nur traurige Musik spielt ? Einen Mollmops. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wie nennt man einen Hering, der immer sauer ist ? Einen Grollmops. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wie nennt man einen Hering, der immer total begeistert ist?Einen Tollmops."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wie nennt man einen Hering, der Regie führt?Einen(Uwe) Bollmops. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wie nennt man einen Hering, der sehr unkultiviert ist ? Einen Prollmops. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wie nennt man einen Hering, der sich für Umfragen interessiert?Einen Pollmops."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wie nennt man einen Hering, der total besoffen ist ? Einen Vollmops. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wie nennt man einen Hering, der total gerne Puppen mag?Einen Dollmops."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wie nennt man einen Hund der gerne Äpfel isst ? Apfelpudel. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wie nennt man einen hungrigen risikobereiten Wellensittich ? Trill - Seeker "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wie nennt man einen kleinen Matrosen, der sich nicht wäscht ? Na : Ein Meerschweinchen !"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wie nennt man einen kleinen Türsteher ?Sicherheitshalber. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wie nennt man einen Landwirt mit Studium ? Einen Ackerdemiker. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wie nennt man einen überfahrenen Vogel?Piepmatsch !"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wie nennt man Fernsehverbot auf Russisch ?Njetflix. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wie nennt man Han Solo, wenn er in der Disko rumtanzt ? Han Twerker. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wie nennt man heute einen Hofnarr ?Untertainer. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wie nennt man jemand der nur so tut als würde er etwas werfen ? Einen Scheinwerfer. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wie nennt man jemanden der DIN A4 Blätter scannt ? Skan - din - a - vier. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wie nennt man Kaninchen im Fitnessstudio ?Pumpernickel. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wie viel wiegen ein Pferd und ein Hund zusammen ? Ein PfHund !"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wie viele Psychotherapeuten braucht man um eine Glühbirne zu wechseln ?Einen, aber die Birne muss auch wollen. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wie viele Softwareentwickler braucht man um eine Glühbirne zu wechseln ?Keinen, das ist eindeutig ein Hardwareproblem."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wie war die Stimmung in der DDR ? Sie hielt sich in Grenzen."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wieso können Seeräuber keinen Kreis fahren?-Weil sie Pi raten. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Will jemand einen Witz über Natriumhydrat hören - NaH !"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wo baden Eisbären am liebsten ? Im Nordpool. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wo geht Darth Vader shoppen ? In der Darth Mall !"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wo gibt es die meisten Gespenster in Europa ?In Buuuuuuuuhdapest !"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wo ist die Deutschlandzentrale von Burger King ? In Whoppertal. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wo machen Kühe Urlaub?Auf Kuuuhba !"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wo wohnen Katzen ? Im Mietz - Haus !"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wo baden Eisbären am liebsten ? Im Nordpool. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wohin geht ein Baum, wenn er Rückenschmerzen hat ? Zum Kiefer - Orthopäden. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wohin geht ein Zyklop, wenn er nicht gut sieht?Zum Augearzt."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wollte Socken bei H&M kaufen.Oma strickt dagegen. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Womit backen Schlümpfe ? Mit Garga - Mehl. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Womit ist der Boden eines Iglus ausgelegt ? Mit Eisdielen. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Womit kann man eine Webseite hosten, aber nur wenn Vollmond ist?Mit einem Werserver. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Womit verprügeln sich Schafe ?Mit dem Mäh - Drescher. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Womit verzieren Rinder ihren Kuchen ? Mit Kuhvertüre. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wovon träumt eine Katze nachts ? Von einem Muskelkater."));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Wussten Sie, dass Esoteriker häufig zur Arbeit pendeln...?"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Zu welchem Arzt geht Pinocchio ? Zum Holz - Nasen - Ohren - Arzt. "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "„Du hast aber schon mal einen Schornstein gemauert, oder?“ „Nein, das ist ein Versuchskaminchen."));
    }
}
