package de.goldendeveloper.entertainment.util;

import de.goldendeveloper.entertainment.Main;
import de.goldendeveloper.mysql.entities.Row;
import de.goldendeveloper.mysql.entities.Table;
import org.jetbrains.annotations.NotNull;

public class Movie {

    public Movie(@NotNull Table table) {
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "DRACHENZÄHMEN LEICHT GEMACHT 1"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "DRACHENZÄHMEN LEICHT GEMACHT 2"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "DRACHENZÄHMEN LEICHT GEMACHT 3"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "AQUAMAN"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Harry Potter und der Stein der Weisen"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Harry Potter und der Orden des Phönix"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Harry Potter und der Gefangene von Askaban"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Harry Potter und die Heiligtümer des Todes Teil 1"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Harry Potter und die Heiligtümer des Todes Teil 2"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Harry Potter und die Kammer des Schreckens "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Harry Potter und der Halbblutprinz"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "DEADPOOL"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "DEADPOOL 2"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "BLACK PANTHER"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "EXTREME RAGE"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "XXX 3: DIE RÜCKKEHR DES XANDER CAGE"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "XXX - TRIPLE X"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "XXX² - THE NEXT LEVEL"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "SKYSCRAPER"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "96 HOURS"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "96 HOURS - TAKEN 2"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "96 HOURS - TAKEN 3"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "AFTER EARTH"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "ALADDIN"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "ARTHUR UND DIE MINIMOYS 1"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "ARTHUR UND DIE MINIMOYS 2"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "ARTHUR UND DIE MINIMOYS 3"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "ALITA: BATTLE ANGEL"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "ALVIN UND DIE CHIPMUNKS"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "ANGEL HAS FALLEN"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "BRIGHT"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "BUMBLEBEE"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "BOB, DER STREUNER"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "BLOODSHOT"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "BLINKY BILL - DAS MEER DER WEISSEN DRACHEN"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "ANT-MAN"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "ANT-MAN AND THE WASP"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "RAYA UND DER LETZTE DRACHE"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "ARLO & SPOT"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "BAD BOYS"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "BAD BOYS FOR LIFE"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "BAYMAX - RIESIGES ROBOWABOHU"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "BAYWATCH"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "BEE MOVIE - DAS HONIGKOMPLOTT"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "BARBIE IN SCHWANENSEE "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "BARBIE IN: DIE SUPER-PRINZESSIN"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "BARBIE IN DER NUSSKNACKER"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "BARBIE ALS RAPUNZEL"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "ASTERIX BEI DEN OLYMPISCHEN SPIELEN"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "AVATAR AUFBRUCH NACH PANDORA"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "AVENGERS ENDGAME"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "AVENGERS 3: INFINITY WAR"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "ARTEMIS FOWL"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "ATLANTIS - DIE RÜCKKEHR"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "AB DURCH DIE HECKE"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Frozen"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "DIE EISKÖNIGIN 2"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Vaiana"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Rapunzel"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Karate kid"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "PHANTASTISCHE TIERWESEN UND WO SIE ZU FINDEN SIND"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "PHANTASTISCHE TIERWESEN - GRINDELWALDS VERBRECHEN"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "ZOOMANIA"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Merlin"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Shrek"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Tarzan"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Die fantastische Welt von Oz"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Monster High"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "CAPTAIN AMERICA: THE FIRST AVENGER"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "CAPTAIN AMERICA 2: THE RETURN OF THE FIRST AVENGER"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "CAPTAIN MARVEL"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "CARS"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "CARS 2"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "CARS 3: EVOLUTION"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "CHAPPIE"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "CHARLIE UND DIE SCHOKOLADENFABRIK "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "CROCODILE DUNDEE"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "CROCODILE DUNDEE II"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "CROCODILE DUNDEE IN LOS ANGELES"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "DADDY OHNE PLAN"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "DAS HAUS DER GEHEIMNISVOLLEN UHREN"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "DAS VERMÄCHTNIS DER TEMPELRITTER"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "DAS VERMÄCHTNIS DES GEHEIMEN BUCHES"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "DAS VERSCHOLLENE MEDAILLON"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "DER HERR DER RINGE - DIE GEFÄHRTEN"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "DER HERR DER RINGE - DIE RÜCKKEHR DES KÖNIGS"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "DER HERR DER RINGE - DIE ZWEI TÜRME"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "DER HOBBIT - DIE SCHLACHT DER FÜNF HEERE"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "DER HOBBIT EINE UNERWARTETE REISE"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "DER HOBBIT: SMAUGS EINÖDE"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "DER KAUFHAUS COP"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "DER KAUFHAUS COP 2"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "DER KNASTCOACH"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "DER KÖNIG DER LÖWEN"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "DER PLANET DER AFFEN: PREVOLUTION"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "DER POLAREXPRESS"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "DER PRINZ AUS ZAMUNDA"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "DER SPION VON NEBENAN"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "DESCENDANTS - DIE NACHKOMMEN"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "DESCENDANTS 2"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "DESCENDANTS 3 - DIE NACHKOMMEN"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "DESCENDANTS 3 - DIE NACHKOMMEN"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "DIE BESTIMMUNG - ALLEGIANT PART 1"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "DIE BESTIMMUNG - DIVERGENT"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "DIE BIENE MAJA - DER FILM"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "DIE CHRONIKEN VON NARNIA - PRINZ KASPIAN VON NARNIA"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "DIE CHRONIKEN VON NARNIA: DER KÖNIG VON NARNIA"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "DIE CHRONIKEN VON NARNIA: DIE REISE AUF DER MORGENRÖTE"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "DIE CROODS"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "DIE FANTASTISCHE REISE DES DR. DOLITTLE"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "DIE HÜTER DES LICHTS"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "DIE PEANUTS - DER FILM"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "DIE PINGUINE AUS MADAGASCAR"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "DIE SCHLÜMPFE"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "DIE SCHLÜMPFE 2"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "DIE SCHLÜMPFE 3 - DAS VERLORENE DORF"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "DIE SCHÖNE UND DAS BIEST"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "DIE TRIBUTE VON PANEM - CATCHING FIRE"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "DIE TRIBUTE VON PANEM - THE HUNGER GAMES"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "DIE TRIBUTE VON PANEM - MOCKINGJAY: TEIL 1"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "DIE TRIBUTE VON PANEM - MOCKINGJAY: TEIL 2"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "DIE UNFASSBAREN - NOW YOU SEE ME"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "DIE UNFASSBAREN 2"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "DIE UNGLAUBLICHEN 2"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "DOCTOR STRANGE"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "DORA UND DIE GOLDENE STADT"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "DRAGONBALL EVOLUTION"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "DUMBO"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "THE DEATH OF SUPERMAN"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "MISSION: IMPOSSIBLE - FALLOUT"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "MISSION: IMPOSSIBLE - ROGUE NATION"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "MISSION: IMPOSSIBLE - 2"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "MISSION: IMPOSSIBLE - 3"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "MISSION: IMPOSSIBLE - PHANTOM PROTOKOLL "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "PACIFIC RIM 2: UPRISING"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "PRINCE OF PERSIA - DER SAND DER ZEIT"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "PREDATORS"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "PRAKTI.COM"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "POWER RANGERS"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "POKEMON MEISTERDETEKTIV PIKACHU"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "PIXELS"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "PETS"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "PETS 2"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "PETER HASE"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "PERCY JACKSON - DIEBE IM OLYMP"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "PERCY JACKSON - IM BANN DES ZYKLOPEN"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "PASSENGERS"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "PARKER"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "PAN"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "PACIFIC RIM"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "ONWARD: KEINE HALBEN SACHEN"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "OBEN"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "NACHTS IM MUSEUM"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "NACHTS IM MUSEUM 2"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "NACHTS IM MUSEUM - DAS GEHEIMNISVOLLE GRABMAL"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "MORTAL ENGINES KRIEG DER STÄDTE"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "MONSTERS VS. ALIENS"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "MONSTER TRUCKS"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "MOGLI: LEGENDE DES DSCHUNGELS"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "MINIONS"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "MERIDA - LEGENDE DER HIGHLANDS"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "MENSCH, DAVE!"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "MEN IN BLACK: INTERNATIONAL"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "MEN IN BLACK"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "MEN IN BLACK II"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "MEN IN BLACK 3"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "MAZE RUNNER 3: DIE AUSERWÄHLTEN IN DER TODESZONE"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "MAZE RUNNER 2 - DIE AUSERWÄHLTEN IN DER BRANDWÜSTE"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "MAZE RUNNER - DIE AUSERWÄHLTEN IM LABYRINTH"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "MAX STEEL"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "MATRIX"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "MATRIX RELOADED"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "MATRIX REVOLUTIONS"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "MARVELS THE AVENGERS"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "MARVELS THE AVENGERS 2: AGE OF ULTRON"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "MAN OF STEEL"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "MALEFICENT - DIE DUNKLE FEE"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "MALEFICENT 2: MÄCHTE DER FINSTERNIS"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "MADAGASCAR"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "MADAGASCAR 2 "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "MADAGASCAR 3 - FLUCHT DURCH EUROPA"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "MAD MAX: FURY ROAD"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "LUCY"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "LUCAS, DER AMEISENSCHRECK"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "LONDON HAS FALLEN"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "LILO & STITCH"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "LILO & STITCH 2 - STITCH VÖLLIG ABGEDREHT"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "LETS BE COPS - DIE PARTY-BULLE"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "LEGION"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "LEGEND OF TARZAN"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "LEAGUE OF GODS"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "LARA CROFT: TOMB RAIDER"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "KUNG FU YOGA - DER GOLDENE ARM DER GÖTTER"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "KUNG FU PANDA - DIE GEHEIMNISSE DER MEISTER"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "KUNG FU PANDA 2"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "KUNG FU PANDA 3"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "KUBO - DER TAPFERE SAMURAI"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "KINGSMAN 1: THE SECRET SERVICE"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "KINGSMAN 2: THE GOLDEN CIRCLE"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "KINGSMAN 3:"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "KINDSKÖPFE"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "KINDSKÖPFE 2"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "KINDERGARTEN COP 2"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "KICK-ASS"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "KICK-ASS 2"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "KHUMBA - DAS ZEBRA OHNE STREIFEN AM POPO"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "KEVIN - ALLEIN ZU HAUS"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "KEVIN - ALLEIN IN NEW YORK"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "KEINOHRHASE & ZWEIOHRKÜKEN"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "JUSTICE LEAGUE"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "JURASSIC WORLD"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "JUPITER ASCENDING"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "JUMANJI: WELCOME TO THE JUNGLE"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "JUMANJI: THE NEXT LEVEL"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "JOKER"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "JOHNNY ENGLISH - MAN LEBT NUR DREIMAL"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "JOHNNY ENGLISH "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "JIU JITSU"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "JIM KNOPF UND LUKAS DER LOKOMOTIVFÜHRER"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "JAMES BOND 007 - SPECTRE"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "JAMES BOND 007 - STIRB AN EINEM ANDEREN TAG"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "JAMES BOND 007 - SKYFALL"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "JAMES BOND 007 - CASINO ROYALE"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "JAGDFIEBER 1"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "JAGDFIEBER 2"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "JAGDFIEBER 3"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "JAGDFIEBER 4 - UNGEBETENE BESUCHER"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "JAGD AUF DEN SCHATZ DER RIESEN"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "JACK REACHER - DIE JAGD HAT BEGONNEN!"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "JACK REACHER - 2: KEIN WEG ZURÜCK"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "IRON MAN 1"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "IRON MAN 2"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "IRON MAN 3"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "INSIDE OUT - ALLES STEHT KOPF"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "INDIANA JONES UND DER TEMPEL DES TODES"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "INDIANA JONES UND DER LETZTE KREUZZUG"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "INDIANA JONES UND DAS KÖNIGREICH DES KRISTALLSCHÄDEL"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "INDIANA JONES - JÄGER DES VERLORENEN SCHATZES"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "INDEPENDENTS DAY 1"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "INDEPENDENCE DAY 2: WIEDERKEHR "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "IMMORTAL WARS - NUR DER STÄRKSTE ÜBERLEBT"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "ICH BIN NUMMER 4"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "ICH - EINFACH UNVERBESSERLICH 1"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "ICH - EINFACH UNVERBESSERLICH 2"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "ICH - EINFACH UNVERBESSERLICH 3"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "ICE AGE 1"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "ICE AGE 2"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "ICE AGE 3"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "ICE AGE 4 - VOLL VERSCHOBEN"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "ICE AGE 5 - KOLLISION VORAUS!"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "I, ROBOT"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "HÜTER DER ERINNERUNG - THE GIVER "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "HULK"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "HUI BUH, DAS SCHLOSSGESPENST"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "HOTEL TRANSSILVANIEN 1"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "HOTEL TRANSSILVANIEN 2"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "HOTEL TRANSSILVANIEN 3 - EIN MONSTER URLAUB (2018)"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "HOTEL TRANSSILVANIEN 4"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "HITMAN - AGENT 47"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "HIGH SCHOOL MUSICAL 1:"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "HIGH SCHOOL MUSICAL 2: SINGT ALLE ODER KEINER! (2007)"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "HIGH SCHOOL MUSICAL 3: SENIOR YEAR (2008)"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "HERCULES"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "HAPPY FEET"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "HANCOCK"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "GUARDIANS OF THE GALAXY"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "GUARDIANS OF THE GALAXY VOL. 2"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "GREEN LANTERN"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "GODZILLA 2 KING OF THE MONSTERS "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "GODS OF EGYPT "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "GOD OF WAR"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "GNOMEO UND JULIA"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "GHOST RIDER: SPIRIT OF VENGEANCE"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "GEMINI MAN"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "GARFIELD - FETT IM LEBEN"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "GARFIELD - TIERISCHE HELDEN"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "FÜNF FREUNDE UND DAS TAL DER DINOSAURIER (2018)"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "FÜNF FREUNDE 3"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "FÜNF FREUNDE 4"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "FREUNDE MIT GEWISSEN VORZÜGEN "));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "FLUCH DER KARIBIK"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "FLUCH DER KARIBIK 2"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "FLUCH DER KARIBIK 3 - AM ENDE DER WELT (2007)"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "FLUCH DER KARIBIK 4 - FREMDE GEZEITEN (2011)"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "FLUCH DER KARIBIK SALAZARS RACHE"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "FINDET DORIE"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "FERDINAND - GEHT STIERISCH AB"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "FASTER"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "FAST & FURIOUS: NEUES MODELL. ORIGINALTEILE (2009)"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "FAST & FURIOUS FIVE"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "FAST & FURIOUS 6"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "FAST AND FURIOUS 7"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "FAST & FURIOUS 8"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "FAST & FURIOUS PRESENTS: HOBBS & SHAW (2019)"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "FANTASTIC FOUR"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "FANTASTIC FOUR - RISE OF THE SILVER SURFER (2007)"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "FACK JU GÖHTE"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "FACK JU GÖHTE 2"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "FACK JU GÖHTE 3"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Final Destination 5"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "EXODUS - GÖTTER UND KÖNIGE"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "ESPEN UND DIE LEGENDE VOM BERGKÖNIG (2017)"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "EMOJI - DER FILM"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "ELLIOT, DER DRACHE"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "LEG DICH NICHT MIT ZOHAN AN"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "17 Again"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "The last witch Hunter"));
    }
}
