package de.goldendeveloper.entertainment.util;

import de.goldendeveloper.entertainment.Main;
import de.goldendeveloper.mysql.entities.Row;
import de.goldendeveloper.mysql.entities.Table;
import org.jetbrains.annotations.NotNull;

public class Serie {

    public Serie(@NotNull Table table) {
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "The Bodyguard"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Mac Gyver (2016)"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "The Witcher"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Blindspot"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Scorpion"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "The Mandalorian"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Mia and Me"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Der kleine Prinz"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "PRODIGAL SON"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "MARVELS IRON FIST"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "LUCIFER"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "LOST IN SPACE"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "LETHAL WEAPON"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "HAWAII FIVE-0"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Young Sheldon"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Forever"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "American Dragon"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Arrow"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Beforeigners"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Black Lightning"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Blood and Treasure"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Bones - Die Knochenjägerin"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Bull"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Criminal Minds"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "CSI: Cyber"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "CSI: Den Tätern auf der Spur"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "CSI: Miami"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Blacklist"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Deception"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Doctor Who"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Einstein"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Supernatural"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "S.W.A.T"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Prison Break"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Ragnarök"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Orange Is the New Black"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Shadow and Bone"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Beck is Back"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Brooklyn 99"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Lupin"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Designated Survivor"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Die Oktonauten"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Warrior Nun"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "The Flash"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Travelers Die Reisenden"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "The Order"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "The 100"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Miraculous"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "DuckTales"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "My hero academia"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Seraph of the end"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Castle"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Supergirl"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "The Protector"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Another Life"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Die Reise nach Westen"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Peaky Blinders (Netflix)"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Atypical"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "The Crossing"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "The Witcher"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Loki"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "The Big Bang Theory"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Cursed die Auserwählte"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Arcane"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Das Buch von Boba Fett"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "The Falcon and the Winter Soldier"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Hawkeye"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "How i met your mother"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Brocklyn Nine-Nine"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Shadowhunters The Mortal Instruments"));
        table.insert(new Row(table, table.getDatabase()).with(Main.columnName, "Black Lagoon"));
    }
}
