package de._coho04_.discord.activity;

import de._Coho04_.mysql.entities.Database;
import de._Coho04_.mysql.entities.Row;
import de._Coho04_.mysql.entities.Table;

public class FillTableIfisEmpty {

    public static void fillSerienTable(Database db, Table table) {
        table.insert(new Row(table, db).with("name", "The Bodyguard"));
        table.insert(new Row(table, db).with("name", "Mac Gyver (2016)"));
        table.insert(new Row(table, db).with("name", "The Witcher"));
        table.insert(new Row(table, db).with("name", "Blindspot"));
        table.insert(new Row(table, db).with("name", "Scorpion"));
        table.insert(new Row(table, db).with("name", "The Mandalorian"));
        table.insert(new Row(table, db).with("name", "Mia and Me"));
        table.insert(new Row(table, db).with("name", "Der kleine Prinz"));
        table.insert(new Row(table, db).with("name", "PRODIGAL SON"));
        table.insert(new Row(table, db).with("name", "MARVELS IRON FIST"));
        table.insert(new Row(table, db).with("name", "LUCIFER"));
        table.insert(new Row(table, db).with("name", "LOST IN SPACE"));
        table.insert(new Row(table, db).with("name", "LETHAL WEAPON"));
        table.insert(new Row(table, db).with("name", "HAWAII FIVE-0"));
        table.insert(new Row(table, db).with("name", "Young Sheldon"));
        table.insert(new Row(table, db).with("name", "Forever"));
        table.insert(new Row(table, db).with("name", "Castel"));
    }

    public static void fillJokeTable(Database db, Table table) {
        table.insert(new Row(table, db).with("name", "Aus welchem Land kommen Schornsteinfeger? Aus Rußland!"));
        table.insert(new Row(table, db).with("name", "Axl Rose hat seiner nordfriesischen Freundin ein Liebeslied geschrieben: Sweet Child of Moin."));
        table.insert(new Row(table, db).with("name", "Beim Zahnarzt: 'Das kann jetzt ein bisschen weh tun.' - 'Kein Problem.' - 'Ich hab seit 3 Jahren ein Verhältnis mit Ihrer Frau.'"));
        table.insert(new Row(table, db).with("name", "Brennholzverleih."));
        table.insert(new Row(table, db).with("name", "Dem Reh fallen die Haare aus. Der Doktor weist es in eine Rehhaarklinik ein."));
        table.insert(new Row(table, db).with("name", "Der Erfinder des Post-It-Zettels ist gestorben. Die tröstliche Nachricht: Es gibt ein Kleben nach dem Tod."));
        table.insert(new Row(table, db).with("name", "Der Pfannkuchenbäcker ist an seinem eigenen Teig erstickt. Einfach crepiert."));
        table.insert(new Row(table, db).with("name", "Egal wie gut Du fährst, Züge fahren Güter."));
        table.insert(new Row(table, db).with("name", "Ein Besoffener beschimpft und beleidigt ein Helium. Und was macht es? Es reagiert nicht."));
        table.insert(new Row(table, db).with("name", "Ein Gockel bekommt eine Blasterpistole. Aus versehen bringt er damit alle Hühner um. Da ist der Hahn Solo."));
        table.insert(new Row(table, db).with("name", "Einbruch bei Adidas. Was schickt die Polizei? Drei Streifen."));
        table.insert(new Row(table, db).with("name", "Fliegt ein Kuckuck übers Meer. Grüßt ihn ein Hai:'Hi'"));
        table.insert(new Row(table, db).with("name", "Fragt der Polizist: Haben sie Restalkohol? - Nee, alles ausgetrunken."));
        table.insert(new Row(table, db).with("name", "Geben sich verliebte Anästhesisten eigentlich Narkosenamen?"));
        table.insert(new Row(table, db).with("name", "Gehen zwei Zahnstocher durch den Wald. Kommt ein Igel vorbei. Sagt der eine Zahnstocher: 'Ich wusste gar nicht, dass hier ein Bus fährt.'"));
        table.insert(new Row(table, db).with("name", "Geht ein Cowboy zum Friseur. Als er wieder rauskommt ist sein Pony weg."));
        table.insert(new Row(table, db).with("name", "Geht eine schwangere Frau zum Bäcker und sagt:'Ich bekomme ein Brot.'"));
        table.insert(new Row(table, db).with("name", "Huch, meine Uhr ist runter gefallen. Ich kann sie nicht aufheben. - Ich hab kein Uhrheberrecht."));
        table.insert(new Row(table, db).with("name", "Hüpft ein Rudel Gurken durch den Wald. Was ist falsch? Gurken sind keine Rudeltiere."));
        table.insert(new Row(table, db).with("name", "Ich bin so unentschlossen. Als japanischer Krieger wäre ich ein Nunja."));
        table.insert(new Row(table, db).with("name", "Ich brauche eine Krankschreibung? Was fehlt ihnen denn? Eine Krankschreibung."));
        table.insert(new Row(table, db).with("name", "Ich habe bei den Weight Watchers angerufen: Aber keine hat abgenommen."));
        table.insert(new Row(table, db).with("name", "Ich habe bei einem Brötchen angerufen, aber:War belegt."));
        table.insert(new Row(table, db).with("name", "Ich habe bei nem DJ angerufen:Der hat einfach aufgelegt."));
        table.insert(new Row(table, db).with("name", "Ich habe bei Spiderman angerufen, aber der hatte kein Netz."));
        table.insert(new Row(table, db).with("name", "Ich habe beim Arzt angerufen:Ich wurde aber nicht verbunden."));
        table.insert(new Row(table, db).with("name", "Ich habe beim Bäcker angerufen, da ging aber nur die Mehlbox ran."));
        table.insert(new Row(table, db).with("name", "Ich habe beim Metzger angerufen, aber kein Schwein ging ran."));
        table.insert(new Row(table, db).with("name", "Ich habe das Herz eines Löwen ...und lebenslanges Verbot im Leipziger Zoo."));
        table.insert(new Row(table, db).with("name", "Ich habe einem Hipster ans Schienbein getreten.Jetzt hopster."));
        table.insert(new Row(table, db).with("name", "Ich habe einen total lieben Hund, der ist so ruhig - der hat sogar den No -Bell preis gewonnen."));
        table.insert(new Row(table, db).with("name", "Ich habe in der Botschaft angerufen, aber keiner ging ran.War wohl Kanada."));
        table.insert(new Row(table, db).with("name", "Ich habe meiner Frau zu Weihnachten einen Nerz geschenkt und jetzt weigert sie sich, das Tier zufüttern."));
        table.insert(new Row(table, db).with("name", "Ich wollte einen Witz über die Deutsche Bahn machen, aber ich wusste nicht ob der ankommt."));
        table.insert(new Row(table, db).with("name", "Im Restaurant:Isst Du gerne wild?-Nein, ganz normal und langsam. "));
        table.insert(new Row(table, db).with("name", "In Mittelamerika gibt es kaum gute Tapezierer - aber dafür Guatemala !"));
        table.insert(new Row(table, db).with("name", "In St.Pauli wurde gestern ein Sarg gefunden.Aber der ging und ging nicht auf.War wohl ein Zuhälter drin ? "));
        table.insert(new Row(table, db).with("name", "In welchem Land ist man so langsam wie eine Schnecke ?In Kriechenland."));
        table.insert(new Row(table, db).with("name", "In welcher Maßeinheit messen Hunde ihre Temperatur ? In Belgrad. "));
        table.insert(new Row(table, db).with("name", "Klaus war echt nervig, deshalb bekam er nie frische Brötchen.Klaus störte Bäcker. "));
        table.insert(new Row(table, db).with("name", "Kommt ein Dachdecker in eine Bar. —Sagt der Wirt: 'Der geht aufs Haus.' "));
        table.insert(new Row(table, db).with("name", "Kommt ein Frosch in den Milchladen.Fragt die Verkäuferin: 'Was willst du denn?' - Sagt der Frosch:'Quak.' "));
        table.insert(new Row(table, db).with("name", "Kommt ein Igel in die Konditorei:'Einmal Rumkugeln bitte'-- Wenn sie wollen, wir haben gerade frisch gewischt."));
        table.insert(new Row(table, db).with("name", "Kommt ein Pferd in den Blumenladen:'Haben sie Mageriten?' (ma ' geritten)"));
        table.insert(new Row(table, db).with("name", "Mein Arzt hat eine südamerikanische Augenkrankheit bei mir diagnostiziert - ich 'Chile.'"));
        table.insert(new Row(table, db).with("name", "Mein Hund ein echter Charmeur.Immer wenn ich ihn fragt:Na wie sehe ich aus, sagt er: Wau !"));
        table.insert(new Row(table, db).with("name", "Mir ist kalt - ich geh mal in die Ecke.Da sind 90 Grad. "));
        table.insert(new Row(table, db).with("name", "Neulich im Tatort: Wo waren Sie zur Tatzeit ? -Im Internet !"));
        table.insert(new Row(table, db).with("name", "Papa, in Ägypten ist nächste Woche auch keine Schule !' -- ' Ok ? ' -- '' Ja, die haben da Sphinxferien !'"));
        table.insert(new Row(table, db).with("name", "Sagt der Pessimist: 'Schlimmer geht nicht!' - Sagt der Optimist:'Doch!'"));
        table.insert(new Row(table, db).with("name", "Sagt der Walfisch zum Tuhnfisch: 'Was wollen wir tun, Fisch?' Sagt der Thunfisch:'Du hast die Wahl, Fisch!' "));
        table.insert(new Row(table, db).with("name", "Sagt die eine Kerze zur anderen:Du, ist Wasser eigentlich gefährlich ? -Sagt die andere:Davon kannst Du ausgehen."));
        table.insert(new Row(table, db).with("name", "Sagt die eine Sicherung zur anderen:Lass uns zusammen durchbrennen !"));
        table.insert(new Row(table, db).with("name", "Sagt die eine Wand zur anderen Wand: Wir treffen uns an der Ecke."));
        table.insert(new Row(table, db).with("name", "Sagt die Erbse zur anderen: Vorsicht, da ist eine Trepepepepepepepepe..."));
        table.insert(new Row(table, db).with("name", "Schicke Unterwäsche !-Wohin ? "));
        table.insert(new Row(table, db).with("name", "Sprechstundenhilfe:' Warum tragen Sie eine Augenklappe ? ' 'Ich bin Piratpatient. '"));
        table.insert(new Row(table, db).with("name", "Steht ein Baum allein im Wald..."));
        table.insert(new Row(table, db).with("name", "Steht ein Pils im Wald.Kommt ein Hase und trinkt es aus.Und warum steht ein Pils im Wald ? Weil die Tannen zapfen."));
        table.insert(new Row(table, db).with("name", "Stelle dir zwei bayerisch getrachtet Personen vor, die die Daumen nach oben recken.In der anderen Hand Bier und Brezn.Was ist das ? Confirmation Bayers"));
        table.insert(new Row(table, db).with("name", "Stiftung Warentest hat Besteck getestet.Das Messer hat am besten abgeschnitten."));
        table.insert(new Row(table, db).with("name", "Tage an denen man plant, Bananen zu essen, nennt man Bananenplantage."));
        table.insert(new Row(table, db).with("name", "Tonic ohne Alkohol ist übrigens ginlos."));
        table.insert(new Row(table, db).with("name", "Treffen sich zwei Magneten:'Was zieh ich heute bloß an?'"));
        table.insert(new Row(table, db).with("name", "Unterhalten sich zwei Fliesenleger:'Wo sind denn die ganzen Fliesen hin?' 'Oh, die muss ich wohl verlegt haben.'"));
        table.insert(new Row(table, db).with("name", "Wann gehen U - Boote unter ? Am Tag der offenen Tür."));
        table.insert(new Row(table, db).with("name", "Warum darf das Neutron nicht in die Disco?Heute nur geladene Gäste !"));
        table.insert(new Row(table, db).with("name", "Warum findet ein Henker nie den Rückweg ? Weil der nur die Hinrichtung kennt. "));
        table.insert(new Row(table, db).with("name", "Warum fliegen Störche im Winter in den Süden?-Weil Laufen zu lange dauern würde. "));
        table.insert(new Row(table, db).with("name", "Warum gehen Ameisen am Sonntag nicht in die Kirche ? Weil Ameisen Insekten sind. "));
        table.insert(new Row(table, db).with("name", "Warum gibt es in Booten keinen Honig ? Weil es auf Schiffen ka -bienen gibt. "));
        table.insert(new Row(table, db).with("name", "Warum haben diese Fische so ausgesprochen gute Zähne ?Das sind Kariesprofilachse. "));
        table.insert(new Row(table, db).with("name", "Warum haben Fische Schuppen?Damit sie ihre Fahrräder unterstellen können."));
        table.insert(new Row(table, db).with("name", "Warum ist der Florist über seine Lieferung traurig?Sie ist eingegangen. "));
        table.insert(new Row(table, db).with("name", "Warum klaut Robin Hood Deo ? Um es unter den Armen zu verteilen !"));
        table.insert(new Row(table, db).with("name", "Warum können Seeräuber schlecht mit Kreisen Rechnen ? Weil sie Pi -Raten !"));
        table.insert(new Row(table, db).with("name", "Warum können Skelette so schlecht lügen ?Die sind so einfach zu durchschauen."));
        table.insert(new Row(table, db).with("name", "Warum leben Haie im Salzwasser ? Weil sie von Pfefferwasser niesen müssen. "));
        table.insert(new Row(table, db).with("name", "Warum muss die Spinne grillen ? Sie ist ein Weberknecht. "));
        table.insert(new Row(table, db).with("name", "Warum sind bei IKEA Pfeile am Boden ? Weil es ein Einrichtungshaus ist."));
        table.insert(new Row(table, db).with("name", "Warum sind Fußballer eine Gefahr im Straßenverkehr ? Weil sie bei rot gehen müssen. "));
        table.insert(new Row(table, db).with("name", "Warum steht die Freiheitsstatue in New York ? Weil sie sich nicht setzen kann. "));
        table.insert(new Row(table, db).with("name", "Warum summen Bienen ? Weil sie den Text nicht kennen. "));
        table.insert(new Row(table, db).with("name", "Warum wachsen auf dem Mond keine Blumen ? Zu wenig Erde."));
        table.insert(new Row(table, db).with("name", "Was bekommt ein Kannibale, der zu spät zum Essen kommt ? Die kalte Schulter."));
        table.insert(new Row(table, db).with("name", "Was benutzt ein Bär als Eingabegerät?Eine Tatzatur."));
        table.insert(new Row(table, db).with("name", "Was bestellt ein Maulwurf im Restaurant? —Ein Drei -Gänge - Menü. "));
        table.insert(new Row(table, db).with("name", "Was denken sich die Gletscher zum Klimawandel ? Wir werden Seen."));
        table.insert(new Row(table, db).with("name", "Was erzählen sich holländische Süßspeisen am liebsten ? Vla - chwitze. "));
        table.insert(new Row(table, db).with("name", "Was erzählt Weizen sich gegenseitig beim Campen ? Grieselgeschichten. "));
        table.insert(new Row(table, db).with("name", "Was essen Autos am liebsten ? —Parkplätzchen. "));
        table.insert(new Row(table, db).with("name", "Was essen Piraten am liebsten ? —Kapern. "));
        table.insert(new Row(table, db).with("name", "Was findet man beim Kannibalen in der Dusche ? —Head and Shoulders. "));
        table.insert(new Row(table, db).with("name", "Was freut sich und stinkt ? -Das Gefurztagskind. "));
        table.insert(new Row(table, db).with("name", "Was für ein Gefühl hatte Mozart beim Komponieren ?Einen Haydn -Spaß. "));
        table.insert(new Row(table, db).with("name", "Was gibt es bei Olympia—Teilnehmern zum Nachtisch ? —Fackelpudding !"));
        table.insert(new Row(table, db).with("name", "Was gräbt und ist aus der Puste ? Eine Schnaufel. "));
        table.insert(new Row(table, db).with("name", "Was hat acht Arme und fliegt durchs Weltall?Eine Krakete."));
        table.insert(new Row(table, db).with("name", "Was hat acht Beine und schummelt?Eine Mogelspinne."));
        table.insert(new Row(table, db).with("name", "Was hat ein Mann, der im Dreieck läuft ? Kreislaufprobleme. "));
        table.insert(new Row(table, db).with("name", "Was hat einen Beutel und schießt ?Ein Penguruh."));
        table.insert(new Row(table, db).with("name", "Was hat Haare und wird gebraten ?Bartkartoffeln. "));
        table.insert(new Row(table, db).with("name", "Was hoppelt über die Wiese und raucht aus den Ohren ?Ein Kaminchen."));
        table.insert(new Row(table, db).with("name", "Was isst eine Sadomaso Frau vor Weihnachten ? Domina - Steine. "));
        table.insert(new Row(table, db).with("name", "Was isst Familie Biber zu abend ?Tischstäbchen. "));
        table.insert(new Row(table, db).with("name", "Was ist braun und hilft dir, wenn du traurig bist ? Ein Trost - brot. "));
        table.insert(new Row(table, db).with("name", "Was ist braun und hängt mit nem Warndreieck im Baum ?Ein Pannenzapfen."));
        table.insert(new Row(table, db).with("name", "Was ist braun und schwimmt unter Wasser ? Ein U - Brot. "));
        table.insert(new Row(table, db).with("name", "Was ist braun, kann fliegen und macht Kindern die Zähne kaputt ? -Die Toffi - Fee !"));
        table.insert(new Row(table, db).with("name", "Was ist braun, lebt im Nil und schmeckt lecker ? Ein Schokodil. "));
        table.insert(new Row(table, db).with("name", "Was ist braun, lecker und gesund?Schogolade. "));
        table.insert(new Row(table, db).with("name", "Was ist bunt und will dringend aus dem Zimmer raus ?Ein Fluchtsalat."));
        table.insert(new Row(table, db).with("name", "Was ist bunt, leuchtet und kann nicht schwimmen?ein Bagger mit Lichterkette."));
        table.insert(new Row(table, db).with("name", "Was ist bunt, süß und ein bisschen einfach gestrickt ? Ein Dummibärchen."));
        table.insert(new Row(table, db).with("name", "Was ist das agressivste Milchprodukt?Schlagsahne."));
        table.insert(new Row(table, db).with("name", "Was ist das Gegenteil von Japan ? Neinpan."));
        table.insert(new Row(table, db).with("name", "Was ist das Wichtigste an den Elefanten?Das zweite E, sonst wären es nur 11 Anten. (bayerisch vorgelesen)"));
        table.insert(new Row(table, db).with("name", "Was ist der unförmigste Seevogel von Nordfriesland ? Die Amöve."));
        table.insert(new Row(table, db).with("name", "Was ist die größte Anerkennung unter Aquarellisten ? 'Verläuft bei Dir!'"));
        table.insert(new Row(table, db).with("name", "Was ist durchsichtig, stinkt und ignorant? Ein Schnurz."));
        table.insert(new Row(table, db).with("name", "Was ist ein Cowboy ohne Pferd? Ein Sattelschlepper."));
        table.insert(new Row(table, db).with("name", "Was ist ein Keks unter einem Baum? Ein schattiges Plätzchen."));
        table.insert(new Row(table, db).with("name", "Was ist ein nackter Ritter? Ent - rüstet!"));
        table.insert(new Row(table, db).with("name", "Was ist eine Glühbirne, die schockiert zu Boden fällt?Fassungslos!"));
        table.insert(new Row(table, db).with("name", "Was ist eine Kastanie hinter Gittern? Eine Knastanie."));
        table.insert(new Row(table, db).with("name", "Was ist gelb und flattert im Wind? Eine Fahnane."));
        table.insert(new Row(table, db).with("name", "Was ist gelb und hüpft durch den Wald?Ein Postfrosch."));
        table.insert(new Row(table, db).with("name", "Was ist gelb und kann nicht schwimmen ? Ein Bagger. Und warum? Weil er nur einen Arm hat."));
        table.insert(new Row(table, db).with("name", "Was ist gelb und läuft den Baum hoch?Ein Posthörnchen."));
        table.insert(new Row(table, db).with("name", "Was ist gelb und schießt ? Eine Banone."));
        table.insert(new Row(table, db).with("name", "Was ist gelb und schwimmt über 'n See? Eine Schwanane."));
        table.insert(new Row(table, db).with("name", "Was ist gelb und steht am Fenster ? -Eine Spannanas."));
        table.insert(new Row(table, db).with("name", "Was ist gesund, kräftig und spielt den beleidigten?Das andere Schmollkornbrot."));
        table.insert(new Row(table, db).with("name", "Was ist groß, braun und schreibt undeutlich ? Ein Kritz - li - bär."));
        table.insert(new Row(table, db).with("name", "Was ist groß, grau und interessiert niemanden ? Ein Irrelephant."));
        table.insert(new Row(table, db).with("name", "Was ist groß, grau und ruft gleich an?Ein Telefant."));
        table.insert(new Row(table, db).with("name", "Was ist grün und fliegt durchs Weltall? Ein Salatelit."));
        table.insert(new Row(table, db).with("name", "Was ist grün und fährt Pandabären zur Arbeit ? Ein Bam - bus."));
        table.insert(new Row(table, db).with("name", "Was ist grün und gewinnt jedes Rennen?Ein Schnellerie."));
        table.insert(new Row(table, db).with("name", "Was ist grün und hüpft durch den Wald?Ein Rudel Gurken."));
        table.insert(new Row(table, db).with("name", "Was ist grün und liegt im Sarg?Eine Sterbse."));
        table.insert(new Row(table, db).with("name", "Was ist grün und macht die Toilette sauber?Ein Klokodil."));
        table.insert(new Row(table, db).with("name", "Was ist grün und schnarcht am Wegesrand ? Eine Pennnessel."));
        table.insert(new Row(table, db).with("name", "Was ist grün und sitzt auf dem Klo ? Der Kacktus."));
        table.insert(new Row(table, db).with("name", "Was ist grün und tut weh, wenn man es ins Auge kriegt ? Ein Billardtisch."));
        table.insert(new Row(table, db).with("name", "Was ist grün und will dringend ins Zimmer ? Ein Klopfsalat."));
        table.insert(new Row(table, db).with("name", "Was ist grün, blind und kann singen ? Kiwi Wonder."));
        table.insert(new Row(table, db).with("name", "Was ist grün, hängt an der Türklinke und guckt durchs Schlüsselloch ? Ein Spionat."));
        table.insert(new Row(table, db).with("name", "Was ist grün, sauer und versteckt sich vor der Polizei ? Ein Essig - Schurke."));
        table.insert(new Row(table, db).with("name", "Was ist grün, schlau und stellt viele Fragen ? -Günther Lauch."));
        table.insert(new Row(table, db).with("name", "Was ist grün, sitzt auf einem Baum und wenn es runterfällt bist Du verletzt ? Ein Billiardtisch."));
        table.insert(new Row(table, db).with("name", "Was ist grün, springt durchs Gras und ist super happy ? Eine Freuschrecke. "));
        table.insert(new Row(table, db).with("name", "Was ist heiß und flauschig ? Eine Fellkartoffel. "));
        table.insert(new Row(table, db).with("name", "Was ist klein und schwarz und dreht sich auf der Wiese ? Ein Maulwurf beim Hammerwerfen. "));
        table.insert(new Row(table, db).with("name", "Was ist klein, glitschig und immer schlecht gelaunt?Eine Maulquappe."));
        table.insert(new Row(table, db).with("name", "Was ist langsam, wird steinalt und macht einen Riesenlärm ? Eine Schildtröte. "));
        table.insert(new Row(table, db).with("name", "Was ist lila und bedient im Restaurant ? Eine Obergine. "));
        table.insert(new Row(table, db).with("name", "Was ist lässig und hat einen Euter ? Eine Kuhl. "));
        table.insert(new Row(table, db).with("name", "Was ist orange und kann nicht still sitzen ?Eine Zappelsine."));
        table.insert(new Row(table, db).with("name", "Was ist orange und läuft durch die Berge ?Eine Wandarine."));
        table.insert(new Row(table, db).with("name", "Was ist rot und schlecht für die Zähne ?Ein Ziegelstein."));
        table.insert(new Row(table, db).with("name", "Was ist rot und steht im Wald ? Ein Kirsch. "));
        table.insert(new Row(table, db).with("name", "Was ist rot und wiehert ? Eine Pferdbeere. "));
        table.insert(new Row(table, db).with("name", "Was ist rot, rund und sitzt auf dem Klo ? Eine Klomate. "));
        table.insert(new Row(table, db).with("name", "Was ist schwarz, rot und lebt in der Arktis ? Ein Pinguin mit Sonnenbrand. "));
        table.insert(new Row(table, db).with("name", "Was ist schwarz - weiß und 50 cm in der Luft?Ein Schwebra."));
        table.insert(new Row(table, db).with("name", "Was ist schwarz - weiß und explodiert?Ein Sprenguin."));
        table.insert(new Row(table, db).with("name", "Was ist schwarz - weiß und hüpft auf und ab ? Ein Springuin. "));
        table.insert(new Row(table, db).with("name", "Was ist schwarz - weiß und sitzt auf der Schaukel ? Ein Schwinguin. "));
        table.insert(new Row(table, db).with("name", "Was ist süß und schwingt sich von Torte zu Torte ?Tarzipan. "));
        table.insert(new Row(table, db).with("name", "Was ist süß, klebrig und geht durch die Wüste ? Ein Karamel. "));
        table.insert(new Row(table, db).with("name", "Was ist unter der Erde und stinkt ? Eine Furzel. "));
        table.insert(new Row(table, db).with("name", "Was ist schwarz - weiß und 50 cm in der Luft?Ein Schwebra."));
        table.insert(new Row(table, db).with("name", "Was ist weiß und fliegt durch den Wald?Biene Mayo."));
        table.insert(new Row(table, db).with("name", "Was ist weiß und guckt durchs Schlüsselloch ? —Ein Spannbettlaken."));
        table.insert(new Row(table, db).with("name", "Was ist weiß und rennt den Berg wieder hoch ? Eine Lawine mit Heimweh. "));
        table.insert(new Row(table, db).with("name", "Was ist weiß und schnarcht auf der Wiese ?Ein Schlaf."));
        table.insert(new Row(table, db).with("name", "Was ist weiß und springt von Baum zu Baum ? Ein Tierarzt bei der Zeckenimpfung."));
        table.insert(new Row(table, db).with("name", "Was ist weiß und stört beim Essen ? Eine Lawine. "));
        table.insert(new Row(table, db).with("name", "Was ist weiß und tanz im Wald ums Feuer ? Rumpelpilzchen. "));
        table.insert(new Row(table, db).with("name", "Was ist wohlhabend und springt von Ast zu Ast ? Ein Scheichhörnchen. "));
        table.insert(new Row(table, db).with("name", "Was kauft ein Mann mit zwei linken Füßen im Schuhgeschäft?Flip Flips."));
        table.insert(new Row(table, db).with("name", "Was kommt aufs Brot und schmeckt nach Kleister?Kleberwurst. "));
        table.insert(new Row(table, db).with("name", "Was lebt in der Savanne und ist immer sauber ? Eine Hygiäne. "));
        table.insert(new Row(table, db).with("name", "Was liegt am Strand und kann man nicht gut verstehen und ist auch noch erkältet ? Eine Niesnuschel. "));
        table.insert(new Row(table, db).with("name", "Was liegt am Strand und kann man nicht gut verstehen ?Eine Nuschel."));
        table.insert(new Row(table, db).with("name", "Was machen PiratInnen, wenn Sie nicht mehr weiterwissen?Einen Arrrrrrrbeitskreis."));
        table.insert(new Row(table, db).with("name", "Was machen Tiere in der Disko?Sie diskotieren."));
        table.insert(new Row(table, db).with("name", "Was machen zwei Bäume, wenn sie einen trinken wollen?Sie gehen in ihre Stammkneipe. "));
        table.insert(new Row(table, db).with("name", "Was machen zwei wütende Schafe ? Sie bekommen sich in die Wolle. "));
        table.insert(new Row(table, db).with("name", "Was macht der Mathematiker beim Skifahren?Er rechnet mit Brüchen."));
        table.insert(new Row(table, db).with("name", "Was macht der Ostfriese wenn er zu Hause mehr elektrische Anschlussleistung braucht?Er geht mit dem Eimer raus und holt sich ein paar Kilo Watt. "));
        table.insert(new Row(table, db).with("name", "Was macht ein arbeitsloser Schauspieler ? Spielt keine Rolle."));
        table.insert(new Row(table, db).with("name", "Was macht ein Clown im Büro ?Faxen. "));
        table.insert(new Row(table, db).with("name", "Was macht ein schwuler Wurm im Salat ? -Er schmeißt die Schnecken raus."));
        table.insert(new Row(table, db).with("name", "Was macht eine Bombe im Bordell? —Puff. "));
        table.insert(new Row(table, db).with("name", "Was macht eine Bombe im Treppenhaus ?Hochgehen. "));
        table.insert(new Row(table, db).with("name", "Was macht eine Ente auf dem Router ? Nat. "));
        table.insert(new Row(table, db).with("name", "Was macht man mit einem Hund ohne Beine ?Um die Häuser ziehen."));
        table.insert(new Row(table, db).with("name", "Was passiert wenn man Cola und Bier gleichzeitig trinkt ? —Man colabiert."));
        table.insert(new Row(table, db).with("name", "Was piekst und fliest das Bad?Ein Kachelschwein."));
        table.insert(new Row(table, db).with("name", "Was sagt der frustrierte Origami - Lehrer zu seinem Schüler ? Kannste knicken !"));
        table.insert(new Row(table, db).with("name", "Was sagt der Fuchs im Hühnerstall ?Raus aus den Federn !"));
        table.insert(new Row(table, db).with("name", "Was sagt der große Stift zum kleinen Stift ?Wachs - mal - Stift. "));
        table.insert(new Row(table, db).with("name", "Was sagt der Holzwurmpapa abends zu seinen Kindern ?Husch, husch ab ins Brettchen. "));
        table.insert(new Row(table, db).with("name", "Was sagt der Teig bei der Hochzeit ? Ich bin ganz gerührt !"));
        table.insert(new Row(table, db).with("name", "Was sagt ein Ackerbesteller bei gutem Wetter ? Das Land - wird. "));
        table.insert(new Row(table, db).with("name", "Was sagt ein Gen, wenn es ein anderes trifft?-Halogen. "));
        table.insert(new Row(table, db).with("name", "Was sagt ein Pirat im Pferdestall ?A, Heu. "));
        table.insert(new Row(table, db).with("name", "Was schwimmt auf dem Teich und fängt mit Z an ?Zwei Enten."));
        table.insert(new Row(table, db).with("name", "Was schwimmt im Meer und addiert ?Ein Oktoplus."));
        table.insert(new Row(table, db).with("name", "Was sind die teuersten Tomaten ? Die Geldautomaten. "));
        table.insert(new Row(table, db).with("name", "Was sitzt am Frühstückstisch und winkt?Ein Grüsli."));
        table.insert(new Row(table, db).with("name", "Was sitzt auf dem Baum und schreit 'Aha!' - Ein Uhu mit Sprachfehler. "));
        table.insert(new Row(table, db).with("name", "Was sitzt auf dem Turm und macht alle 15 Minuten Schuhu?Der Turmuhur."));
        table.insert(new Row(table, db).with("name", "Was sitzt auf einem Baum und winkt ? —Ein Huhu !"));
        table.insert(new Row(table, db).with("name", "Was sitzt ganz hinten im Brotkasten und ist beleidigt ? Ein Schmollkornbrot. "));
        table.insert(new Row(table, db).with("name", "Was sitzt im Baum und weint?Eine Heule !"));
        table.insert(new Row(table, db).with("name", "Was steht auf dem Herd und ist total geheim ? Ein Topf Secret !"));
        table.insert(new Row(table, db).with("name", "Was steht Weihnachten im Wohnzimmer und ist kaputt ?Ein Pannenbaum."));
        table.insert(new Row(table, db).with("name", "Was studiert man für einen Führerschein ?Fahr - ma - kologie. "));
        table.insert(new Row(table, db).with("name", "Was wird oft übersehen ?Ein Gartenzaun."));
        table.insert(new Row(table, db).with("name", "Welche Fische haben die beste Mundhygiene ?Die Zahnprophylachse."));
        table.insert(new Row(table, db).with("name", "Welche Handwerker essen am meisten ? Maurer, die verputzen ganze Häuser. "));
        table.insert(new Row(table, db).with("name", "Welche Schuhe tragen Raubfische sehr gern ?Hai - Heels. "));
        table.insert(new Row(table, db).with("name", "Welche Weinsorte wächst am Fuße des Vesuvs ? Glühwein. "));
        table.insert(new Row(table, db).with("name", "Welcher Fisch nervt im Unterricht ? Na der Stör !"));
        table.insert(new Row(table, db).with("name", "Welches Gemüse serviert sich selbst ? Die Obergine. "));
        table.insert(new Row(table, db).with("name", "Welches Getränk trinken Firmenchefs?Leitungswasser. "));
        table.insert(new Row(table, db).with("name", "Welches ist die lustigste Automarke ? Scherzedes. "));
        table.insert(new Row(table, db).with("name", "Welches Maultier sitzt in der Bar und trink Cappuccino ? Das Cafémel. "));
        table.insert(new Row(table, db).with("name", "Welches Obst geht immer in die Kirche ? Die Frommbeere. "));
        table.insert(new Row(table, db).with("name", "Welches Tier badet gern in Tomaten, Basilikum und Olivenöl?Der Mozzarellensittich."));
        table.insert(new Row(table, db).with("name", "Welches Tier hält immer Maß ? Der Ellensittich. "));
        table.insert(new Row(table, db).with("name", "Welches Tier klebt gerne zwischen den Zähnen ? Der Karamellensittich. "));
        table.insert(new Row(table, db).with("name", "Welches Tier kümmert sich um Meeresbewohner, denen es nicht gut geht?Die Krakenschwester."));
        table.insert(new Row(table, db).with("name", "Welches Tier trägt Strapse und Korsett und ist auch sonst eher verrucht?Der Bordellensittich."));
        table.insert(new Row(table, db).with("name", "Wenn ein südamerikanisches Kameltier betrunken ist ...ist das dann ein Alkpaka ? "));
        table.insert(new Row(table, db).with("name", "Wenn eine Kapselkaffeemaschine das Zeitliche segnet, schlägt die Stunde des Senseomanns."));
        table.insert(new Row(table, db).with("name", "Wenn Nicolas Wöhrl sich ein Brötchen schmiert ...ist es dann wissenschaftlich belegt ? "));
        table.insert(new Row(table, db).with("name", "Wer ist bunt, flattert durch die Luft und hilft wo er nur kann ? Ein Retterling. "));
        table.insert(new Row(table, db).with("name", "Wer ist grün, kann zaubern und riecht streng?Stinkerbell. "));
        table.insert(new Row(table, db).with("name", "Wer kümmert sich um die Gräten der Meeresbewohner ?Der Oktopäde."));
        table.insert(new Row(table, db).with("name", "Wer mit Nüssen zahlt, darf sich nicht wundern, wenn Affen für ihn arbeiten."));
        table.insert(new Row(table, db).with("name", "Wer wohnt im Dschungel und schummelt?Mogli. "));
        table.insert(new Row(table, db).with("name", "Wie begrüßen sich Schönheitschirurgen ?Na was machst Du denn für ein Gesicht ?"));
        table.insert(new Row(table, db).with("name", "Wie berechnet eine Kuh die Fläche ihrer Weide ?--Mit der Muhtiplikation."));
        table.insert(new Row(table, db).with("name", "Wie heißt das intelligenteste Gemüse ? -Schlaubergine. "));
        table.insert(new Row(table, db).with("name", "Wie heißt der Tiger mit Vornamen ?-Schaumfes !"));
        table.insert(new Row(table, db).with("name", "Wie heißt ein Spanier ohne Auto ?Carlos. "));
        table.insert(new Row(table, db).with("name", "Wie kastriert man einen Kühlschrank ? Tür auf, Eier raus, Tür zu. "));
        table.insert(new Row(table, db).with("name", "Wie nennt man das Küchengerät dass dir heimlich die Süßigkeiten wegisst ? Die Spülnaschine. "));
        table.insert(new Row(table, db).with("name", "Wie nennt man das Oberteil von Meerjungfrauen ? Algebra. "));
        table.insert(new Row(table, db).with("name", "Wie nennt man den Flur eines Iglus ? Eisdiele !"));
        table.insert(new Row(table, db).with("name", "Wie nennt man den germanischen Gott der Ungeduld ?Hammersbald. "));
        table.insert(new Row(table, db).with("name", "Wie nennt man die Steigerung von Buchstabensuppe ? Wörtersee. "));
        table.insert(new Row(table, db).with("name", "Wie nennt man ein kleines schwäbisches Schwein, das um Hilfe ruft ? Ein Notrufsäule. "));
        table.insert(new Row(table, db).with("name", "Wie nennt man ein Monster mit Schnupfen ? Rotzilla. "));
        table.insert(new Row(table, db).with("name", "Wie nennt man ein Rudel aggressiver Wölfe ? Wolfgang. "));
        table.insert(new Row(table, db).with("name", "Wie nennt man ein verschwundenes Rindvieh ?-Oxford. "));
        table.insert(new Row(table, db).with("name", "Wie nennt man ein weißes Mammut ?Hell - mut !"));
        table.insert(new Row(table, db).with("name", "Wie nennt man ein tiefgefrorenes Mammut ?Hart - mut !"));
        table.insert(new Row(table, db).with("name", "Wie nennt man eine Biene, die diagonal fliegt?Eine Quersumme."));
        table.insert(new Row(table, db).with("name", "Wie nennt man eine Frucht, die ein großes Anwesen hat?--Eine Hektarine. "));
        table.insert(new Row(table, db).with("name", "Wie nennt man einen ausgehungerten Frosch ?Magerquark. "));
        table.insert(new Row(table, db).with("name", "Wie nennt man einen Bär der KungFu beherrscht ?Grizzly. "));
        table.insert(new Row(table, db).with("name", "Wie nennt man einen Ausserirdischen, der in der Informationstechnik arbeitet?Italien. "));
        table.insert(new Row(table, db).with("name", "Wie nennt man einen Bären der 'Granufink' braucht ? Ein Pullerbär. "));
        table.insert(new Row(table, db).with("name", "Wie nennt man einen Delfin mit einer Unterhose auf dem Kopf ? Slipper. "));
        table.insert(new Row(table, db).with("name", "Wie nennt man einen dicken Schriftsteller ?-Kugelschreiber !"));
        table.insert(new Row(table, db).with("name", "Wie nennt man einen dünnen Weihnachtsmann ?Nikolauch. "));
        table.insert(new Row(table, db).with("name", "Wie nennt man einen extrem dünnen Frosch ? Magerquak. "));
        table.insert(new Row(table, db).with("name", "Wie nennt man einen Gerd, der den Rasen mäht ? Gerd - ner. "));
        table.insert(new Row(table, db).with("name", "Wie nennt man einen Hering, der am Flughafen arbeitet ? Einen Zollmops. "));
        table.insert(new Row(table, db).with("name", "Wie nennt man einen Hering, der beleidigt ist?Einen Schmollmops."));
        table.insert(new Row(table, db).with("name", "Wie nennt man einen Hering, der die besten Memes postet?Einen Lolmops."));
        table.insert(new Row(table, db).with("name", "Wie nennt man einen Hering, der doofe Kommentare schreibt ? Einen Trollmops. "));
        table.insert(new Row(table, db).with("name", "Wie nennt man einen Hering, der gerne Atombombentests macht ? Einen Atollmops. "));
        table.insert(new Row(table, db).with("name", "Wie nennt man einen Hering, der gerne Befehle befolgt ? Einen Jawollmops. "));
        table.insert(new Row(table, db).with("name", "Wie nennt man einen Hering, der gerne Fußball mag ? Einen(Mehmet) Schollmops. "));
        table.insert(new Row(table, db).with("name", "Wie nennt man einen Hering, der gerne strickt?Einen Wollmops."));
        table.insert(new Row(table, db).with("name", "Wie nennt man einen Hering, der immer alles aufschreibt ? Einen Protokollmops. "));
        table.insert(new Row(table, db).with("name", "Wie nennt man einen Hering, der immer alles machen muss?Einen Sollmops."));
        table.insert(new Row(table, db).with("name", "Wie nennt man einen Hering, der immer nur traurige Musik spielt ? Einen Mollmops. "));
        table.insert(new Row(table, db).with("name", "Wie nennt man einen Hering, der immer sauer ist ? Einen Grollmops. "));
        table.insert(new Row(table, db).with("name", "Wie nennt man einen Hering, der immer total begeistert ist?Einen Tollmops."));
        table.insert(new Row(table, db).with("name", "Wie nennt man einen Hering, der Regie führt?Einen(Uwe) Bollmops. "));
        table.insert(new Row(table, db).with("name", "Wie nennt man einen Hering, der sehr unkultiviert ist ? Einen Prollmops. "));
        table.insert(new Row(table, db).with("name", "Wie nennt man einen Hering, der sich für Umfragen interessiert?Einen Pollmops."));
        table.insert(new Row(table, db).with("name", "Wie nennt man einen Hering, der total besoffen ist ? Einen Vollmops. "));
        table.insert(new Row(table, db).with("name", "Wie nennt man einen Hering, der total gerne Puppen mag?Einen Dollmops."));
        table.insert(new Row(table, db).with("name", "Wie nennt man einen Hund der gerne Äpfel isst ? Apfelpudel. "));
        table.insert(new Row(table, db).with("name", "Wie nennt man einen hungrigen risikobereiten Wellensittich ? Trill - Seeker "));
        table.insert(new Row(table, db).with("name", "Wie nennt man einen kleinen Matrosen, der sich nicht wäscht ? Na : Ein Meerschweinchen !"));
        table.insert(new Row(table, db).with("name", "Wie nennt man einen kleinen Türsteher ?Sicherheitshalber. "));
        table.insert(new Row(table, db).with("name", "Wie nennt man einen Landwirt mit Studium ? Einen Ackerdemiker. "));
        table.insert(new Row(table, db).with("name", "Wie nennt man einen überfahrenen Vogel?Piepmatsch !"));
        table.insert(new Row(table, db).with("name", "Wie nennt man Fernsehverbot auf Russisch ?Njetflix. "));
        table.insert(new Row(table, db).with("name", "Wie nennt man Han Solo, wenn er in der Disko rumtanzt ? Han Twerker. "));
        table.insert(new Row(table, db).with("name", "Wie nennt man heute einen Hofnarr ?Untertainer. "));
        table.insert(new Row(table, db).with("name", "Wie nennt man jemand der nur so tut als würde er etwas werfen ? Einen Scheinwerfer. "));
        table.insert(new Row(table, db).with("name", "Wie nennt man jemanden der DIN A4 Blätter scannt ? Skan - din - a - vier. "));
        table.insert(new Row(table, db).with("name", "Wie nennt man Kaninchen im Fitnessstudio ?Pumpernickel. "));
        table.insert(new Row(table, db).with("name", "Wie viel wiegen ein Pferd und ein Hund zusammen ? Ein PfHund !"));
        table.insert(new Row(table, db).with("name", "Wie viele Psychotherapeuten braucht man um eine Glühbirne zu wechseln ?Einen, aber die Birne muss auch wollen. "));
        table.insert(new Row(table, db).with("name", "Wie viele Softwareentwickler braucht man um eine Glühbirne zu wechseln ?Keinen, das ist eindeutig ein Hardwareproblem."));
        table.insert(new Row(table, db).with("name", "Wie war die Stimmung in der DDR ? Sie hielt sich in Grenzen."));
        table.insert(new Row(table, db).with("name", "Wieso können Seeräuber keinen Kreis fahren?-Weil sie Pi raten. "));
        table.insert(new Row(table, db).with("name", "Will jemand einen Witz über Natriumhydrat hören - NaH !"));
        table.insert(new Row(table, db).with("name", "Wo baden Eisbären am liebsten ? Im Nordpool. "));
        table.insert(new Row(table, db).with("name", "Wo geht Darth Vader shoppen ? In der Darth Mall !"));
        table.insert(new Row(table, db).with("name", "Wo gibt es die meisten Gespenster in Europa ?In Buuuuuuuuhdapest !"));
        table.insert(new Row(table, db).with("name", "Wo ist die Deutschlandzentrale von Burger King ? In Whoppertal. "));
        table.insert(new Row(table, db).with("name", "Wo machen Kühe Urlaub?Auf Kuuuhba !"));
        table.insert(new Row(table, db).with("name", "Wo wohnen Katzen ? Im Mietz - Haus !"));
        table.insert(new Row(table, db).with("name", "Wo baden Eisbären am liebsten ? Im Nordpool. "));
        table.insert(new Row(table, db).with("name", "Wohin geht ein Baum, wenn er Rückenschmerzen hat ? Zum Kiefer - Orthopäden. "));
        table.insert(new Row(table, db).with("name", "Wohin geht ein Zyklop, wenn er nicht gut sieht?Zum Augearzt."));
        table.insert(new Row(table, db).with("name", "Wollte Socken bei H&M kaufen.Oma strickt dagegen. "));
        table.insert(new Row(table, db).with("name", "Womit backen Schlümpfe ? Mit Garga - Mehl. "));
        table.insert(new Row(table, db).with("name", "Womit ist der Boden eines Iglus ausgelegt ? Mit Eisdielen. "));
        table.insert(new Row(table, db).with("name", "Womit kann man eine Webseite hosten, aber nur wenn Vollmond ist?Mit einem Werserver. "));
        table.insert(new Row(table, db).with("name", "Womit verprügeln sich Schafe ?Mit dem Mäh - Drescher. "));
        table.insert(new Row(table, db).with("name", "Womit verzieren Rinder ihren Kuchen ? Mit Kuhvertüre. "));
        table.insert(new Row(table, db).with("name", "Wovon träumt eine Katze nachts ? Von einem Muskelkater."));
        table.insert(new Row(table, db).with("name", "Wussten Sie, dass Esoteriker häufig zur Arbeit pendeln...?"));
        table.insert(new Row(table, db).with("name", "Zu welchem Arzt geht Pinocchio ? Zum Holz - Nasen - Ohren - Arzt. "));
        table.insert(new Row(table, db).with("name", "„Du hast aber schon mal einen Schornstein gemauert, oder?“ „Nein, das ist ein Versuchskaminchen."));
    }

    public static void fillMovieTable(Database db, Table table) {
        table.insert(new Row(table, db).with("name", "DRACHENZÄHMEN LEICHT GEMACHT 1"));
        table.insert(new Row(table, db).with("name", "DRACHENZÄHMEN LEICHT GEMACHT 2"));
        table.insert(new Row(table, db).with("name", "DRACHENZÄHMEN LEICHT GEMACHT 3"));
        table.insert(new Row(table, db).with("name", "AQUAMAN"));
        table.insert(new Row(table, db).with("name", "Harry Potter und der Stein der Weisen"));
        table.insert(new Row(table, db).with("name", "Harry Potter und der Orden des Phönix"));
        table.insert(new Row(table, db).with("name", "Harry Potter und der Gefangene von Askaban"));
        table.insert(new Row(table, db).with("name", "Harry Potter und die Heiligtümer des Todes Teil 1"));
        table.insert(new Row(table, db).with("name", "Harry Potter und die Heiligtümer des Todes Teil 2"));
        table.insert(new Row(table, db).with("name", "Harry Potter und die Kammer des Schreckens "));
        table.insert(new Row(table, db).with("name", "Harry Potter und der Halbblutprinz"));
        table.insert(new Row(table, db).with("name", "DEADPOOL"));
        table.insert(new Row(table, db).with("name", "DEADPOOL 2"));
        table.insert(new Row(table, db).with("name", "BLACK PANTHER"));
        table.insert(new Row(table, db).with("name", "EXTREME RAGE"));
        table.insert(new Row(table, db).with("name", "XXX 3: DIE RÜCKKEHR DES XANDER CAGE"));
        table.insert(new Row(table, db).with("name", "XXX - TRIPLE X"));
        table.insert(new Row(table, db).with("name", "XXX² - THE NEXT LEVEL"));
        table.insert(new Row(table, db).with("name", "SKYSCRAPER"));
        table.insert(new Row(table, db).with("name", "96 HOURS"));
        table.insert(new Row(table, db).with("name", "96 HOURS - TAKEN 2"));
        table.insert(new Row(table, db).with("name", "96 HOURS - TAKEN 3"));
        table.insert(new Row(table, db).with("name", "AFTER EARTH"));
        table.insert(new Row(table, db).with("name", "ALADDIN"));
        table.insert(new Row(table, db).with("name", "ARTHUR UND DIE MINIMOYS 1"));
        table.insert(new Row(table, db).with("name", "ARTHUR UND DIE MINIMOYS 2"));
        table.insert(new Row(table, db).with("name", "ARTHUR UND DIE MINIMOYS 3"));
        table.insert(new Row(table, db).with("name", "ALITA: BATTLE ANGEL"));
        table.insert(new Row(table, db).with("name", "ALVIN UND DIE CHIPMUNKS"));
        table.insert(new Row(table, db).with("name", "ANGEL HAS FALLEN"));
        table.insert(new Row(table, db).with("name", "BRIGHT"));
        table.insert(new Row(table, db).with("name", "BUMBLEBEE"));
        table.insert(new Row(table, db).with("name", "BOB, DER STREUNER"));
        table.insert(new Row(table, db).with("name", "BLOODSHOT"));
        table.insert(new Row(table, db).with("name", "BLINKY BILL - DAS MEER DER WEISSEN DRACHEN"));
        table.insert(new Row(table, db).with("name", "ANT-MAN"));
        table.insert(new Row(table, db).with("name", "ANT-MAN AND THE WASP"));
        table.insert(new Row(table, db).with("name", "RAYA UND DER LETZTE DRACHE"));
        table.insert(new Row(table, db).with("name", "ARLO & SPOT"));
        table.insert(new Row(table, db).with("name", "BAD BOYS"));
        table.insert(new Row(table, db).with("name", "BAD BOYS FOR LIFE"));
        table.insert(new Row(table, db).with("name", "BAYMAX - RIESIGES ROBOWABOHU"));
        table.insert(new Row(table, db).with("name", "BAYWATCH"));
        table.insert(new Row(table, db).with("name", "BEE MOVIE - DAS HONIGKOMPLOTT"));
        table.insert(new Row(table, db).with("name", "BARBIE IN SCHWANENSEE "));
        table.insert(new Row(table, db).with("name", "BARBIE IN: DIE SUPER-PRINZESSIN"));
        table.insert(new Row(table, db).with("name", "BARBIE IN DER NUSSKNACKER"));
        table.insert(new Row(table, db).with("name", "BARBIE ALS RAPUNZEL"));
        table.insert(new Row(table, db).with("name", "ASTERIX BEI DEN OLYMPISCHEN SPIELEN"));
        table.insert(new Row(table, db).with("name", "AVATAR AUFBRUCH NACH PANDORA"));
        table.insert(new Row(table, db).with("name", "AVENGERS ENDGAME"));
        table.insert(new Row(table, db).with("name", "AVENGERS 3: INFINITY WAR"));
        table.insert(new Row(table, db).with("name", "ARTEMIS FOWL"));
        table.insert(new Row(table, db).with("name", "ATLANTIS - DIE RÜCKKEHR"));
        table.insert(new Row(table, db).with("name", "AB DURCH DIE HECKE"));
        table.insert(new Row(table, db).with("name", "Frozen"));
        table.insert(new Row(table, db).with("name", "DIE EISKÖNIGIN 2"));
        table.insert(new Row(table, db).with("name", "Vaiana"));
        table.insert(new Row(table, db).with("name", "Rapunzel"));
        table.insert(new Row(table, db).with("name", "Karate kid"));
        table.insert(new Row(table, db).with("name", "PHANTASTISCHE TIERWESEN UND WO SIE ZU FINDEN SIND"));
        table.insert(new Row(table, db).with("name", "PHANTASTISCHE TIERWESEN - GRINDELWALDS VERBRECHEN"));
        table.insert(new Row(table, db).with("name", "ZOOMANIA"));
        table.insert(new Row(table, db).with("name", "Merlin"));
        table.insert(new Row(table, db).with("name", "Shrek"));
        table.insert(new Row(table, db).with("name", "Tarzan"));
        table.insert(new Row(table, db).with("name", "Die fantastische Welt von Oz"));
        table.insert(new Row(table, db).with("name", "Monster High"));
        table.insert(new Row(table, db).with("name", "CAPTAIN AMERICA: THE FIRST AVENGER"));
        table.insert(new Row(table, db).with("name", "CAPTAIN AMERICA 2: THE RETURN OF THE FIRST AVENGER"));
        table.insert(new Row(table, db).with("name", "CAPTAIN MARVEL"));
        table.insert(new Row(table, db).with("name", "CARS"));
        table.insert(new Row(table, db).with("name", "CARS 2"));
        table.insert(new Row(table, db).with("name", "CARS 3: EVOLUTION"));
        table.insert(new Row(table, db).with("name", "CHAPPIE"));
        table.insert(new Row(table, db).with("name", "CHARLIE UND DIE SCHOKOLADENFABRIK "));
        table.insert(new Row(table, db).with("name", "CROCODILE DUNDEE"));
        table.insert(new Row(table, db).with("name", "CROCODILE DUNDEE II"));
        table.insert(new Row(table, db).with("name", "CROCODILE DUNDEE IN LOS ANGELES"));
        table.insert(new Row(table, db).with("name", "DADDY OHNE PLAN"));
        table.insert(new Row(table, db).with("name", "DAS HAUS DER GEHEIMNISVOLLEN UHREN"));
        table.insert(new Row(table, db).with("name", "DAS VERMÄCHTNIS DER TEMPELRITTER"));
        table.insert(new Row(table, db).with("name", "DAS VERMÄCHTNIS DES GEHEIMEN BUCHES"));
        table.insert(new Row(table, db).with("name", "DAS VERSCHOLLENE MEDAILLON"));
        table.insert(new Row(table, db).with("name", "DER HERR DER RINGE - DIE GEFÄHRTEN"));
        table.insert(new Row(table, db).with("name", "DER HERR DER RINGE - DIE RÜCKKEHR DES KÖNIGS"));
        table.insert(new Row(table, db).with("name", "DER HERR DER RINGE - DIE ZWEI TÜRME"));
        table.insert(new Row(table, db).with("name", "DER HOBBIT - DIE SCHLACHT DER FÜNF HEERE"));
        table.insert(new Row(table, db).with("name", "DER HOBBIT EINE UNERWARTETE REISE"));
        table.insert(new Row(table, db).with("name", "DER HOBBIT: SMAUGS EINÖDE"));
        table.insert(new Row(table, db).with("name", "DER KAUFHAUS COP"));
        table.insert(new Row(table, db).with("name", "DER KAUFHAUS COP 2"));
        table.insert(new Row(table, db).with("name", "DER KNASTCOACH"));
        table.insert(new Row(table, db).with("name", "DER KÖNIG DER LÖWEN"));
        table.insert(new Row(table, db).with("name", "DER PLANET DER AFFEN: PREVOLUTION"));
        table.insert(new Row(table, db).with("name", "DER POLAREXPRESS"));
        table.insert(new Row(table, db).with("name", "DER PRINZ AUS ZAMUNDA"));
        table.insert(new Row(table, db).with("name", "DER SPION VON NEBENAN"));
        table.insert(new Row(table, db).with("name", "DESCENDANTS - DIE NACHKOMMEN"));
        table.insert(new Row(table, db).with("name", "DESCENDANTS 2"));
        table.insert(new Row(table, db).with("name", "DESCENDANTS 3 - DIE NACHKOMMEN"));
        table.insert(new Row(table, db).with("name", "DESCENDANTS 3 - DIE NACHKOMMEN"));
        table.insert(new Row(table, db).with("name", "DIE BESTIMMUNG - ALLEGIANT PART 1"));
        table.insert(new Row(table, db).with("name", "DIE BESTIMMUNG - DIVERGENT"));
        table.insert(new Row(table, db).with("name", "DIE BIENE MAJA - DER FILM"));
        table.insert(new Row(table, db).with("name", "DIE CHRONIKEN VON NARNIA - PRINZ KASPIAN VON NARNIA"));
        table.insert(new Row(table, db).with("name", "DIE CHRONIKEN VON NARNIA: DER KÖNIG VON NARNIA"));
        table.insert(new Row(table, db).with("name", "DIE CHRONIKEN VON NARNIA: DIE REISE AUF DER MORGENRÖTE"));
        table.insert(new Row(table, db).with("name", "DIE CROODS"));
        table.insert(new Row(table, db).with("name", "DIE FANTASTISCHE REISE DES DR. DOLITTLE"));
        table.insert(new Row(table, db).with("name", "DIE HÜTER DES LICHTS"));
        table.insert(new Row(table, db).with("name", "DIE PEANUTS - DER FILM"));
        table.insert(new Row(table, db).with("name", "DIE PINGUINE AUS MADAGASCAR"));
        table.insert(new Row(table, db).with("name", "DIE SCHLÜMPFE"));
        table.insert(new Row(table, db).with("name", "DIE SCHLÜMPFE 2"));
        table.insert(new Row(table, db).with("name", "DIE SCHLÜMPFE 3 - DAS VERLORENE DORF"));
        table.insert(new Row(table, db).with("name", "DIE SCHÖNE UND DAS BIEST"));
        table.insert(new Row(table, db).with("name", "DIE TRIBUTE VON PANEM - CATCHING FIRE"));
        table.insert(new Row(table, db).with("name", "DIE TRIBUTE VON PANEM - THE HUNGER GAMES"));
        table.insert(new Row(table, db).with("name", "DIE TRIBUTE VON PANEM - MOCKINGJAY: TEIL 1"));
        table.insert(new Row(table, db).with("name", "DIE TRIBUTE VON PANEM - MOCKINGJAY: TEIL 2"));
        table.insert(new Row(table, db).with("name", "DIE UNFASSBAREN - NOW YOU SEE ME"));
        table.insert(new Row(table, db).with("name", "DIE UNFASSBAREN 2"));
        table.insert(new Row(table, db).with("name", "DIE UNGLAUBLICHEN 2"));
        table.insert(new Row(table, db).with("name", "DOCTOR STRANGE"));
        table.insert(new Row(table, db).with("name", "DORA UND DIE GOLDENE STADT"));
        table.insert(new Row(table, db).with("name", "DRAGONBALL EVOLUTION"));
        table.insert(new Row(table, db).with("name", "DUMBO"));
        table.insert(new Row(table, db).with("name", "THE DEATH OF SUPERMAN"));
        table.insert(new Row(table, db).with("name", "MISSION: IMPOSSIBLE - FALLOUT"));
        table.insert(new Row(table, db).with("name", "MISSION: IMPOSSIBLE - ROGUE NATION"));
        table.insert(new Row(table, db).with("name", "MISSION: IMPOSSIBLE - 2"));
        table.insert(new Row(table, db).with("name", "MISSION: IMPOSSIBLE - 3"));
        table.insert(new Row(table, db).with("name", "MISSION: IMPOSSIBLE - PHANTOM PROTOKOLL "));
        table.insert(new Row(table, db).with("name", "PACIFIC RIM 2: UPRISING"));
        table.insert(new Row(table, db).with("name", "PRINCE OF PERSIA - DER SAND DER ZEIT"));
        table.insert(new Row(table, db).with("name", "PREDATORS"));
        table.insert(new Row(table, db).with("name", "PRAKTI.COM"));
        table.insert(new Row(table, db).with("name", "POWER RANGERS"));
        table.insert(new Row(table, db).with("name", "POKEMON MEISTERDETEKTIV PIKACHU"));
        table.insert(new Row(table, db).with("name", "PIXELS"));
        table.insert(new Row(table, db).with("name", "PETS"));
        table.insert(new Row(table, db).with("name", "PETS 2"));
        table.insert(new Row(table, db).with("name", "PETER HASE"));
        table.insert(new Row(table, db).with("name", "PERCY JACKSON - DIEBE IM OLYMP"));
        table.insert(new Row(table, db).with("name", "PERCY JACKSON - IM BANN DES ZYKLOPEN"));
        table.insert(new Row(table, db).with("name", "PASSENGERS"));
        table.insert(new Row(table, db).with("name", "PARKER"));
        table.insert(new Row(table, db).with("name", "PAN"));
        table.insert(new Row(table, db).with("name", "PACIFIC RIM"));
        table.insert(new Row(table, db).with("name", "ONWARD: KEINE HALBEN SACHEN"));
        table.insert(new Row(table, db).with("name", "OBEN"));
        table.insert(new Row(table, db).with("name", "NACHTS IM MUSEUM"));
        table.insert(new Row(table, db).with("name", "NACHTS IM MUSEUM 2"));
        table.insert(new Row(table, db).with("name", "NACHTS IM MUSEUM - DAS GEHEIMNISVOLLE GRABMAL"));
        table.insert(new Row(table, db).with("name", "MORTAL ENGINES KRIEG DER STÄDTE"));
        table.insert(new Row(table, db).with("name", "MONSTERS VS. ALIENS"));
        table.insert(new Row(table, db).with("name", "MONSTER TRUCKS"));
        table.insert(new Row(table, db).with("name", "MOGLI: LEGENDE DES DSCHUNGELS"));
        table.insert(new Row(table, db).with("name", "MINIONS"));
        table.insert(new Row(table, db).with("name", "MERIDA - LEGENDE DER HIGHLANDS"));
        table.insert(new Row(table, db).with("name", "MENSCH, DAVE!"));
        table.insert(new Row(table, db).with("name", "MEN IN BLACK: INTERNATIONAL"));
        table.insert(new Row(table, db).with("name", "MEN IN BLACK"));
        table.insert(new Row(table, db).with("name", "MEN IN BLACK II"));
        table.insert(new Row(table, db).with("name", "MEN IN BLACK 3"));
        table.insert(new Row(table, db).with("name", "MAZE RUNNER 3: DIE AUSERWÄHLTEN IN DER TODESZONE"));
        table.insert(new Row(table, db).with("name", "MAZE RUNNER 2 - DIE AUSERWÄHLTEN IN DER BRANDWÜSTE"));
        table.insert(new Row(table, db).with("name", "MAZE RUNNER - DIE AUSERWÄHLTEN IM LABYRINTH"));
        table.insert(new Row(table, db).with("name", "MAX STEEL"));
        table.insert(new Row(table, db).with("name", "MATRIX"));
        table.insert(new Row(table, db).with("name", "MATRIX RELOADED"));
        table.insert(new Row(table, db).with("name", "MATRIX REVOLUTIONS"));
        table.insert(new Row(table, db).with("name", "MARVEL'S THE AVENGERS"));
        table.insert(new Row(table, db).with("name", "MARVEL'S THE AVENGERS 2: AGE OF ULTRON"));
        table.insert(new Row(table, db).with("name", "MAN OF STEEL"));
        table.insert(new Row(table, db).with("name", "MALEFICENT - DIE DUNKLE FEE"));
        table.insert(new Row(table, db).with("name", "MALEFICENT 2: MÄCHTE DER FINSTERNIS"));
        table.insert(new Row(table, db).with("name", "MADAGASCAR"));
        table.insert(new Row(table, db).with("name", "MADAGASCAR 2 "));
        table.insert(new Row(table, db).with("name", "MADAGASCAR 3 - FLUCHT DURCH EUROPA"));
        table.insert(new Row(table, db).with("name", "MAD MAX: FURY ROAD"));
        table.insert(new Row(table, db).with("name", "LUCY"));
        table.insert(new Row(table, db).with("name", "LUCAS, DER AMEISENSCHRECK"));
        table.insert(new Row(table, db).with("name", "LONDON HAS FALLEN"));
        table.insert(new Row(table, db).with("name", "LILO & STITCH"));
        table.insert(new Row(table, db).with("name", "LILO & STITCH 2 - STITCH VÖLLIG ABGEDREHT"));
        table.insert(new Row(table, db).with("name", "LET'S BE COPS - DIE PARTY-BULLE"));
        table.insert(new Row(table, db).with("name", "LEGION"));
        table.insert(new Row(table, db).with("name", "LEGEND OF TARZAN"));
        table.insert(new Row(table, db).with("name", "LEAGUE OF GODS"));
        table.insert(new Row(table, db).with("name", "LARA CROFT: TOMB RAIDER"));
        table.insert(new Row(table, db).with("name", "KUNG FU YOGA - DER GOLDENE ARM DER GÖTTER"));
        table.insert(new Row(table, db).with("name", "KUNG FU PANDA - DIE GEHEIMNISSE DER MEISTER"));
        table.insert(new Row(table, db).with("name", "KUNG FU PANDA 2"));
        table.insert(new Row(table, db).with("name", "KUNG FU PANDA 3"));
        table.insert(new Row(table, db).with("name", "KUBO - DER TAPFERE SAMURAI"));
        table.insert(new Row(table, db).with("name", "KINGSMAN 1: THE SECRET SERVICE"));
        table.insert(new Row(table, db).with("name", "KINGSMAN 2: THE GOLDEN CIRCLE"));
        table.insert(new Row(table, db).with("name", "KINGSMAN 3:"));
        table.insert(new Row(table, db).with("name", "KINDSKÖPFE"));
        table.insert(new Row(table, db).with("name", "KINDSKÖPFE 2"));
        table.insert(new Row(table, db).with("name", "KINDERGARTEN COP 2"));
        table.insert(new Row(table, db).with("name", "KICK-ASS"));
        table.insert(new Row(table, db).with("name", "KICK-ASS 2"));
        table.insert(new Row(table, db).with("name", "KHUMBA - DAS ZEBRA OHNE STREIFEN AM POPO"));
        table.insert(new Row(table, db).with("name", "KEVIN - ALLEIN ZU HAUS"));
        table.insert(new Row(table, db).with("name", "KEVIN - ALLEIN IN NEW YORK"));
        table.insert(new Row(table, db).with("name", "KEINOHRHASE & ZWEIOHRKÜKEN"));
        table.insert(new Row(table, db).with("name", "JUSTICE LEAGUE"));
        table.insert(new Row(table, db).with("name", "JURASSIC WORLD"));
        table.insert(new Row(table, db).with("name", "JUPITER ASCENDING"));
        table.insert(new Row(table, db).with("name", "JUMANJI: WELCOME TO THE JUNGLE"));
        table.insert(new Row(table, db).with("name", "JUMANJI: THE NEXT LEVEL"));
        table.insert(new Row(table, db).with("name", "JOKER"));
        table.insert(new Row(table, db).with("name", "JOHNNY ENGLISH - MAN LEBT NUR DREIMAL"));
        table.insert(new Row(table, db).with("name", "JOHNNY ENGLISH "));
        table.insert(new Row(table, db).with("name", "JIU JITSU"));
        table.insert(new Row(table, db).with("name", "JIM KNOPF UND LUKAS DER LOKOMOTIVFÜHRER"));
        table.insert(new Row(table, db).with("name", "JAMES BOND 007 - SPECTRE"));
        table.insert(new Row(table, db).with("name", "JAMES BOND 007 - STIRB AN EINEM ANDEREN TAG"));
        table.insert(new Row(table, db).with("name", "JAMES BOND 007 - SKYFALL"));
        table.insert(new Row(table, db).with("name", "JAMES BOND 007 - CASINO ROYALE"));
        table.insert(new Row(table, db).with("name", "JAGDFIEBER 1"));
        table.insert(new Row(table, db).with("name", "JAGDFIEBER 2"));
        table.insert(new Row(table, db).with("name", "JAGDFIEBER 3"));
        table.insert(new Row(table, db).with("name", "JAGDFIEBER 4 - UNGEBETENE BESUCHER"));
        table.insert(new Row(table, db).with("name", "JAGD AUF DEN SCHATZ DER RIESEN"));
        table.insert(new Row(table, db).with("name", "JACK REACHER - DIE JAGD HAT BEGONNEN!"));
        table.insert(new Row(table, db).with("name", "JACK REACHER - 2: KEIN WEG ZURÜCK"));
        table.insert(new Row(table, db).with("name", "IRON MAN 1"));
        table.insert(new Row(table, db).with("name", "IRON MAN 2"));
        table.insert(new Row(table, db).with("name", "IRON MAN 3"));
        table.insert(new Row(table, db).with("name", "INSIDE OUT - ALLES STEHT KOPF"));
        table.insert(new Row(table, db).with("name", "INDIANA JONES UND DER TEMPEL DES TODES"));
        table.insert(new Row(table, db).with("name", "INDIANA JONES UND DER LETZTE KREUZZUG"));
        table.insert(new Row(table, db).with("name", "INDIANA JONES UND DAS KÖNIGREICH DES KRISTALLSCHÄDEL"));
        table.insert(new Row(table, db).with("name", "INDIANA JONES - JÄGER DES VERLORENEN SCHATZES"));
        table.insert(new Row(table, db).with("name", "INDEPENDENTS DAY 1"));
        table.insert(new Row(table, db).with("name", "INDEPENDENCE DAY 2: WIEDERKEHR "));
        table.insert(new Row(table, db).with("name", "IMMORTAL WARS - NUR DER STÄRKSTE ÜBERLEBT"));
        table.insert(new Row(table, db).with("name", "ICH BIN NUMMER 4"));
        table.insert(new Row(table, db).with("name", "ICH - EINFACH UNVERBESSERLICH 1"));
        table.insert(new Row(table, db).with("name", "ICH - EINFACH UNVERBESSERLICH 2"));
        table.insert(new Row(table, db).with("name", "ICH - EINFACH UNVERBESSERLICH 3"));
        table.insert(new Row(table, db).with("name", "ICE AGE 1"));
        table.insert(new Row(table, db).with("name", "ICE AGE 2"));
        table.insert(new Row(table, db).with("name", "ICE AGE 3"));
        table.insert(new Row(table, db).with("name", "ICE AGE 4 - VOLL VERSCHOBEN"));
        table.insert(new Row(table, db).with("name", "ICE AGE 5 - KOLLISION VORAUS!"));
        table.insert(new Row(table, db).with("name", "I, ROBOT"));
        table.insert(new Row(table, db).with("name", "HÜTER DER ERINNERUNG - THE GIVER "));
        table.insert(new Row(table, db).with("name", "HULK"));
        table.insert(new Row(table, db).with("name", "HUI BUH, DAS SCHLOSSGESPENST"));
        table.insert(new Row(table, db).with("name", "HOTEL TRANSSILVANIEN 1"));
        table.insert(new Row(table, db).with("name", "HOTEL TRANSSILVANIEN 2"));
        table.insert(new Row(table, db).with("name", "HOTEL TRANSSILVANIEN 3 - EIN MONSTER URLAUB (2018)"));
        table.insert(new Row(table, db).with("name", "HOTEL TRANSSILVANIEN 4"));
        table.insert(new Row(table, db).with("name", "HITMAN - AGENT 47"));
        table.insert(new Row(table, db).with("name", "HIGH SCHOOL MUSICAL 1:"));
        table.insert(new Row(table, db).with("name", "HIGH SCHOOL MUSICAL 2: SINGT ALLE ODER KEINER! (2007)"));
        table.insert(new Row(table, db).with("name", "HIGH SCHOOL MUSICAL 3: SENIOR YEAR (2008)"));
        table.insert(new Row(table, db).with("name", "HERCULES"));
        table.insert(new Row(table, db).with("name", "HAPPY FEET"));
        table.insert(new Row(table, db).with("name", "HANCOCK"));
        table.insert(new Row(table, db).with("name", "GUARDIANS OF THE GALAXY"));
        table.insert(new Row(table, db).with("name", "GUARDIANS OF THE GALAXY VOL. 2"));
        table.insert(new Row(table, db).with("name", "GREEN LANTERN"));
        table.insert(new Row(table, db).with("name", "GODZILLA 2 KING OF THE MONSTERS "));
        table.insert(new Row(table, db).with("name", "GODS OF EGYPT "));
        table.insert(new Row(table, db).with("name", "GOD OF WAR"));
        table.insert(new Row(table, db).with("name", "GNOMEO UND JULIA"));
        table.insert(new Row(table, db).with("name", "GHOST RIDER: SPIRIT OF VENGEANCE"));
        table.insert(new Row(table, db).with("name", "GEMINI MAN"));
        table.insert(new Row(table, db).with("name", "GARFIELD - FETT IM LEBEN"));
        table.insert(new Row(table, db).with("name", "GARFIELD - TIERISCHE HELDEN"));
        table.insert(new Row(table, db).with("name", "FÜNF FREUNDE UND DAS TAL DER DINOSAURIER (2018)"));
        table.insert(new Row(table, db).with("name", "FÜNF FREUNDE 3"));
        table.insert(new Row(table, db).with("name", "FÜNF FREUNDE 4"));
        table.insert(new Row(table, db).with("name", "FREUNDE MIT GEWISSEN VORZÜGEN "));
        table.insert(new Row(table, db).with("name", "FLUCH DER KARIBIK"));
        table.insert(new Row(table, db).with("name", "FLUCH DER KARIBIK 2"));
        table.insert(new Row(table, db).with("name", "FLUCH DER KARIBIK 3 - AM ENDE DER WELT (2007)"));
        table.insert(new Row(table, db).with("name", "FLUCH DER KARIBIK 4 - FREMDE GEZEITEN (2011)"));
        table.insert(new Row(table, db).with("name", "FLUCH DER KARIBIK SALAZARS RACHE"));
        table.insert(new Row(table, db).with("name", "FINDET DORIE"));
        table.insert(new Row(table, db).with("name", "FERDINAND - GEHT STIERISCH AB"));
        table.insert(new Row(table, db).with("name", "FASTER"));
        table.insert(new Row(table, db).with("name", "FAST & FURIOUS: NEUES MODELL. ORIGINALTEILE (2009)"));
        table.insert(new Row(table, db).with("name", "FAST & FURIOUS FIVE"));
        table.insert(new Row(table, db).with("name", "FAST & FURIOUS 6"));
        table.insert(new Row(table, db).with("name", "FAST AND FURIOUS 7"));
        table.insert(new Row(table, db).with("name", "FAST & FURIOUS 8"));
        table.insert(new Row(table, db).with("name", "FAST & FURIOUS PRESENTS: HOBBS & SHAW (2019)"));
        table.insert(new Row(table, db).with("name", "FANTASTIC FOUR"));
        table.insert(new Row(table, db).with("name", "FANTASTIC FOUR - RISE OF THE SILVER SURFER (2007)"));
        table.insert(new Row(table, db).with("name", "FACK JU GÖHTE"));
        table.insert(new Row(table, db).with("name", "FACK JU GÖHTE 2"));
        table.insert(new Row(table, db).with("name", "FACK JU GÖHTE 3"));
        table.insert(new Row(table, db).with("name", "Final Destination 5"));
        table.insert(new Row(table, db).with("name", "EXODUS - GÖTTER UND KÖNIGE"));
        table.insert(new Row(table, db).with("name", "ESPEN UND DIE LEGENDE VOM BERGKÖNIG (2017)"));
        table.insert(new Row(table, db).with("name", "EMOJI - DER FILM"));
        table.insert(new Row(table, db).with("name", "ELLIOT, DER DRACHE"));
        table.insert(new Row(table, db).with("name", "LEG DICH NICHT MIT ZOHAN AN"));
        table.insert(new Row(table, db).with("name", "17 Again"));
        table.insert(new Row(table, db).with("name", "The last witch Hunter"));
    }

    public static void fillGameTable(Database db, Table table) {
        table.insert(new Row(table, db).with("name", "Valorant"));
        table.insert(new Row(table, db).with("name", "Minecraft"));
        table.insert(new Row(table, db).with("name", "Call of Duty: Black Ops Cold War"));
        table.insert(new Row(table, db).with("name", "Call of Duty: Black Ops 2"));
        table.insert(new Row(table, db).with("name", "Call of Duty: Warzone"));
        table.insert(new Row(table, db).with("name", "Call of Duty: Modern Warfare"));
        table.insert(new Row(table, db).with("name", "League of Legends"));
        table.insert(new Row(table, db).with("name", "Apex Legens"));
        table.insert(new Row(table, db).with("name", "Grand Theft Auto 5"));
        table.insert(new Row(table, db).with("name", "Shellshock Live"));
        table.insert(new Row(table, db).with("name", "Remant from the Ashes"));
        table.insert(new Row(table, db).with("name", "Rougue Company"));
        table.insert(new Row(table, db).with("name", "Pico Park"));
        table.insert(new Row(table, db).with("name", "Raft"));
        table.insert(new Row(table, db).with("name", "Rocket_League"));
        table.insert(new Row(table, db).with("name", "Split Gate"));
        table.insert(new Row(table, db).with("name", "Fornite"));
        table.insert(new Row(table, db).with("name", "Orcs Must Die! 3"));
        table.insert(new Row(table, db).with("name", "Immortal Fenxy Rising"));
        table.insert(new Row(table, db).with("name", "Stranded_Deep"));
        table.insert(new Row(table, db).with("name", "Among Us"));
        table.insert(new Row(table, db).with("name", "Watch Dogs 2"));
        table.insert(new Row(table, db).with("name", "Satisfactory"));
        table.insert(new Row(table, db).with("name", "Kingdom new Lands"));
        table.insert(new Row(table, db).with("name", "Counter Strike"));
        table.insert(new Row(table, db).with("name", "FarCry 5"));
        table.insert(new Row(table, db).with("name", "FarCry 6"));
        table.insert(new Row(table, db).with("name", "Mud Runner"));
        table.insert(new Row(table, db).with("name", "Battelfront 2"));
        table.insert(new Row(table, db).with("name", "StarCraft 1"));
        table.insert(new Row(table, db).with("name", "StarCraft 2"));
        table.insert(new Row(table, db).with("name", "Age of Empire 2"));
        table.insert(new Row(table, db).with("name", "Subnautica"));
        table.insert(new Row(table, db).with("name", "Subnautica Below Zero"));
        table.insert(new Row(table, db).with("name", "Sea of Thives"));
        table.insert(new Row(table, db).with("name", "Supraland"));
        table.insert(new Row(table, db).with("name", "Terraria"));
        table.insert(new Row(table, db).with("name", "Stone.world"));
        table.insert(new Row(table, db).with("name", "Overcooked"));
    }
}
