# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Deploy Java

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean install
      - name: 🚚 Get latest code
        uses: actions/checkout@v4
      - name: Build Jar
        run: cd ${{ github.workspace }} && mvn install
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          local-dir: '${{ github.workspace }}/target/'
          server-dir: ${{ secrets.SERVER_DIR }}
          exclude: |
            **/classes/**
            **/generated-sources/**
            **/maven-archiver/**
            **/maven-status/**

      - name: ls -a via ssh
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd ${{ secrets.SERVER_DIR }} && cd ../
            docker compose down gd_entertainment
            docker compose build --no-cache gd_entertainment
            docker compose up -d gd_entertainment
          host: ${{ secrets.HOST }}
          port: 22
          user: ${{ secrets.USERNAME }}
          pass : ${{ secrets.PASSWORD }}
